-- Seed: notable deceased people (data from Wikidata; summaries from Wikipedia, CC BY-SA 4.0).
-- Photos are hotlinked from Wikimedia Commons. Year-only birth dates are left NULL.

INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Sheikh Mujibur Rahman$b$, DATE '1920-03-17', DATE '1975-08-15', $b$Sheikh Mujibur Rahman was a Bangladeshi politician, revolutionary, statesman, activist, and diarist who was the founding president of Bangladesh. As the leader of Bangladesh, he led the country as its president and prime minister from 1972 until his assassination in a coup d'état in 1975.

Source: Wikipedia — https://en.wikipedia.org/wiki/Sheikh_Mujibur_Rahman$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Sheikh%20Mujibur%20Rahman%20portrait%20%28PID-h0066%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Khaleda Zia$b$, DATE '1945-08-15', DATE '2025-12-30', $b$Begum Khaleda Zia was a Bangladeshi politician who twice served as prime minister of Bangladesh, from 1991 to 1996 and again from 2001 to 2006. She was the first female prime minister of Bangladesh and the second female prime minister in the Muslim world after Benazir Bhutto. She was the wife of the former president of Bangladesh and army chief, Ziaur Rahman and was first lady from 1977 to 1981. She was the longest serving chairperson of the Bangladesh Nationalist Party (BNP) from 1984 until her death in 2025.

Source: Wikipedia — https://en.wikipedia.org/wiki/Khaleda_Zia$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Khaleda%20Zia%20cropped%20from%20Secretary%20Kerry%20Poses%20for%20a%20Photo%20With%20Government%20Opposition%20Leader%20Begum%20Khaled%20Zia%20at%20U.S.%20Embassy%20Dhaka%20%2829284522026%29%20%28cropped%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Kazi Nazrul Islam$b$, DATE '1899-05-24', DATE '1976-08-29', $b$Kazi Nazrul Islam was a Bengali poet, short story writer, journalist, lyricist, and musician. He was later honoured with the title of national poet of Bangladesh. Nazrul produced a large body of poetry, music, messages, novels, and stories with themes that included equality, justice, anti-imperialism, humanity, rebellion against oppression and religious devotion. Nazrul Islam's activism for political and social justice as well as writing a poem titled "Bidrohī", meaning "the rebel" in Bengali, earned him the title of "Bidrohī Kôbi". His compositions form the avant-garde music genre of Nazrul Gīti.

Source: Wikipedia — https://en.wikipedia.org/wiki/Kazi_Nazrul_Islam$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Nazrul.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Zillur Rahman$b$, DATE '1929-03-09', DATE '2013-03-20', $b$Mohammed Zillur Rahman was a Bangladeshi politician who served as President of Bangladesh from 2009 until his death in 2013. He was also a senior presidium member of the Awami League. He is the third president of Bangladesh to die in office and the first to die of natural causes, as both Sheikh Mujibur Rahman and Ziaur Rahman were assassinated.

Source: Wikipedia — https://en.wikipedia.org/wiki/Zillur_Rahman$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Zillur%20Rahman%20in%20Dhaka%20on%20September%2007%2C%202011.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Ziaur Rahman$b$, DATE '1936-01-19', DATE '1981-05-30', $b$Ziaur Rahman was a Bangladeshi military leader and politician who served as the sixth president of Bangladesh from 1977 until his assassination in 1981. One of the leading figures of the country's independence war, Zia broadcast the Bangladeshi declaration of independence in March 1971 from Chittagong. In the aftermath of the Sipahi-Janata revolution in 1975, he consolidated power to lead Bangladesh with pragmatic policies through economic liberalisation and civic nationalism that significantly contributed to the economic recovery of the country. He is often referred to as the Shaheed President in Bangladesh. He also founded the Bangladesh Nationalist Party (BNP).

Source: Wikipedia — https://en.wikipedia.org/wiki/Ziaur_Rahman$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Bangladeshi%20president%20Ziaur%20Rahman%2C%20Bir%20Uttom.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Iajuddin Ahmed$b$, DATE '1931-02-01', DATE '2012-12-10', $b$Iajuddin Ahmed was the president of Bangladesh, serving from 2002 to 2009.

Source: Wikipedia — https://en.wikipedia.org/wiki/Iajuddin_Ahmed$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Iajuddin%20Ahmed%20at%20Zia%20International%20Airport%20in%20Dhaka%20%28cropped%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Begum Rokeya$b$, DATE '1880-12-09', DATE '1932-12-09', $b$Rokeya Sakhawat Hossain, commonly known as Begum Rokeya, was a prominent Bengali feminist thinker, writer, educator and political activist from British India. She is widely regarded as a pioneer of feminism in Bangladesh and India.

Source: Wikipedia — https://en.wikipedia.org/wiki/Begum_Rokeya$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Begum%20Rokeya.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Khwaja Nazimuddin$b$, DATE '1894-07-19', DATE '1964-10-22', $b$Sir Khwaja Nazimuddin was a Pakistani politician who served as the second governor-general of Pakistan from 1948 to 1951, and then as the second prime minister of Pakistan from 1951 to 1953.

Source: Wikipedia — https://en.wikipedia.org/wiki/Khwaja_Nazimuddin$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Khawaja%20Nazimuddin.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Hussain Muhammad Ershad$b$, DATE '1930-02-01', DATE '2019-07-14', $b$Hussain Muhammad Ershad was a Bangladeshi military officer, dictator and politician who served as President of Bangladesh from 1983 to 1990.

Source: Wikipedia — https://en.wikipedia.org/wiki/Hussain_Muhammad_Ershad$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Hussain%20Muhammad%20Ershad%20at%20a%20political%20program%20in%20Dhaka%2C%202018%20%281%29%20%28cropped%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Mohammad Ali Bogra$b$, DATE '1909-10-19', DATE '1963-01-23', $b$Syed Mohammad Ali Chowdhury Bogra was a Pakistani politician and diplomat who served as the third prime minister of Pakistan from 1953 to 1955. He was appointed in this capacity in 1953 until he stepped down in 1955 in favour of his federal finance minister Chaudhri Muhammad Ali.

Source: Wikipedia — https://en.wikipedia.org/wiki/Mohammad_Ali_Bogra$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Pakistani%20Prime%20Minister%20Bogra%20with%20Eisenhower%20%28cropped%29.png?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Shahabuddin Ahmed$b$, DATE '1930-02-01', DATE '2022-03-19', $b$Shahabuddin Ahmed was a Bangladeshi jurist and statesman who served as the president of Bangladesh from 1996 to 2001 and as the chief justice of Bangladesh from 1990 to 1995. He previously served as the acting president during 1990–91 when Hussain Muhammad Ershad resigned from the post. He headed a interim government and oversaw a general election in February 1991.

Source: Wikipedia — https://en.wikipedia.org/wiki/Shahabuddin_Ahmed$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Shahabuddin%20Ahmed.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Abdur Rahman Biswas$b$, DATE '1926-09-01', DATE '2017-11-03', $b$Abdur Rahman Biswas was a Bangladeshi politician. He was the President of Bangladesh from 1991 to 1996. Biswas represented Pakistan at the United Nations General Assembly, prior to the independence of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Abdur_Rahman_Biswas$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Tajuddin Ahmad$b$, DATE '1925-07-23', DATE '1975-11-03', $b$Tajuddin Ahmad was a Bangladeshi politician. He led the first government of Bangladesh as its prime minister during the Bangladesh Liberation War in 1971–1972, and is regarded as one of the most instrumental figures in the birth of Bangladesh. He was the 2nd Finance Minister of Bangladesh in 1972–1974.

Source: Wikipedia — https://en.wikipedia.org/wiki/Tajuddin_Ahmad$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Tajuddin%20Ahmad%20in%201970%20%28cropped%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Fazlur Rahman Khan$b$, DATE '1929-04-03', DATE '1982-03-27', $b$Fazlur Rahman Khan was a Bangladeshi-American structural engineer and architect who initiated important structural systems for skyscrapers. Considered the "father of tubular designs" for high-rises, Khan was also a pioneer in computer-aided design (CAD). He was the designer of the Sears Tower, since renamed Willis Tower, the tallest building in the world from 1973 until 1998, and the 100-story John Hancock Center.

Source: Wikipedia — https://en.wikipedia.org/wiki/Fazlur_Rahman_Khan$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Fazlur%20Khan%20%2814396319747%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Avijit Roy$b$, DATE '1972-09-12', DATE '2015-02-26', $b$Avijit Roy was a Bangladeshi-American engineer, online activist, writer, and blogger known for creating and administrating the Mukto-Mona, an Internet blogging community for Bangladeshi freethinkers, rationalists, skeptics, atheists, and humanists. Roy was an advocate of free expression in Bangladesh and coordinated international protests against government censorship and imprisonment of atheist bloggers. He was killed by machete-wielding assailants in Dhaka, Bangladesh, on 26 February 2015; the Islamic militant organization Ansarullah Bangla Team claimed responsibility for the attack.

Source: Wikipedia — https://en.wikipedia.org/wiki/Avijit_Roy$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$A. K. Fazlul Huq$b$, DATE '1873-10-26', DATE '1962-04-27', $b$Abul Kasem Fazlul Huq, popularly known as Sher-e-Bangla, was a Pakistani statesman, lawyer, and politician who served as the first and longest-serving prime minister of Bengal during the British Raj. He presented the Lahore Resolution in 1940, the foundational document of the Pakistan Movement, for which he is regarded as one of the Founding Fathers of Pakistan.

Source: Wikipedia — https://en.wikipedia.org/wiki/A._K._Fazlul_Huq$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/A%20k%20fazlul%20hoque.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Nurul Amin$b$, DATE '1893-07-15', DATE '1974-10-02', $b$Nurul Amin was a Pakistani politician and jurist who served as the eighth prime minister of Pakistan from 7 December to 20 December 1971. His premiership term of only 13 days was the shortest served in Pakistani history.

Source: Wikipedia — https://en.wikipedia.org/wiki/Nurul_Amin$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Nurul%20amin.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Khondaker Mostaq Ahmad$b$, NULL, DATE '1996-03-05', $b$Khondaker Mostaq Ahmad was a Bangladeshi politician. He was the Minister of Commerce in the third Mujib Rahman ministry under President-Prime Minister Sheikh Mujibur Rahman, and assumed the presidency of Bangladesh after the President-Prime Minister's assassination on 15 August 1975. He praised the assassins as "sons of the sun" and put cabinet ministers loyal to Sheikh Mujibur Rahman in jail. On 3 November, he himself was deposed in another coup.

Source: Wikipedia — https://en.wikipedia.org/wiki/Khondaker_Mostaq_Ahmad$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/%E0%A6%96%E0%A6%A8%E0%A7%8D%E0%A6%A6%E0%A6%95%E0%A6%BE%E0%A6%B0%20%E0%A6%AE%E0%A7%8B%E0%A6%B6%E0%A6%A4%E0%A6%BE%E0%A6%95%20%E0%A6%86%E0%A6%B9%E0%A6%AE%E0%A7%87%E0%A6%A6%20%28cropped%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Sufia Kamal$b$, DATE '1911-06-20', DATE '1999-11-20', $b$Begum Sufia Kamal was a Bangladeshi poet, feminist leader, and political activist. She took part in the Bengali nationalist movement of the 1950s and civil society leader in independent Bangladesh. She led feminist activism and was a president of Bangladesh Mahila Parishad. She died in 1999 and was the first woman to be given a state funeral in Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Sufia_Kamal$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Kamaluddin%20Ahmed%20Sufia%20Kamal.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Zainul Abedin$b$, DATE '1914-12-29', DATE '1976-05-28', $b$Zainul Abedin, also known as Shilpacharya was a Bangladeshi painter. He became well known in 1944 through his series of paintings depicting some of the great famines in Bengal during its British colonial period. After the Partition of Indian subcontinent he moved to East Pakistan. In 1948, he helped to establish the Institute of Arts and Crafts at the University of Dhaka. The Indian Express has described him as a legendary Bangladeshi painter and activist. Like many of his contemporaries, his paintings on the Bengal famine of 1943 are viewed as his most characteristic works.

Source: Wikipedia — https://en.wikipedia.org/wiki/Zainul_Abedin$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Zainul%20Abedin.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Syed Nazrul Islam$b$, NULL, DATE '1975-11-03', $b$Syed Nazrul Islam was a Bangladeshi politician and a senior leader of the Awami League. During the Bangladesh War of Independence, he was declared as the Acting President of Bangladesh by the Provisional Government.

Source: Wikipedia — https://en.wikipedia.org/wiki/Syed_Nazrul_Islam$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Sayed%20nazrul%20islam.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Abdus Sattar$b$, DATE '1906-03-01', DATE '1985-10-05', $b$Abdus Sattar was a Bangladeshi statesman. A leader of the Bangladesh Nationalist Party (BNP), he served as the president of Bangladesh from 1981 to 1982, and earlier as the vice president. A jurist by profession, Abdus Sattar held numerous constitutional and political offices in British India, East Pakistan and Bangladesh. He was a cabinet minister, Supreme Court judge, and chief election commissioner of Pakistan. He took oath and became president shortly after the assassination of President Ziaur Rahman.

Source: Wikipedia — https://en.wikipedia.org/wiki/Abdus_Sattar_(president)$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/President%20Sattar%201981%20%28cropped%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Humayun Ahmed$b$, DATE '1948-11-13', DATE '2012-07-19', $b$Humayun Ahmed was a Bangladeshi novelist, dramatist, screenwriter, filmmaker, songwriter, scholar, and academic. His breakthrough was his debut novel Nondito Noroke published in 1972. He wrote over 200 fiction and non-fiction books. He was one of the most popular authors and filmmakers in post-independence Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Humayun_Ahmed$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Humayun%20Ahmed%2013Nov2010.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Abu Sadat Mohammad Sayem$b$, DATE '1916-03-26', DATE '1997-07-08', $b$Mirza Abu Sadat Mohammad Sayem was a Bangladeshi jurist and statesman. He was the chief justice of Bangladesh from 1972 to 1975. He became the president of Bangladesh in the aftermath of counter-coups in November 1975. He held the post of Chief Martial Law Administrator (CMLA). Sayem presided over a cabinet headed by the three chiefs of the armed forces. The cabinet included civilian technocrats and politicians. Sayem resigned on grounds of ill health in April 1977 and was replaced by Ziaur Rahman.

Source: Wikipedia — https://en.wikipedia.org/wiki/Abu_Sadat_Mohammad_Sayem$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Jibanananda Das$b$, DATE '1899-02-17', DATE '1954-10-22', $b$Jibanananda Das was a Bengali poet, writer, and educationist widely regarded as one of the major figures of twentieth-century Bengali modernist poetry. Often called Rupashi Banglar Kabi, he received limited recognition during his lifetime but later came to be considered one of the most important and influential figures in Bengali literature after Rabindranath Tagore and Kazi Nazrul Islam.

Source: Wikipedia — https://en.wikipedia.org/wiki/Jibanananda_Das$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Jibanananda%20Das%20%281899%E2%80%931954%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Moudud Ahmed$b$, DATE '1940-05-24', DATE '2021-03-16', $b$Moudud Ahmed was a Bangladeshi lawyer and politician. He was a standing committee member of the Bangladesh Nationalist Party. Ahmed was elected as a Jatiya Sangsad member five times from the Noakhali-1 and Noakhali-5 constituencies.

Source: Wikipedia — https://en.wikipedia.org/wiki/Moudud_Ahmed$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Moudud%20Ahmed%20%2801%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$A. Q. M. Badruddoza Chowdhury$b$, DATE '1932-11-01', DATE '2024-10-05', $b$Abdul Qasim Mohammad Badruddoza Chowdhury was a Bangladeshi politician who served as the president of Bangladesh from 14 November 2001 until his dismissal on 21 June 2002. He was the founding secretary-general of the Bangladesh Nationalist Party (BNP).

Source: Wikipedia — https://en.wikipedia.org/wiki/A._Q._M._Badruddoza_Chowdhury$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/A.%20Q.%20M.%20Badruddoza%20Chowdhury.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Abu Sayeed Chowdhury$b$, NULL, DATE '1987-08-02', $b$Abu Sayeed Chowdhury was a jurist and the second president of Bangladesh. Besides that, he held the positions of the chairman of the United Nations Commission on Human Rights, the vice-chancellor of the University of Dhaka, the Foreign Minister of Bangladesh, and the first Bangladesh High Commissioner to the UK.

Source: Wikipedia — https://en.wikipedia.org/wiki/Abu_Sayeed_Chowdhury$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Abu%20Sayeed%20Chowdhury%20at%20the%20office%20of%20the%20Vice-Chancellor%20of%20Dacca%20University%2C%20November%201970.png?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Mohammad Mohammadullah$b$, DATE '1921-10-21', DATE '1999-11-12', $b$Mohammad Mohammadullah was the third president of the People's Republic of Bangladesh. Mohammadullah became the Acting President on 24 December 1973, was elected president on 24 January 1974, and took oath of office on 27 January 1974. He remained President until 25 January 1975.

Source: Wikipedia — https://en.wikipedia.org/wiki/Mohammad_Mohammadullah$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Muhammad Habibur Rahman$b$, DATE '1930-12-03', DATE '2014-01-11', $b$Muhammad Habibur Rahman was a Bangladeshi jurist and statesman who served as Chief Justice of Bangladesh in 1995. He was chief adviser of the 1996 caretaker government that oversaw the June 1996 Bangladeshi general election. He was a faculty member at the Department of Law, University of Rajshahi and University of Dhaka. Besides being a language activist, an advocate of the Bengali language, he wrote extensively and published eight books on the subject. He played a significant role in implementing Bengali in the Supreme Court of Bangladesh. He wrote Jathashabdo (1974), the first thesaurus in the Bengali language.

Source: Wikipedia — https://en.wikipedia.org/wiki/Muhammad_Habibur_Rahman$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Muhammad%20Habibur%20Rahman%20by%20Sabila%20Enun%202.JPG?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Ahmed Sofa$b$, DATE '1943-06-30', DATE '2001-07-28', $b$Ahmed Sofa was a Bangladeshi writer, thinker, novelist, poet, philosopher and public intellectual. Sofa is considered by many, including National Professor Abdur Razzaq and Salimullah Khan, to be the most important Bengali Muslim writer after Mir Mosharraf Hossain and Kazi Nazrul Islam. A writer by occupation, Sofa wrote 18 non-fiction books, 8 novels, 4 collections of poems, 2 collections of short stories, and several books in other genres.

Source: Wikipedia — https://en.wikipedia.org/wiki/Ahmed_Sofa$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Abdur%20Razzaq%20%26%20Ahmed%20Sofa.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Abdul Hamid Khan Bhashani$b$, DATE '1880-12-12', DATE '1976-11-17', $b$Abdul Hamid Khan Bhashani, also known reverentially as Maulana Bhashani, was a Bangladeshi politician and statesman who was one of the founders of the Awami League. His political tenure spanned the British colonial India, Pakistan, and Bangladesh periods. Bhashani was popularly known by the honorary title Mozlum Jananeta for his lifelong stance advocating for the poor.

Source: Wikipedia — https://en.wikipedia.org/wiki/Abdul_Hamid_Khan_Bhashani$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Maulana%20Bhasani%20in%20Havana%2C%20Cuba.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Mizanur Rahman Chowdhury$b$, DATE '1928-10-19', DATE '2006-02-02', $b$Mizanur Rahman Chowdhury was a Bengali politician, most notable for serving as Prime Minister of Bangladesh from 9 July 1986, to 27 March 1988.

Source: Wikipedia — https://en.wikipedia.org/wiki/Mizanur_Rahman_Chowdhury$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Mizan%20Chowdhury%20%28cropped%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Muhammad Mansur Ali$b$, DATE '1919-01-16', DATE '1975-11-03', $b$Muhammad Mansur Ali was a Bangladeshi politician who was a close confidant of Sheikh Mujibur Rahman, the founding leader of Bangladesh. A senior leader of the Awami League, Mansur also served briefly as the Prime Minister of Bangladesh in 1975 until he was assassinated while incarcerated on 3 November 1975.

Source: Wikipedia — https://en.wikipedia.org/wiki/Muhammad_Mansur_Ali$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Muhammad%20Mansur%20Ali.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Hasna Begum$b$, DATE '1935-02-24', DATE '2020-12-01', $b$Hasna Begum was a Bangladeshi philosopher and feminist, and a professor of philosophy at the University of Dhaka until her retirement in December 2000.

Source: Wikipedia — https://en.wikipedia.org/wiki/Hasna_Begum$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Hasna%20Begum%202.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Novera Ahmed$b$, DATE '1939-03-29', DATE '2015-05-05', $b$Novera Ahmed was a Bangladeshi modern sculptor. She was awarded the Ekushey Padak medal by the government of Bangladesh in 1997 and Independence Award in 2025. Artist Zainul Abedin described her work saying "What Novera is doing now will take us a long time to understand – she is that kind of an artist."

Source: Wikipedia — https://en.wikipedia.org/wiki/Novera_Ahmed$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Humayun Azad$b$, DATE '1947-04-28', DATE '2004-08-12', $b$Humayun Azad was a Bangladeshi poet, novelist, short-story writer, essayist, linguist, columnist and professor of Dhaka University. He wrote more than 70 titles. He was awarded the Bangla Academy Literary Award in 1986 for his contributions to Bengali linguistics. In 2012, the government of Bangladesh honored him with Ekushey Padak posthumously for his contributions to Bengali literature.

Source: Wikipedia — https://en.wikipedia.org/wiki/Humayun_Azad$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Firoza Begum$b$, DATE '1930-07-28', DATE '2014-09-09', $b$Firoza Begum was a Bangladeshi Bengali Nazrul Geeti singer. She was awarded the Independence Day Award in 1979 by the government of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Firoza_Begum_(singer)$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Young%20Firoza%20Begum%201955.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$M. A. G. Osmani$b$, DATE '1918-09-01', DATE '1984-02-16', $b$Muhammad Ataul Gani Osmani was a Bangladeshi military officer, revolutionary and politician. His military career spanned three decades, beginning with his service in the British Indian Army in 1939. He fought in the Burma Campaign during World War II, and after the partition of India in 1947, he joined the Pakistan Army and served in the East Bengal Regiment, retiring as a colonel in 1967. Osmani joined the Provisional Government of Bangladesh in 1971 as the commander-in-chief of the nascent Bangladesh Forces. Regarded as the founder of the Bangladesh Armed Forces, Osmani retired as a four star general from the Bangladesh Army in 1972.

Source: Wikipedia — https://en.wikipedia.org/wiki/M._A._G._Osmani$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/M%20A%20G%20Osmani.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Zahir Raihan$b$, DATE '1935-08-19', DATE '1972-01-30', $b$Mohammad Zahirullah, known as Zahir Raihan, was a Bangladeshi novelist, writer and filmmaker. He is most notable for his documentary Stop Genocide (1971), made during the Bangladesh Liberation War. He was posthumously awarded Ekushey Padak in 1977 and Independence Day Award in 1992 by the government of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Zahir_Raihan$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Zahir%20Raihan%20%281935%E2%80%931972%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Farida Parveen$b$, DATE '1954-12-31', DATE '2025-09-13', $b$Farida Parveen was a Bangladeshi folk singer. Referred to as "the Queen of Lalon song," she received Ekushey Padak in 1987 and Bangladesh National Film Award for Best Female Playback Singer for the film Andho Prem (1993).

Source: Wikipedia — https://en.wikipedia.org/wiki/Farida_Parveen$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Farida%20Parveen.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Fazle Hasan Abed$b$, DATE '1936-04-27', DATE '2019-12-20', $b$Sir Fazle Hasan Abed was the founder of BRAC, one of the world's largest non-governmental organizations.

Source: Wikipedia — https://en.wikipedia.org/wiki/Fazle_Hasan_Abed$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Fazle%20Hasan%20Abed%20at%20Bangabhaban%202019-08-20%20%28PID-0037351%29%20%28cropped%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Shamsur Rahman$b$, DATE '1929-10-24', DATE '2006-08-17', $b$Shamsur Rahman was a Bangladeshi poet, columnist and journalist. A prolific writer, Rahman produced more than sixty books of poetry collection and is considered a key figure in Bengali literature from the latter half of the 20th century. He was regarded as the unofficial poet laureate of Bangladesh. Major themes in his poetry and writings include liberal humanism, human relations, romanticised rebellion of youth, the emergence of and consequent events in Bangladesh, and opposition to religious fundamentalism.

Source: Wikipedia — https://en.wikipedia.org/wiki/Shamsur_Rahman_(poet)$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Shamsur%20Rahman%20Pohela%20Falgun%201412%20%28cropped%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Ataur Rahman Khan$b$, DATE '1905-03-06', DATE '1991-12-07', $b$Ataur Rahman Khan was a Bangladeshi lawyer, politician and writer, who served as the chief minister of East Pakistan from 1 September 1956 to 13 April 1958, and as the prime minister of Bangladesh from 30 March 1984 to 1 January 1985.

Source: Wikipedia — https://en.wikipedia.org/wiki/Ataur_Rahman_Khan$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Ataur%20Rahman%20Khan.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Aly Zaker$b$, DATE '1944-11-06', DATE '2020-11-27', $b$Aly Zaker was a Bangladeshi actor, businessman, director and writer. He was the owner of Asiatic Marketing Communications Limited.

Source: Wikipedia — https://en.wikipedia.org/wiki/Aly_Zaker$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Aly-Zaker.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Munier Choudhury$b$, DATE '1925-11-27', DATE '1971-12-14', $b$Abu Naeem Mohammad Munier Choudhury was a Bangladeshi educationist, linguist, playwright, literary critic and political dissident. He was a victim of the mass killing of Bangladeshi intellectuals in 1971.

Source: Wikipedia — https://en.wikipedia.org/wiki/Munier_Choudhury$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Munier%20Choudhury%201957.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Jahanara Imam$b$, DATE '1929-05-03', DATE '1994-06-26', $b$Jahanara Imam was a Bangladeshi writer and political activist. She is known for her efforts to bring war criminals to trial for war crimes during the Bangladesh Liberation War. She has been called "Shaheed Janani".

Source: Wikipedia — https://en.wikipedia.org/wiki/Jahanara_Imam$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Jahanara%20Imam%201993.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Kazi Zafar Ahmed$b$, DATE '1939-07-01', DATE '2015-08-27', $b$Kazi Zafar Ahmad was a Bangladeshi politician of the Jatiya Party, who was Prime Minister of Bangladesh from 1989 to 1990.

Source: Wikipedia — https://en.wikipedia.org/wiki/Kazi_Zafar_Ahmed$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Kazi%20Zafar%20Ahmed.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Syed Mujtaba Ali$b$, DATE '1904-09-13', DATE '1974-02-11', $b$Syed Mujtaba Ali was a Bengali writer, journalist, travel enthusiast, academic, scholar and linguist. He lived in Bangladesh, India, Germany, Afghanistan and Egypt.

Source: Wikipedia — https://en.wikipedia.org/wiki/Syed_Mujtaba_Ali$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Syed%20Mujtaba%20Ali.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Humayun Rashid Choudhury$b$, DATE '1928-11-11', DATE '2001-07-10', $b$Humayun Rasheed Choudhury was a Bangladeshi career diplomat and speaker of the Bangladesh Parliament from 1996 to 2001. He was elected president of the 41st session of the UN General Assembly in 1986. He was also Foreign Minister of Bangladesh and Chair of the Parliamentary Standing Committee on Foreign Relations. He was awarded the Independence Day Award posthumously in 2018 by the government of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Humayun_Rashid_Choudhury$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Humayun%20Rashid%20Choudhury.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Anisuzzaman$b$, DATE '1937-02-18', DATE '2020-05-14', $b$Abu Tayyab Muhammad Anisuzzaman was a Bangladeshi academic of Bengali literature. He was an activist who took part in the Language Movement (1952), participated in the Mass Uprising (1969), and took part in the Bangladesh Liberation War (1971).

Source: Wikipedia — https://en.wikipedia.org/wiki/Anisuzzaman$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/%E0%A6%86%E0%A6%A8%E0%A6%BF%E0%A6%B8%E0%A7%81%E0%A6%9C%E0%A7%8D%E0%A6%9C%E0%A6%BE%E0%A6%AE%E0%A6%BE%E0%A6%A8%20%E0%A7%A8%E0%A7%A6%E0%A7%A7%E0%A7%A6.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Sahara Khatun$b$, DATE '1943-03-01', DATE '2020-07-10', $b$Sahara Khatun was a Bangladesh Awami League politician and a cabinet minister. She was the Jatiyo Sangsad member representing the Dhaka-18 constituency, and was the presidium member of the party.

Source: Wikipedia — https://en.wikipedia.org/wiki/Sahara_Khatun$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Ms.%20Sahara%20Khatun%20in%20New%20Delhi%20on%2024%20February%202012.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Abu Taher$b$, DATE '1938-11-14', DATE '1976-07-21', $b$Mohammad Abu Taher (Bengali: মোহাম্মদ আবু তাহের ; 14 November 1938 – 21 July 1976) was a Bangladeshi military officer. He first served in the Pakistan Army before defecting to the Bangladesh Army during the Bangladesh Liberation War. He later crossed into India and reported to the Indian authorities. After a week of screening at Dehradun, he was sent to Kolkata, West Bengal. He was ordered to report to Sector 11 of Mukti Bahini under the command of Major Ziaur Rahman. He became the sector commander after Major Ziaur Rahman and served in the Bangladesh Defence Forces (BDF) for about two months, until November 1971. He was awarded the Bir Uttom Medal for gallantry in the War of Liberation.

Source: Wikipedia — https://en.wikipedia.org/wiki/Abu_Taher$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Abu%20Taher.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Perween Rahman$b$, DATE '1957-01-22', DATE '2013-03-13', $b$Perween Rahman was a Pakistani social activist, director of the Orangi Pilot Project Research and Training Institute. She was murdered on 13 March 2013.

Source: Wikipedia — https://en.wikipedia.org/wiki/Perween_Rahman$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Dhirendranath Datta$b$, DATE '1886-11-02', DATE '1971-03-21', $b$Dhirendranath Datta was a Bengali lawyer and politician from East Bengal who was a member of the 1st Constituent Assembly of Pakistan. He is best known for proposing Bengali for the national language of Pakistan in the Assembly. He was also active in the politics of undivided Bengal in pre-partition India.

Source: Wikipedia — https://en.wikipedia.org/wiki/Dhirendranath_Datta$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Sheikh Fazilatunnesa Mujib$b$, DATE '1930-08-08', DATE '1975-08-15', $b$Begum Sheikh Fazilatunnesa Mujib, commonly known as Begum Mujib and also known by her nickname Renu was the wife of Sheikh Mujibur Rahman, the founding president of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Sheikh_Fazilatunnesa_Mujib$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Sheikh%20Mujib%20and%20Begum%20Mujib%20circa%201955%20%28cropped%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Xulhaz Mannan$b$, DATE '1976-10-13', DATE '2016-04-25', $b$Xulhaz Mannan was an LGBTQ+ rights activist, USAID employee, and the founder of Bangladesh's first and only LGBTQ-themed magazine Roopbaan. He was murdered, along with his friend and fellow-activist Mahbub Rabbi Tonoy, in a 2016 machete attack by Ansar al-Islam, the Bangladeshi branch of Al-Qaeda.

Source: Wikipedia — https://en.wikipedia.org/wiki/Xulhaz_Mannan$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Syeda Sajeda Chowdhury$b$, DATE '1935-05-08', DATE '2022-09-11', $b$Syeda Sajeda Chowdhury was a Bangladeshi politician who served as the Deputy Leader of the Jatiya Sangsad from 2009 to 2022. She served as a Jatiya Sangsad member representing the Faridpur-2 constituency from 2008 till her death in 2022. She also served as the Environment and Forest Minister of Bangladesh during 1996–2001. She was also the first and only female general secretary of the Bangladesh Awami League, serving from 1986 to 1992.

Source: Wikipedia — https://en.wikipedia.org/wiki/Syeda_Sajeda_Chowdhury$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Syeda%20Sajeda%20Chowdhury%20-%20Sheikh%20Hasina%20National%20Parliament%20Prime%20Ministers%20Question%20Hour%202015-09-09%20%28PID-0058150%29%20%28cropped%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Manna$b$, DATE '1964-04-14', DATE '2008-02-17', $b$Syed Mohammad Aslam Talukder, known by his stage name Manna (মান্না), was a Bangladeshi film actor and producer. His first released film was Pagli (1986). He got his debut as a lead role in the film Kashem Malar Prem (1991), directed by Mustafa Anwar.

Source: Wikipedia — https://en.wikipedia.org/wiki/Manna_(actor)$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/SM%20Aslam%20Talukder%20Manna.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Andrew Kishore$b$, NULL, DATE '2020-07-06', $b$Andrew Kishore Kumar Baroi, widely known as Andrew Kishore, was a Bangladeshi playback singer. Often referred to as the "Playback King" of Bangladesh for his extensive contributions to the classic era of Dhalywood cinema, he was the lead playback singer for more than 100 films and recorded over 15,000 songs.

Source: Wikipedia — https://en.wikipedia.org/wiki/Andrew_Kishore$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Andrew%20Kishore.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Kabori$b$, DATE '1950-07-09', DATE '2021-04-17', $b$Sarah Begum Kabori was a Bangladeshi film actress and politician. Her notable films include Sutorang, Sareng Bou, Abhirbhab, Shat Bhai Champa, Sujon Sokhi, and Lalon Fokir. She received the Bangladesh National Film Award for Best Actress for her role in the film Sareng Bou (1978) and a Lifetime Achievement Award in 2013.

Source: Wikipedia — https://en.wikipedia.org/wiki/Kabori$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Sarah%20Begum%20Kabori%20Receives%20Lifetime%20Achievement%20Award%20National%20Film%20Awards%20Dhaka%202015-04-04%20%28PID-0060031%29%20%28cropped%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Al Mahmud$b$, DATE '1936-07-11', DATE '2019-02-15', $b$Mir Abdus Shukur Al Mahmud was a Bangladeshi poet, novelist, and short-story writer. He is considered one of the greatest Bengali poets to have emerged in the 20th century. His work in Bengali poetry is dominated by his frequent use of regional dialects. In the 1950s he was among those Bengali poets who were outspoken in their writing on such subjects as the events of the Bengali language movement, nationalism, political and economical repression, and the struggle against the West Pakistani government.

Source: Wikipedia — https://en.wikipedia.org/wiki/Al_Mahmud$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Al%20Mahmud.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Syed Waliullah$b$, DATE '1922-08-15', DATE '1971-10-10', $b$Syed Waliullah was a Bangladeshi novelist, short-story writer and playwright. He was notable for his debut novel, Lalsalu. He was awarded Bangla Academy Literary Award (1961), Adamjee Prize (1965), Ekushey Padak (1984) and Bangladesh National Film for Best Story (2001).

Source: Wikipedia — https://en.wikipedia.org/wiki/Syed_Waliullah$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Zohurul Hoque$b$, DATE '1926-10-11', DATE '2017-01-18', $b$Zohurul Hoque was an Indian Islamic scholar and doctor known for his translations of the Qur'an into the Bengali, Assamese and English languages. He later moved to Muscat in Oman.

Source: Wikipedia — https://en.wikipedia.org/wiki/Zohurul_Hoque$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/ZH%202507.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Lalon$b$, NULL, DATE '1890-10-17', $b$Lalon, also known as Lalon Shah, Lalon Fakir, Lalon Shai, and Shahji, was a Bengali spiritual leader, philosopher, mystic poet and social reformer. Born in what is now Khulna Division in Bangladesh, Lalon was a disciple of his father Malam Shah and Siraj Shah. He is regarded as an icon of Bengali culture, for inspiring and influencing many poets and social thinkers including Rabindranath Tagore, Kazi Nazrul Islam and Allen Ginsberg. Lalon's philosophy of humanity rejects all distinctions of caste, class, and creed and takes a stand against theological conflicts and racism.

Source: Wikipedia — https://en.wikipedia.org/wiki/Lalon$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Fakir%20Lalon%20Shah.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Allauddin Khan$b$, NULL, DATE '1972-09-06', $b$Ustad Allauddin Khan was an Indian sarod player, multi-instrumentalist, composer and one of the most notable music teachers of the 20th century in Indian classical music.

Source: Wikipedia — https://en.wikipedia.org/wiki/Allauddin_Khan$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Ustad%20Alauddin%20Khan%20Full%201%20%28cropped%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Surya Sen$b$, DATE '1894-03-22', DATE '1934-01-08', $b$Surya Sen, also known as Surya Kumar Sen, was an Indian revolutionary who played a significant role in the Indian independence movement against British colonial rule. He is best known for leading the Chittagong Armoury Raid in 1930.

Source: Wikipedia — https://en.wikipedia.org/wiki/Surya_Sen$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Surya%20Sen%20before%201934.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Pritilata Waddedar$b$, DATE '1911-05-05', DATE '1932-09-23', $b$Pritilata Waddedar was a Bengali revolutionary nationalist from Chittagong who was influential in the Indian independence movement. She is often praised as "Bengal's first woman martyr".

Source: Wikipedia — https://en.wikipedia.org/wiki/Pritilata_Waddedar$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Original%20Archived%20photo%20of%20Pritilata%20Waddedar.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Kalpana Datta$b$, DATE '1913-07-27', DATE '1995-02-08', $b$Kalpana Datta, also known as Kalpana Joshi, was an Indian independence movement activist and a member of the armed independence movement led by Surya Sen, which carried out the Chittagong armoury raid in 1930. Later she joined the Communist Party of India and married Puran Chand Joshi, the general secretary of the party, in 1943.

Source: Wikipedia — https://en.wikipedia.org/wiki/Kalpana_Datta$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Kalpana%20Dutt.png?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Jagadish Chandra Bose$b$, DATE '1858-11-30', DATE '1937-11-23', $b$Sir Jagadish Chandra Bose was a polymath with interests in biology, physics and writing science fiction. He was a pioneer in the investigation of radio microwave optics, made significant contributions to botany, and was a major force behind the expansion of experimental science on the Indian subcontinent. Bose is considered the father of Bengali science fiction. A crater on the Moon was named in his honour. He founded the Bose Institute, a premier research institute in India and also one of its oldest. Established in 1917, the institute was the first interdisciplinary research centre in Asia. He served as the Director of Bose Institute from its inception until his death.

Source: Wikipedia — https://en.wikipedia.org/wiki/Jagadish_Chandra_Bose$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/1920%20Jagadish%20Chandra%20Bose.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Syed Manzoorul Islam$b$, DATE '1951-01-18', DATE '2025-10-10', $b$Syed Manzoorul Islam was a Bangladeshi critic, writer, and a professor at the University of Dhaka. As a literary critic, he wrote criticism on writers including Michael Madhusudan Dutt, Kazi Nazrul Islam, Sudhindranath Dutta, Samar Sen, and Shamsur Rahman. He became the president of PEN Bangladesh in January 2018.

Source: Wikipedia — https://en.wikipedia.org/wiki/Syed_Manzoorul_Islam$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Syed%20Manzoorul%20Islam%20in%20Dhaka%202019.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Quamrul Hassan$b$, DATE '1921-12-02', DATE '1988-02-02', $b$Quamrul Hassan was a Bangladeshi artist. Quamrul Hassan is referred to in Bangladesh as Potua, a word usually associated with folk artists, due to his down to earth style yet very modern in nature as he always added Cubism other than the folk style to his artworks. In addition to his artistic legacy, two of Quamrul Hassan's work have come to be part of Bangladesh's political history. The first of these is a monstrous rendition of Yahya Khan, the Pakistani president who ordered genocide in Bangladesh. The second was just before his death, mocking the then dictator of Bangladesh, Hossain Mohammad Ershad. This sketch was titled Desh aaj bisshobeheyar khoppre.

Source: Wikipedia — https://en.wikipedia.org/wiki/Quamrul_Hassan$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Quamrul%20Hassan.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$SM Sultan$b$, DATE '1923-08-10', DATE '1994-10-10', $b$Sheikh Mohammed Sultan, popularly known as S M Sultan, was a Bengali decolonial artist who worked in painting and drawing. His fame rests on his striking depictions of exaggeratedly muscular Bengali peasants engaged in the activities of their everyday lives. Sultan's early works were influenced by western technics and forms, particularly impressionism, however, in his later works particularly, works exhibited in 1976, we discover there is a constant temptation to decolonize his art technics and forms.

Source: Wikipedia — https://en.wikipedia.org/wiki/SM_Sultan$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Salman Shah$b$, DATE '1971-09-17', DATE '1996-09-06', $b$Chowdhury Muhammad Shahriar Emon, known by his stage name Salman Shah, was a Bangladeshi film and television actor and model. Referred in the media as the "First Superstar of Dhallywood", he is widely regarded as the most influential and iconic figures in Bangladesh's film history. He is also known as a fashion icon.

Source: Wikipedia — https://en.wikipedia.org/wiki/Salman_Shah_(actor)$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Ayub Bachchu$b$, DATE '1962-08-16', DATE '2018-10-18', $b$Ayub Bachchu was a Bangladeshi rock guitarist, composer, singer and songwriter, who was the founder of the Bangladeshi rock band Love Runs Blind and earned success as the lead singer and the lead guitarist of the band. He is considered a rock and pop culture icon in Bangladesh. He was one of the pioneers of Bangladeshi rock and pop music.

Source: Wikipedia — https://en.wikipedia.org/wiki/Ayub_Bachchu$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/LRB%20Ayub%20Bachchu%20%28cropped%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Azam Khan$b$, DATE '1950-02-28', DATE '2011-06-05', $b$Mahbubul Haque Khan, known professionally as Azam Khan, was a Bangladeshi singer-songwriter, record producer, and the lead singer of the pioneering pop-rock band Uchcharon. Widely referred to as the "Pop Samrat" and "The Rock Guru", he is considered a founding figure of Bangladeshi rock and one of the most influential artists in the history of Bangladeshi popular music.

Source: Wikipedia — https://en.wikipedia.org/wiki/Azam_Khan_(singer)$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/%E0%A6%86%E0%A6%9C%E0%A6%AE%20%E0%A6%96%E0%A6%BE%E0%A6%A8%20%28%E0%A6%86%E0%A6%AC%E0%A6%BE%E0%A6%B0%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Tareque Masud$b$, DATE '1956-12-06', DATE '2011-08-13', $b$Tareque Masud was a Bangladeshi independent film director, film producer, screenwriter and lyricist. He first found success with the films Muktir Gaan (1995) and Matir Moina (2002), for which he won three international awards, including the International Critics' FIPRESCI Prize, in the Directors' Fortnight at 2002 Cannes Film Festival. The film became Bangladesh's first film to compete for the Academy Award for Best Foreign Language Film.

Source: Wikipedia — https://en.wikipedia.org/wiki/Tareque_Masud$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Tareque%20Masud%20Syl.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Shawkat Osman$b$, DATE '1917-01-02', DATE '1998-05-14', $b$Sheikh Azizur Rahman, known as Shawkat Osman, was a Bangladeshi novelist and short story writer. He won the Bangla Academy Literary Award in 1962, the Ekushey Padak in 1983 and the Independence Day Award in 1997.

Source: Wikipedia — https://en.wikipedia.org/wiki/Shawkat_Osman$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Kabir Chowdhury$b$, NULL, DATE '2011-12-13', $b$Kabir Chowdhury was a Bangladeshi academic, essayist, materialist, translator, cultural worker and civil society activist. He received Bangla Academy Literary Award (1973), Ekushey Padak (1991) and Independence Day Award (1997). He became a National Professor of Bangladesh in 1998.

Source: Wikipedia — https://en.wikipedia.org/wiki/Kabir_Chowdhury$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Muzharul Islam$b$, DATE '1923-12-25', DATE '2012-07-15', $b$Muzharul Islam was a Bangladeshi architect, urban planner, educator, and activist. He is considered the grand master of regional modernism in South Asia. Islam is the pioneer of modern architecture in Bangladesh and the father of Bengali modernism. Islam's style and influence dominated the architectural scene in the country during the 1960s and 70s, along with major US architects he brought to work in Dhaka.

Source: Wikipedia — https://en.wikipedia.org/wiki/Muzharul_Islam$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Muzharul%20Islam.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Zafrullah Chowdhury$b$, DATE '1941-12-27', DATE '2023-04-11', $b$Zafrullah Chowdhury was a Bangladeshi public health and social activist.

Source: Wikipedia — https://en.wikipedia.org/wiki/Zafrullah_Chowdhury$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Zafrullah%20Chowdhury.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Jasimuddin$b$, DATE '1903-01-01', DATE '1976-03-13', $b$Jasimuddin, popularly called Palli Kabi, was a Bangladeshi poet, lyricist, composer and writer widely celebrated for his modern ballad sagas in the pastoral mode. Although his full name was Jasim Uddin Mollah, he was known as Jasim Uddin. His Nakshi Kanthar Math and Sojan Badiar Ghat are considered among the best lyrical poems in the Bengali language. He is the key figure for the revivals of pastoral literature in Bengal during the 20th century. As a versatile writer, Jasimuddin wrote poems, ballads, songs, dramas, novel, stories, memoirs, travelogues, etc.

Source: Wikipedia — https://en.wikipedia.org/wiki/Jasimuddin$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Jasimuddin%20Lomax%201951%20%282%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Shahidullah Kaiser$b$, DATE '1927-02-16', DATE '1971-12-14', $b$Shahidullah Kaiser was a Bangladeshi novelist and writer. He was awarded Bangla Academy Literary Award in 1969, Ekushey Padak in 1983, and the Independence Day Award in 1998.

Source: Wikipedia — https://en.wikipedia.org/wiki/Shahidullah_Kaiser$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Matiur Rahman$b$, DATE '1941-10-29', DATE '1971-08-20', $b$Flight Lieutenant Matiur Rahman, Bir Sreshtho was a Bengali fighter pilot in the Pakistan Air Force (PAF) from East Pakistan and a recipient of Bir Sreshtho, Bangladesh's highest military award, for his actions during the Bangladesh War of Independence.

Source: Wikipedia — https://en.wikipedia.org/wiki/Matiur_Rahman_(Bir_Sreshtho)$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Bir%20Shreshto%20Flt.%20Lft.%20Matiur%20Rahman-6.png?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Khaled Mosharraf$b$, DATE '1937-11-01', DATE '1975-11-07', $b$Khaled Mosharraf was a major general in the Bangladesh Army, who is known for his role in the Bangladesh Liberation War and the subsequent coups in post-independence Bangladesh. After deposing Khondakar Mustaq Ahmad in the 3 November 1975 coup, Mosharraf was assassinated on 7 November 1975.

Source: Wikipedia — https://en.wikipedia.org/wiki/Khaled_Mosharraf$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Hason Raja$b$, DATE '1854-12-21', DATE '1922-12-06', $b$Dewan Hason Raja Choudhury, or simply known as Hason Raja, was a Bengali mystic poet and songwriter from Sylhet, Bengal Presidency. His unique style of music made him one of the most prominent figures in Bengali folk culture.

Source: Wikipedia — https://en.wikipedia.org/wiki/Hason_Raja$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/%E0%A6%B9%E0%A6%BE%E0%A6%B8%E0%A6%A8%20%E0%A6%B0%E0%A6%BE%E0%A6%9C%E0%A6%BE.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Abdullah-Al-Muti$b$, DATE '1930-01-01', DATE '1998-11-30', $b$Sheikh Abdullah Al Muti Sharafuddin, known as Abdullah Al Muti, was a Bangladeshi educationalist and science writer. He wrote tough scientific ideas in an easy fashion suitable for children and teenagers. He became first Bangladeshi writer to win the UNESCO Kalinga Prize in 1983. He had earned major national awards - Bangla Academy Literary Award in 1975, Ekushey Padak in 1985 and Independence Day Award in 1995. He wrote many science fiction stories like Akash(আকাশ)

Source: Wikipedia — https://en.wikipedia.org/wiki/Abdullah-Al-Muti$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Abdullah-Al-Muti.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Rawshan Ara Bachchu$b$, DATE '1932-12-17', DATE '2019-12-03', $b$Rawshan Ara Bachchu was a Bangladeshi activist. She took part in Bengali language movement in 1952. She was awarded Anannya Top Ten Awards in 2009.

Source: Wikipedia — https://en.wikipedia.org/wiki/Rawshan_Ara_Bachchu$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Rowshan%20Ara%20Bachchu%2002.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Ahmed Sharif$b$, DATE '1921-02-13', DATE '1999-02-24', $b$Ahmed Sharif was an educationist, philosopher, critic, writer and scholar of medieval Bengali literature. He is recognized as one of the most outspoken atheists and radical thinkers of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Ahmed_Sharif$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Ahmed%20Sharif.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Rizia Rahman$b$, DATE '1939-12-28', DATE '2019-08-16', $b$Rizia Rahman was a Bangladeshi novelist. She had a number of novels and short stories to her credit. Her works cut across all genres. She was best known for the novel Bong Theke Bangla. She was the recipient of Bangla Academy Literary Award (1978). As of 2018, she had published more than 50 novels and short story collections during her long career.

Source: Wikipedia — https://en.wikipedia.org/wiki/Rizia_Rahman$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$A. T. M. Shamsuzzaman$b$, DATE '1941-09-10', DATE '2021-02-20', $b$Abu Taher Mohammad Shamsuzzaman was a Bangladeshi film and television actor, director, and screenwriter. He was awarded the Ekushey Padak in 2015 by the government of Bangladesh. He won Bangladesh National Film Awards five times for his roles in Dayee Ke? (1987), Madam Fuli (1999), Churiwala (2001), Mon Bosena Porar Table E (2009), and Chorabali (2012).

Source: Wikipedia — https://en.wikipedia.org/wiki/A._T._M._Shamsuzzaman$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Anwar Hossain$b$, DATE '1948-10-06', DATE '2018-12-01', $b$Anwar Hossain was a Bangladeshi photographer and cinematographer. He won Bangladesh National Film Award for Best Cinematography a record five times for the films Sundori (1979), Emiler Goenda Bahini (1980), Puraskar (1983), Anya Jibon (1995) and Lalsalu (2003).

Source: Wikipedia — https://en.wikipedia.org/wiki/Anwar_Hossain_(photographer)$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Anwar%20Hossain.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Murtaja Baseer$b$, DATE '1932-08-17', DATE '2020-08-15', $b$Murtaja Baseer was a Bangladeshi painter and artist known for his abstract realism themed works. He was also a poet, author, researcher, numismatist, and filmmaker. Baseer was awarded the Ekushey Padak, Bangladesh's second highest civilian honor, in 1980, and the Independence Award, Bangladesh's highest state award, in 2019.

Source: Wikipedia — https://en.wikipedia.org/wiki/Murtaja_Baseer$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Mortaza%20Bashir.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Kamal Lohani$b$, DATE '1934-06-26', DATE '2020-06-20', $b$Kamal Lohani was a Bangladeshi journalist. He was awarded Ekushey Padak in 2015 by the Government of Bangladesh. He served as the director general of Shilpakala Academy from April 2009 until April 2011.

Source: Wikipedia — https://en.wikipedia.org/wiki/Kamal_Lohani$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Kamal%20Lohani.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Abdul Karim Sahitya Bisharad$b$, DATE '1871-10-11', DATE '1953-09-30', $b$Munshi Abdul Karim, known as Abdul Karim Sahitya Bisharad, was a Bengali littérateur, historian of Bangla literature and collector and interpreter of old Bangla manuscripts.

Source: Wikipedia — https://en.wikipedia.org/wiki/Abdul_Karim_Sahitya_Bisharad$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Abdul%20Karim%20Sahitya%20Bisharad%20real.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Abul Maal Abdul Muhith$b$, DATE '1934-10-06', DATE '2022-04-30', $b$Abul Maal Abdul Muhith was a Bangladeshi economist, writer, civil servant, secretary, diplomat and politician. He served as the finance minister of the government of Bangladesh from January 2009 until January 2019.

Source: Wikipedia — https://en.wikipedia.org/wiki/Abul_Maal_Abdul_Muhith$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Finance%20Minister%20of%20Bangladesh%20Abul%20Maal%20Abdul%20Muhith.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Akhteruzzaman Elias$b$, DATE '1943-02-16', DATE '1997-01-04', $b$Akhteruzzaman Elias was a Bangladeshi novelist and short story writer. He has been regarded as one of the most prominent writers of Bangladesh. During his lifetime, he published two novels and several short stories. He died from cancer in 1997. Elias won many awards during his lifetime and posthumously.

Source: Wikipedia — https://en.wikipedia.org/wiki/Akhteruzzaman_Elias$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Noor Hossain$b$, NULL, DATE '1987-11-10', $b$Noor Hossain was a Bangladeshi activist who was killed by the police on 10 November 1987, while protesting against Ershad administration near Zero Point, Dhaka. Zero Point was later renamed as Noor Hossain Square and the anniversary of his death is officially commemorated each year as the Noor Hossain Day.

Source: Wikipedia — https://en.wikipedia.org/wiki/Noor_Hossain$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Noor%20Hossain%20at%2010%20November%201987%20protest%20for%20democracy%20in%20Dhaka%20%2803%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Rudra Mohammad Shahidullah$b$, DATE '1956-10-16', DATE '1991-06-21', $b$Rudra Mohammad Shahidullah was a Bangladeshi poet noted for his revolutionary and romantic poetry. He is considered one of the leading Bengali poets of the 1970s. He received Munir Chaudhury Memorial Award in 1980 and Ekushey Padak in 2024

Source: Wikipedia — https://en.wikipedia.org/wiki/Rudra_Mohammad_Shahidullah$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Rudra%20Muhammad%20Shahidullah.JPG?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Helal Hafiz$b$, DATE '1948-10-07', DATE '2024-12-13', $b$Helal Hafiz was a Bangladeshi poet. He is considered a true representative of poets of his generation, having certain creative traits in an age when his nation and countries in the neighbourhood witnessed dramatic transitions, particularly in the arena of politics. He won the Bangla Academy Literary Award (2013). Hafiz died in Dhaka on 13 December 2024, at the age of 76.

Source: Wikipedia — https://en.wikipedia.org/wiki/Helal_Hafiz$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Helal%20Hafiz%20at%20Dhaka%20Lit%20Fest%202017%2001%20%28cropped%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Zakaria Pintoo$b$, DATE '1943-01-01', DATE '2024-11-18', $b$Zakaria Pintoo, alternatively spelled Zakaria Pintu, was a Bangladeshi footballer who played as a defender. He was the first captain of the Bangladesh national team.

Source: Wikipedia — https://en.wikipedia.org/wiki/Zakaria_Pintoo$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Zakaria%20Pintoo%20pictured%20in%201969.png?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Abdul Gaffar Chowdhury$b$, DATE '1934-12-12', DATE '2022-05-19', $b$Abdul Gaffar Chowdhury was a Bangladeshi-born British writer, journalist, columnist, political analyst and poet. He wrote the lyrics to "Amar Bhaier Rokte Rangano", a widely celebrated song commemorating the Bengali language movement. He was awarded the Bangla Academy Literary Award in 1967, the Ekushey Padak in 1983, and the Independence Day Award in 2009.

Source: Wikipedia — https://en.wikipedia.org/wiki/Abdul_Gaffar_Chowdhury$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Mir Mugdho$b$, DATE '1998-10-09', DATE '2024-07-18', $b$Mir Mahfuzur Rahman Mugdho was a Bangladeshi student activist and freelancer in the 2024 quota reform movement, who was shot dead while distributing food, water and biscuits during the protest. His death is widely recognised as a pivotal point in the July Uprising.

Source: Wikipedia — https://en.wikipedia.org/wiki/Mir_Mugdho$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Shamsuzzaman Khan$b$, DATE '1940-12-29', DATE '2021-04-14', $b$Shamsuzzaman Khan was a Bangladeshi academician, folklorist, and writer who served as president of the Bangla Academy from June 2020 until his death in April 2021. He also served as the director general of the academy during 2009–2018. He was notable for editing book series on folk culture of 64 different districts in 64 volumes and collections of folklore series in 114 volumes. He was awarded Bangla Academy Literary Award in 2001, Ekushey Padak in 2009 and Independence Day Award in 2017 by the government of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Shamsuzzaman_Khan$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Shamsuzzaman%20Khan%20Dhaka%202019%20%283%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Khan Ataur Rahman$b$, DATE '1928-12-11', DATE '1997-12-01', $b$Khan Ataur Rahman was a Bangladeshi film actor, director, producer, screenplay writer, composer, and singer, best known for his role in the film Jibon Theke Neya (1970). He received the Bangladesh National Film Award for Best Screenplay for the films Sujon Sokhi (1975) and Danpite Chhele (1980). He was awarded Ekushey Padak posthumously in 2003 by the Government of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Khan_Ataur_Rahman$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Rawshan Ara$b$, DATE '1940-08-03', DATE '2010-06-24', $b$Rawshan Ara, was a Bangladeshi film actress. Before joining film, She was employed in the doctor's profession. Poet Bande Ali Mia was her brother-in-law and Renowned film actress Suchitra Sen was her friend who also classmates of her school life. In 1959, she made her film debut in the movie Matir Pahar.

Source: Wikipedia — https://en.wikipedia.org/wiki/Rawshan_Ara$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Sayeeda Khanam$b$, DATE '1937-12-29', DATE '2020-08-18', $b$Sayeeda Khanam was the first female professional photographer of Bangladesh. She covered many important events of Liberation War of Bangladesh in 1971 through her photography.

Source: Wikipedia — https://en.wikipedia.org/wiki/Sayeeda_Khanam$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Saida%20Khanom%20%28cropped%29.JPG?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Fakir Alamgir$b$, DATE '1950-02-25', DATE '2021-07-23', $b$Fakir Alamgir was a Bangladeshi folk and pop singer. He was awarded Ekushey Padak in 1999 by the Government of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Fakir_Alamgir$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Fakir%20Alamgir%20%283%29.JPG?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Rahat Khan$b$, DATE '1940-12-19', DATE '2020-08-28', $b$Rahat Khan was a Bangladeshi journalist and litterateur. He wrote more than 32 novels. He won Bangla Academy Literary Award in 1973 and Ekushey Padak in 1996 by the Government of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Rahat_Khan$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Rashid Haider$b$, DATE '1941-07-15', DATE '2020-10-13', $b$Rashid Haider was a Bangladeshi author and novelist. He was awarded Ekushey Padak in 2014 and Bangla Academy Literary Award in 1984 by the government of Bangladesh. He was the author of more than 70 books.

Source: Wikipedia — https://en.wikipedia.org/wiki/Rashid_Haider$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Rashid%20Haider.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Saadat Husain$b$, DATE '1946-11-24', DATE '2020-04-22', $b$Sadat Hussain was a Bangladeshi bureaucrat and the 9th chairman of the Bangladesh Public Service Commission, one of the country's leading constitutional bodies. He also served as the chief of the Bangladesh Civil Service and as the cabinet secretary to the government of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Saadat_Husain$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Dr.SadaatHussain2011-3.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Syed Abul Maksud$b$, DATE '1946-10-23', DATE '2021-02-23', $b$Syed Abul Maksud was a Bangladeshi journalist, columnist, research scholar, essayist, and writer. He was acclaimed for his critical and research work. He was a regular contributor to the Daily Prothom Alo. The Bangla Dictionary of Writers stats that his essays on literature, society, culture and politics are much appreciated for his clear view, lucid language and simple style. He carried out substantive research works on "the lives of famous litterateurs such as Rabindranath Tagore, Buddhadeva Bose", Mohandas Karamchand Gandhi, Syed Waliullah etc. His Journal of Germany is a popular travel book.

Source: Wikipedia — https://en.wikipedia.org/wiki/Syed_Abul_Maksud$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Syed%20Abul%20Maksud%202019002.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Badruddin Umar$b$, DATE '1931-12-20', DATE '2025-09-07', $b$Badruddin Umar was a Bangladeshi Marxist–Leninist theorist, political activist, historian, writer, intellectual, and leader of the Communist Party of Bangladesh (Marxist–Leninist) (Umar). His father, Abul Hashim, was a prominent politician in the Indian subcontinent.

Source: Wikipedia — https://en.wikipedia.org/wiki/Badruddin_Umar$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/%E0%A6%AC%E0%A6%A6%E0%A6%B0%E0%A7%81%E0%A6%A6%E0%A7%8D%E0%A6%A6%E0%A7%80%E0%A6%A8%20%E0%A6%AE%E0%A7%8B%E0%A6%B9%E0%A6%BE%E0%A6%AE%E0%A7%8D%E0%A6%AE%E0%A6%A6%20%E0%A6%89%E0%A6%AE%E0%A6%B0.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Sanjida Khatun$b$, DATE '1933-04-04', DATE '2025-03-25', $b$Sanjida Khatun was a Bangladeshi musicologist. She was awarded Bangla Academy Literary Award in 1998 and Ekushey Padak in 1991 by the government of Bangladesh and Padma Shri, India's fourth highest civilian award, in 2021.

Source: Wikipedia — https://en.wikipedia.org/wiki/Sanjida_Khatun$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Abubakar Siddique$b$, DATE '1934-08-19', DATE '2023-12-28', $b$Abubakar Siddique was a Bangladeshi poet, novelist, short-story writer and critic. He published more than 20 poetry books, 4 novels, 15 storybooks, and one rhyme book. He won Bangla Academy Literary Award in 1988.

Source: Wikipedia — https://en.wikipedia.org/wiki/Abubakar_Siddique$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/%E0%A6%86%E0%A6%AC%E0%A7%81%E0%A6%AC%E0%A6%95%E0%A6%B0%20%E0%A6%B8%E0%A6%BF%E0%A6%A6%E0%A7%8D%E0%A6%A6%E0%A6%BF%E0%A6%95.png?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Jamal Nazrul Islam$b$, DATE '1939-01-24', DATE '2013-03-16', $b$Jamal Nazrul Islam FRAS was a Bangladeshi mathematical physicist and cosmologist. He was a professor at University of Chittagong, served as a member of the advisory board at Shahjalal University of Science and Technology and member of the syndicate at Chittagong University of Engineering & Technology until his death. He also served as the director of the Research Center for Mathematical and Physical Sciences (RCMPS) at the University of Chittagong. He was posthumously awarded Independence Award, the highest civilian honour of the country, in 2025.

Source: Wikipedia — https://en.wikipedia.org/wiki/Jamal_Nazrul_Islam$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Jamal%20Nazrul%20Islam.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Saleemul Huq$b$, DATE '1952-10-02', DATE '2023-10-28', $b$Saleemul Huq was a Bangladeshi-British scientist and had been the Director of the International Centre for Climate Change & Development (ICCCAD) based in Bangladesh, also Professor at Independent University, Bangladesh (IUB). He was elected one of Nature's 10 top scientists in 2022.

Source: Wikipedia — https://en.wikipedia.org/wiki/Saleemul_Huq$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Saleemul%20Huq%20%282%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Hamidur Rahman$b$, NULL, DATE '1988-11-19', $b$Hamidur Rahman was a Bangladeshi artist and sculptor. He is best known as the architect of the Shaheed Minar, a national monument in Dhaka, Bangladesh, established to commemorate the martyrs of the Language Movement of 1952.

Source: Wikipedia — https://en.wikipedia.org/wiki/Hamidur_Rahman_(artist)$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Front%20Cover%20-%20Flyer%20from%20the%20exposition%20%22Paintings%20%26%20Drawings%20by%20Hamidur%20Rahman%22.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Abul Kashem$b$, DATE '1920-06-28', DATE '1991-03-11', $b$Mohammad Abul Kashem is generally considered as a pioneer and the architect of the historic Language Movement of Bangladesh. He was also a politician, author and an eminent educationist. He founded the Islamic-oriented Bengali cultural organisation Tamaddun Majlish.

Source: Wikipedia — https://en.wikipedia.org/wiki/Abul_Kashem$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Principal%20Abul%20Kashem%20003.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Golam Mostofa$b$, NULL, DATE '1964-10-13', $b$Golam Mostofa was a Pakistani Bengali writer and poet.

Source: Wikipedia — https://en.wikipedia.org/wiki/Golam_Mostofa_(poet)$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/%E0%A6%97%E0%A7%8B%E0%A6%B2%E0%A6%BE%E0%A6%AE%20%E0%A6%AE%E0%A7%8B%E0%A6%B8%E0%A7%8D%E0%A6%A4%E0%A6%AB%E0%A6%BE%20%28%E0%A6%AC%E0%A6%BE%E0%A6%99%E0%A6%BE%E0%A6%B2%E0%A6%BF%20%E0%A6%95%E0%A6%AC%E0%A6%BF%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Nilima Ibrahim$b$, DATE '1921-10-11', DATE '2002-06-18', $b$Neelima Ibrahim was a Bangladeshi educationist, littérateur and social worker. She is well known for her scholarship on Bengali literature but even more so for her depiction of raped and tortured women in the 1971 Bangladesh Liberation War in her book Ami Birangana Bolchi. She was awarded Bangla Academy Literary Award in 1969, Begum Rokeya Padak in 1996 and Ekushey Padak in 2000 by the Government of Bangladesh for her contributions to Bangla literature.

Source: Wikipedia — https://en.wikipedia.org/wiki/Nilima_Ibrahim$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Nilima%20Ibrahim.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Razia Khan$b$, NULL, DATE '2011-12-28', $b$Razia Khan Amin was a Bangladeshi writer, poet and educationist. She was also a journalist, theatre actor and columnist for newspapers. She was awarded Ekushey Padak in 1997 for her contribution to education by the Government of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Razia_Khan$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Momtazuddin Ahmed$b$, DATE '1935-01-18', DATE '2019-06-02', $b$Momtazuddin Ahmed was a Bangladeshi playwright-actor and educationist. He was also active in the field of culture, performance, literature and other socio-political activities. His theatre activities were mostly in the field of satire.

Source: Wikipedia — https://en.wikipedia.org/wiki/Momtazuddin_Ahmed_(dramatist)$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Momtazuddin%20Ahmed%20taken%20by%20Ragib.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Syed Abdullah Khalid$b$, NULL, DATE '2017-05-20', $b$Syed Abdullah Khalid was a Bangladeshi sculptor and painter. He was awarded Ekushey Padak by the Government of Bangladesh in February 2017.

Source: Wikipedia — https://en.wikipedia.org/wiki/Syed_Abdullah_Khalid$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Syed%20Abdullah%20Khalid.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Hamidul Huq Chowdhury$b$, NULL, DATE '1992-01-18', $b$Hamidul Huq Chowdhury was a Pakistani-Bangladeshi politician. He was the founder of The Pakistan Observer, an English-language newspaper which changed its name to The Bangladesh Observer after the Bangladesh Liberation War. He was educated in Dhaka and Calcutta, and had a career as a lawyer, politician and newspaper proprietor.

Source: Wikipedia — https://en.wikipedia.org/wiki/Hamidul_Huq_Chowdhury$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Hamidul%20Huq%20Choudhury.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Shaikh Jamiruddin$b$, NULL, DATE '1937-06-02', $b$Shaikh Muhammad Jamiruddin was a Bengali Islamic preacher and writer.

Source: Wikipedia — https://en.wikipedia.org/wiki/Shaikh_Jamiruddin$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Munshi%20Sheikh%20Jamiruddin.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Sardar Fazlul Karim$b$, DATE '1925-05-01', DATE '2014-06-15', $b$Sardar Fazlul Karim was a Bangladeshi academic, philosopher and essayist.

Source: Wikipedia — https://en.wikipedia.org/wiki/Sardar_Fazlul_Karim$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Sheikh Jamal$b$, DATE '1954-04-28', DATE '1975-08-15', $b$Sheikh Jamal was a Bangladeshi military personnel and athlete. He was the second son of Sheikh Fazilatunnesa Mujib and Sheikh Mujibur Rahman, the founding president of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Sheikh_Jamal$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Sheikh%20Jamal%20and%20Kader%20Siddique.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Syed Nawab Ali Chowdhury$b$, DATE '1863-12-29', DATE '1929-04-17', $b$Syed Nawab Ali Chowdhury was Nawab of Dhanbari of Tangail in East Bengal.

Source: Wikipedia — https://en.wikipedia.org/wiki/Syed_Nawab_Ali_Chowdhury$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Syed%20Nawab%20Ali%20Chowdhury.JPG?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Tofail Ahmed$b$, DATE '1943-10-22', DATE '2026-06-01', $b$Tofail Ahmed was a Bangladeshi independence activist, Bengali nationalist–Mujibist revolutionary and politician. He played a key role in the 1969 East Pakistan mass uprising and then the Bangladesh Liberation War in 1971. In independent Bangladesh, he was a close confident of Sheikh Mujibur Rahman, and then served as full minister for the ministries of Industries and Commerce under Sheikh Hasina. He was a 8-term Jatiya Sangsad member representing the Bhola-1, Bhola-2 and Bakerganj-1 constituencies during 1973–2024.

Source: Wikipedia — https://en.wikipedia.org/wiki/Tofail_Ahmed_(politician)$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Tofail%20Ahmed%20Dhaka%202019%20%281%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Akbar Ali Khan$b$, NULL, DATE '2022-09-08', $b$Akbar Ali Khan was a Bangladeshi economist and educationist who served as a bureaucrat until 2001. He was a sub-divisional officer of Habiganj during the Bangladesh Liberation War when he decided to join the war. Later, he served as an official of the Mujibnagar Government. After independence, he rejoined the civil service and reached the highest post of Cabinet Secretary. In the meanwhile, he also worked as a university teacher. Towards the end of 2006, he became one of the advisers of the Caretaker Government led by President Iajuddin Ahmed. In October 2007, the Government of Bangladesh constituted a Regulatory Reforms Commission (RRC) with him as the chair.

Source: Wikipedia — https://en.wikipedia.org/wiki/Akbar_Ali_Khan_(economist)$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Akbar%20Ali%20Khan.png?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Abul Hasan$b$, DATE '1947-08-21', DATE '1975-11-26', $b$Abul Hossain Miah was a Bangladeshi poet and journalist.

Source: Wikipedia — https://en.wikipedia.org/wiki/Abul_Hasan_(poet)$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Ahsan Habib$b$, DATE '1917-02-02', DATE '1985-07-10', $b$Ahsan Habib was a Bangladeshi poet and literary figure in Bengali culture. Before the India-Pakistan partition, he worked on several literary magazines: Takbir, Bulbul (1937–38) and The Saogat (1939-43) and he was a staff artiste at the Kolkata Centre of All India Radio. After partition he came to Dhaka and worked on Daily Azad, Monthly Mohammadi, Daily Krishak, Daily Ittehad, Weekly Prabaha, etc.

Source: Wikipedia — https://en.wikipedia.org/wiki/Ahsan_Habib_(poet)$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Shawkat Ali$b$, DATE '1936-02-12', DATE '2018-01-25', $b$Shawkat Ali was a Bangladeshi writer. He was awarded Bangla Academy Literary Award in 1968 and Ekushey Padak in 1990 by the Government of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Shawkat_Ali_(novelist)$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Ali Imam$b$, DATE '1950-12-31', DATE '2022-11-21', $b$Ali Imam was a Bangladeshi children's writer and audio-visual organizer. He wrote many scientific stories, travel stories for children. He was awarded Bangla Academy Literary Award in 2001 in juvenile literature.

Source: Wikipedia — https://en.wikipedia.org/wiki/Ali_Imam_(writer)$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Ali%20Imam%2C%20Bangladeshi%20writer%2008%20%28cropped%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Bashirul Haq$b$, DATE '1942-06-24', DATE '2020-04-04', $b$Bashirul Haq was a Bangladeshi architect, town planner and visiting professor of MIT. He was regarded as one of the most influential architects in South Asia in terms of environmentally and socially responsive design.

Source: Wikipedia — https://en.wikipedia.org/wiki/Bashirul_Haq$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Bashirul%20Haq.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Ajoy Roy$b$, DATE '1935-03-01', DATE '2019-12-09', $b$Ajoy Roy was a Bangladeshi professor of physics at the University of Dhaka, but was best known for his prominent role in Bangladesh's human rights activism and freethinking. He was one of the eminent educationists promoting secular humanism in Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Ajoy_Roy$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Ajoy%20Roy.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Fazilatunnesa Bappy$b$, DATE '1970-12-31', DATE '2020-01-02', $b$Fazilatunesa Bappy was a Bangladeshi lawyer and a politician representing the Bangladesh Awami League party. She was a member of the Jatiya Sangsad.

Source: Wikipedia — https://en.wikipedia.org/wiki/Fazilatunnesa_Bappy$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Fazilatun%20Nasa%20Bappy%20%282%29%20%28cropped%29.jpg?width=640$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Manjural Islam Rana$b$, DATE '1984-05-04', DATE '2007-03-16', $b$Manjural Islam Rana, also known as Qazi Manjural Islam, was a Bangladeshi cricketer who played six Tests and 25 One Day Internationals for Bangladesh. Born in Khulna, he was a slow left-arm orthodox spin bowler. He played for Khulna Division at domestic level and made his One Day International (ODI) debut in November 2003 against England. Three months later, Rana played his first Test against Zimbabwe. On 16 March 2007, he died of severe head injuries sustained in a road accident in Khulna at the age of 22.

Source: Wikipedia — https://en.wikipedia.org/wiki/Manjural_Islam_Rana$b$, 'en', NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url) VALUES (gen_random_uuid(), $b$Anwara Bahar Chowdhury$b$, DATE '1919-02-13', DATE '1987-10-27', $b$Anwara Bahar Chowdhury was a Bangladeshi social activist and writer.

Source: Wikipedia — https://en.wikipedia.org/wiki/Anwara_Bahar_Chowdhury$b$, 'en', NULL);
