-- Bangladeshi singers who have passed away (Wikidata + English/Bengali Wikipedia, CC BY-SA 4.0).
-- Includes singers born in present-day Bangladesh. Photos hotlinked from Wikimedia Commons.
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Abdul Latif$b$, NULL, DATE '2005-02-26', $b$Abdul Latif (1927 – 26 February 2005) was a Bangladeshi singer, musician, and lyricist.  He was the initial composer of the Bengali language movement song, "Amaar Bhaiyer Rakte Rangano Ekushey February". He was awarded Ekushey Padak in 1997 and Independence Day Award in 2002 by the Government of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Abdul_Latif_(musician)$b$, 'en', NULL, $b$Singer$b$, NULL, $b$Dhaka$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Abdul Alim$b$, DATE '1931-07-27', DATE '1974-09-05', $b$Abdul Alim (27 July 1931 – 5 September 1974) was a Bangladeshi folk singer. He won the Bangladesh National Film Award for Best Male Playback Singer in 1975 for playback in Sujan Sakhi. He was posthumously awarded the Ekushey Padak in 1977 and Independence Day Award in 1997 by the government of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Abdul_Alim_(folk_singer)$b$, 'en', NULL, $b$Singer$b$, NULL, $b$Dhaka$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Abdul Ahad$b$, NULL, DATE '1996-05-14', $b$Abdul Ahad (18 January 1918 – 14 May 1996) was a Bangladeshi composer, music director and singer.

Source: Wikipedia — https://en.wikipedia.org/wiki/Abdul_Ahad_(music_director)$b$, 'en', NULL, $b$Singer, Music director, Musician$b$, $b$Rajshahi$b$, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Abdul Karim Shah$b$, NULL, DATE '2014-06-10', $b$Abdul Karim Shah (known as Baul Abdul Karim Shah; c. 1927 – 10 June 2014) was a Bangladeshi baul singer. He was awarded the Ekushey Padak in 2011 for his contribution to arts by the Government of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Abdul_Karim_Shah$b$, 'en', NULL, $b$Singer$b$, NULL, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Abdur Rahman Boyati$b$, DATE '1939-01-01', DATE '2013-08-19', $b$Abdur Rahman Boyati (1 January 1939 – 19 August 2013) was a Bangladeshi folk singer. He was also a lyricist, music composer, director, and poet. He was posthumously awarded the Ekushey Padak in 2015 by the government of Bangladesh. He is most notable for the hits "Mon Amar Deho Ghori Sondhan Kori", "Ei Prithibi Jemon Ache, Temni Pore Robe" and "Din Gele Ar Din Pabi Na".

Source: Wikipedia — https://en.wikipedia.org/wiki/Abdur_Rahman_Boyati$b$, 'en', NULL, $b$Singer, Composer, Poet$b$, $b$Dhaka$b$, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Abbasuddin Ahmed$b$, DATE '1901-10-27', DATE '1959-12-30', $b$Abbasuddin Ahmed (27 October 1901 – 30 December 1959) was a Bengali folk song composer and singer born in the Bengal province of British India. He was known for Bhawaiya folk song, which is a style commonly found in Rangpur, undivided Goalpara district, and Cooch Behar.

Source: Wikipedia — https://en.wikipedia.org/wiki/Abbasuddin_Ahmed$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Abbasuddin%20Ahmed2.jpg?width=640$b$, $b$Singer, Writer, Composer$b$, $b$Tufanganj$b$, $b$East Pakistan$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Abu Zafar$b$, DATE '1943-05-15', DATE '2024-12-06', $b$Abu Zafar (15 May 1943 – 6 December 2024) was a Bangladeshi lyricist, music composer, poet and singer. His notable songs include Ei Padma Ei Meghna, Tomra Bhulei Gecho Mallikadir Naam, Nindar Kata Jodi Na Bidhilo Gaye, Ami Helen Kingba Momtajke Dekhini, and Tumi Raat Ami Raatjaga Pakhi.

The song Ei Padma Ei Meghna ranked 17 among top 20 all time Bengali songs by the listeners of BBC Bangla in 2006.

Source: Wikipedia — https://en.wikipedia.org/wiki/Abu_Zafar_(lyricist)$b$, 'en', NULL, $b$Singer$b$, $b$Kushtia District$b$, $b$Dhaka$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Akhtar Sadmani$b$, DATE '1934-01-02', DATE '2003-12-30', $b$Akhtar Sadmani (2 January 1934 – 30 December 2003) was a Bangladeshi singer. In 2011, he was awarded Ekushey Padak by the government of Bangladesh for his contribution to performance arts.

Source: Wikipedia — https://en.wikipedia.org/wiki/Akhtar_Sadmani$b$, 'en', NULL, $b$Singer$b$, NULL, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Ajit Roy$b$, DATE '1938-06-29', DATE '2011-09-04', $b$Ajit Roy (29 June 1938 – 4 September 2011) was a Bangladeshi Rabindra Sangeet singer. During the Liberation War of 1971 he sang inspiring songs called Gana Sangeet to inspire people to take arms against the Pakistani forces. He was awarded the Independence Day Award in 2000 by the Government of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Ajit_Roy$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Ajit%20Roy.jpg?width=640$b$, $b$Singer$b$, NULL, $b$Dhaka$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Anil Biswas$b$, DATE '1914-07-07', DATE '2003-05-31', $b$Anil Krishna Biswas (7 July 1914 – 31 May 2003), professionally known as Anil Biswas, was an Indian film music director and playback singer from 1935 to 1965, who apart from being one of pioneers of playback singing, is also credited for the first Indian orchestra of twelve pieces and introducing orchestral music and full-blooded choral effects, into Indian cinema. A master in western symphonic music was known for the Indian classical or folk elements, especially Baul and Bhatiyali in his music. The most notable of the over 90 films he composed music for were: Roti (1942), Kismet (1943), Anokha Pyar (1948), Tarana (1951), Waris (1954), Pardesi (1957) and Char Dil Char Rahen (1959).

He was also a pioneer in using the counter melody in film scores, employing technique of western music, ‘cantala’, where one line overlaps the other in contra-melody, recitative prose songs as in Roti (1942), besides he was the first one to start extensively using the Ragmala. Another important element that he introduced was western orchestration, using indigenous instruments both in the songs as well as in their melodic interludes, a trend that soon caught on and paved way for the musicals of Indian cinema today.

He was awarded the Sangeet Natak Akademi Award in 1986, given by the Sangeet Natak Akademi, India's National Academy of Music, Dance & Drama.

Source: Wikipedia — https://en.wikipedia.org/wiki/Anil_Biswas_(composer)$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Composer%20Anil%20Biswas.jpg?width=640$b$, $b$Singer, Composer, Actor$b$, $b$Barishal$b$, $b$New Delhi$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Amaresh Roy Chowdhury$b$, DATE '1928-09-18', DATE '2025-08-12', $b$Amaresh Roy Chowdhury (18 September 1928 – 12 August 2025) was a Bangladeshi classical vocalist of the Indian subcontinent. He was awarded the Ekushey Padak in 2016 by the Government of Bangladesh for his contribution to classical music.

Source: Wikipedia — https://en.wikipedia.org/wiki/Amaresh_Roy_Chowdhury$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/AmareshRoy.jpg?width=640$b$, $b$Singer$b$, $b$Faridpur Sadar Upazila$b$, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Arundhati Devi$b$, NULL, DATE '1990-10-16', $b$Arundhati Devi (née Guha Thakurata; also known as Arundhati Mukherjee or Mukhopadhyay; 29 April 1924 – 16 October 1990) was an Indian actress, director, writer and singer who is predominantly known for her work in Bengali cinema.

Arundhati Devi was a student of Visva-Bharati University where she was trained in Rabindra Sangeet by Sailajaranjan Majumdar. She began her career as a Rabindra Sangeet singer at All India Radio in 1940. As an actress, Arundhati Devi made her film debut in Kartik Chattopadhyay's Bengali film Mahaprasthaner Pathe (1952) which also had a Hindi version titled Yatrik. She later collaborated with directors such as Devaki Kumar Bose in Nabajanma (1956), Asit Sen in Chalachal (1956) and Panchatapa (1957), Prabhat Mukhopadhyay in Maa (1956), Mamata (1957), Bicharak (1959) and Akashpatal (1960), and Tapan Sinha in Kalamati (1958), Jhinder Bondi (1961), and Jatugriha (1964). In 1963, she was conferred with BFJA Award for Best Actress for her role in the National Award winning Bengali film Bhagini Nivedita (1962) directed by Bijoy Bose. In 1967, she was conferred with the National Film Award for Best Film Based On High Literary Work for her directorial debut Chutti at the 14th National Film Awards.

Source: Wikipedia — https://en.wikipedia.org/wiki/Arundhati_Devi$b$, 'en', NULL, $b$Singer, Film director, Actor$b$, $b$Barishal$b$, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Atul Prasad Sen$b$, DATE '1871-10-20', DATE '1934-08-26', $b$Atul Prasad Sen (Bengali: অতুলপ্রসাদ সেন; 20 October 1871 – 26 August 1934) was a Bengali composer, lyricist, singer, writer, lawyer, philanthropist and educationist.

Source: Wikipedia — https://en.wikipedia.org/wiki/Atul_Prasad_Sen$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/%E0%A6%85%E0%A6%A4%E0%A7%81%E0%A6%B2%E0%A6%AA%E0%A7%8D%E0%A6%B0%E0%A6%B8%E0%A6%BE%E0%A6%A6%20%E0%A6%B8%E0%A7%87%E0%A6%A8.jpg?width=640$b$, $b$Poet, Writer, Lyricist, Barrister, Singer$b$, $b$Dhaka$b$, $b$Lucknow$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Ava Alam$b$, DATE '1947-12-26', DATE '1976-11-21', $b$Ava Alam (1947–1976) was a Bangladeshi classical singer and music teacher. She was awarded Ekushey Padak in 1978 by the Government of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Ava_Alam$b$, 'en', NULL, $b$Singer$b$, $b$Madaripur District$b$, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Azad Rahman$b$, DATE '1944-01-01', DATE '2020-05-16', $b$Azad Rahman (1 January 1944 – 16 May 2020)  was a Bangladeshi composer. He won Bangladesh National Film Award for Best Music Director twice and Best Male Playback Singer once for his performance in the films Jadur Bashi (1977) and Chandabaz (1993). He received a gold medal in 2011 from Rabindra Bharati University in Kolkata.

Source: Wikipedia — https://en.wikipedia.org/wiki/Azad_Rahman$b$, 'en', NULL, $b$Singer, Composer$b$, $b$Bardhaman$b$, $b$Shamoly$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Banani Ghosh$b$, NULL, DATE '2023-06-07', $b$Banani Ghosh (died 7 June 2023) was an Indian Bengali musician, primarily known as an exponent of Rabindra Sangeet, but also specializing in the music of Atulprasad Sen, Rajanikanta Sen and others.

Source: Wikipedia — https://en.wikipedia.org/wiki/Banani_Ghosh$b$, 'en', NULL, $b$Singer$b$, $b$Mymensingh$b$, $b$Kolkata$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Bari Siddiqui$b$, DATE '1954-11-15', DATE '2017-11-24', $b$Bari Siddiqui (15 November 1954 – 24 November 2017) was a Bangladeshi singer-songwriter and flautist. His songs include Shua Chan Pakhi, Amar Gaye Joto Dukkho Shoy, Pubali Batashe and Manush Dhoro Manush Bhojo.

Source: Wikipedia — https://en.wikipedia.org/wiki/Bari_Siddiqui$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/%E0%A6%B6%E0%A6%BE%E0%A6%AC%E0%A6%BF%E0%A6%AA%E0%A7%8D%E0%A6%B0%E0%A6%AC%E0%A6%BF%E0%A6%A4%E0%A7%87%20%E0%A6%AC%E0%A6%BE%E0%A6%B0%E0%A7%80%20%E0%A6%B8%E0%A6%BF%E0%A6%A6%E0%A7%8D%E0%A6%A6%E0%A6%BF%E0%A6%95%E0%A7%80.jpg?width=640$b$, $b$Singer, Flautist$b$, $b$Netrokona District$b$, $b$Dhaka$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Bijoy Sarkar$b$, DATE '1903-02-16', DATE '1985-12-04', $b$Bijoy Sarkar (born Bijay Krishna Adhikari; 20 February 1903 – 4 December 1985) was a Bengali poet, baul singer, lyricist, and composer.

Source: Wikipedia — https://en.wikipedia.org/wiki/Bijoy_Sarkar$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Bijay%20Sarkar.jpg?width=640$b$, $b$Singer, Lyricist, Writer$b$, $b$Narail$b$, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Bidit Lal Das$b$, DATE '1938-06-15', DATE '2012-10-08', $b$Bidit Lal Das (15 June 1936 – 8 October 2012), commonly known as Potol Babu, was a Bangladeshi folk singer, composer, and music teacher from Swadhin Bangla Betar Kendra.

Source: Wikipedia — https://en.wikipedia.org/wiki/Bidit_Lal_Das$b$, 'en', NULL, $b$Singer$b$, $b$Sylhet$b$, $b$Dhaka$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Bhaba Pagla$b$, DATE '1902-10-17', DATE '1984-02-26', $b$Bhabendramohan Ray Chaudhury (17 October 1902 – 26 February 1984), better known as Bhaba Pagla, was a  Bengali lyricist, composer, and a devotee of goddess Kali. He is known for his contributions to Bengali folk music. His conventional education did not exceed the primary school level but his creations, mostly lyrics, had been sunk into a deep inner meaning and located in a high thought though common words used for cultural expression. The lyrics also had been composed by him with easy harmony to entertain the masses.

Source: Wikipedia — https://en.wikipedia.org/wiki/Bhaba_Pagla$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Bhaba%20Pagla.jpg?width=640$b$, $b$Composer, Lyricist, Singer$b$, $b$Manikganj District$b$, $b$Kalna$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Bulbul Mahalanobish$b$, DATE '1953-03-10', DATE '2023-07-14', $b$Bulbul Mahalanobish (10 March 1953 – 14 July 2023) was a Bangladeshi Nazrul Geeti singer, poet, author, musician, and stage performer. She was a singer at Swadhin Bangla Betar Kendra, the radio broadcasting centre of Bengali nationalist forces during the Bangladesh Liberation War in 1971.

Source: Wikipedia — https://en.wikipedia.org/wiki/Bulbul_Mahalanobish$b$, 'en', NULL, $b$Singer, Writer, Musician$b$, NULL, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Chinmoy Lahiri$b$, DATE '1920-03-20', DATE '1984-08-17', $b$Acharya Chinmoy Lahiri (Bengali: আচার্য চিন্ময় লাহিড়ী; 20 March 1920 – 17 August 1984) was an Indian vocalist from Bengal in the Hindustani classical tradition. He is known for the Khayal form of singing, as well as for his popular renditions of Dhrupad, Thumri and Tappa, along with Bengali Raga-pradhan songs.

Source: Wikipedia — https://en.wikipedia.org/wiki/Chinmoy_Lahiri$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Acharya%20Chinmoy%20Lahiri.jpg?width=640$b$, $b$Singer$b$, $b$Pabna District$b$, $b$Kolkata$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Dalia Nausheen$b$, NULL, DATE '2026-04-01', $b$Dalia Nausheen (1954 or 1955 – 1 April 2026) was a Bangladeshi Nazrul Sangeet singer. She was one of the artists who participated in the Swadhin Bangla Betar Kendra during the Bangladesh Liberation War in 1971. In recognition of her contribution to music, the government of Bangladesh awarded her the country's second highest civilian award Ekushey Padak in 2020.

Nausheen started practising North Indian Classical music and Nazrul Sangeet at the age of five. Her father Muzharul Islam, a noted architect in South Asia, also inspired her to the music. Sudhin Das was her first teacher. She completed her five-year music course in 1973 from Chhayanaut where she was taught by Sohrab Hossain, Sheikh Luthfur Rahman and Ustad Ful Muhammed. Later, she joined the same institution as a teacher.

Nausheen died of cancer in Dhaka, on 1 April 2026, at the age of 71.

Source: Wikipedia — https://en.wikipedia.org/wiki/Dalia_Nausheen$b$, 'en', NULL, $b$Singer$b$, NULL, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Debabrata Biswas$b$, DATE '1911-08-22', DATE '1980-08-18', $b$Debabrata Biswas (also known as George Biswas or George-da; 23 August 1911 – 18 August 1980) was an Indian vocalist known for his interpretation of Rabindra Sangeet, a genre of music composed by Rabindranath Tagore.

Source: Wikipedia — https://en.wikipedia.org/wiki/Debabrata_Biswas$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Hemango%20with%20Debabrata%20Biswas%2C%20Omar%20Sheikh%2C%20Niranjan%20Sen%20and%20others.%20Pic%20courtesy%20Hemango%20Biswas%27s%20family.tif?width=640$b$, $b$Singer$b$, $b$Kishoreganj District$b$, $b$Kolkata$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Durbin Shah$b$, DATE '1920-11-02', DATE '1977-02-15', $b$Durbin Shah (Bengali: দুর্বিন শাহ) was a Bangladeshi mystic lyric poet and one of the most knowledgeable commentators on Bengali folk literature, Baulsadhak.

Source: Wikipedia — https://en.wikipedia.org/wiki/Durbin_Shah$b$, 'en', NULL, $b$Singer, Poet, Musician$b$, NULL, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Farida Yasmin$b$, DATE '1940-02-03', DATE '2015-08-08', $b$Farida Yasmin (3 February 1940 – 8 August 2015) was a Bangladeshi playback singer.

Source: Wikipedia — https://en.wikipedia.org/wiki/Farida_Yasmin_(singer)$b$, 'en', NULL, $b$Singer$b$, $b$Murshidabad$b$, $b$Dhaka$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Geeta Dutt$b$, DATE '1930-11-23', DATE '1972-07-20', $b$Geeta Dutt (Bengali pronunciation: [ɡita dɔtːo]; born Geeta Ghosh Roy Chowdhuri; 23 November 1930 – 20 July 1972) was an Indian classical and playback singer. She found particular prominence as a playback singer in Hindi cinema and Bengali cinema and is considered as one of the best playback singers of all time in Hindi films. She also sang many modern Bengali songs in the non-film genre.

Source: Wikipedia — https://en.wikipedia.org/wiki/Geeta_Dutt$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Portrait%20of%20Indian%20playback%20singer%20Geeta%20Dutt.jpg?width=640$b$, $b$Singer, Film actor, Actor, Musician$b$, $b$Faridpur District$b$, $b$Mumbai$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Foni Borua$b$, NULL, DATE '2001-06-22', $b$Foni Borua (1915 – 22 June 2001) was a Bangladeshi musician. He was a pioneer of folk culture and modern Kavigan (lyrical folk debates). In recognition of his contributions to music, the Government of Bangladesh awarded him the country's second-highest civilian honor, the Ekushey Padak, in 2001.

Source: Wikipedia — https://en.wikipedia.org/wiki/Foni_Borua$b$, 'en', NULL, $b$Singer, Musician$b$, NULL, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Hemanga Biswas$b$, NULL, DATE '1987-11-22', $b$Hemanga Biswas (Bengali/Assamese: হেমাঙ্গ বিশ্বাস, pronounced [hemaŋɡo biʃːaʃ]; 14 December 1912 –  22 November 1987) was an Indian singer, composer, author and political activist, known for his literature in Bengali and Assamese, advocacy of peoples music, drawing from genres of folk music, including Bhatiali originally popular among the fishermen of Bengal.

Source: Wikipedia — https://en.wikipedia.org/wiki/Hemanga_Biswas$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Hemango%20Biswas%20in%20the%201980s.TIF?width=640$b$, $b$Singer, Writer, Ethnomusicologist$b$, $b$Habiganj District$b$, $b$Kolkata$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Happy Akhand$b$, DATE '1960-10-12', DATE '1987-12-28', $b$Happy Akhand (12 October 1960 – 28 December 1987) was a Bangladeshi rock singer and songwriter. He was one of the pioneering rock musicians in Bangladesh. He was the founding member of the rock band Miles. He is sometimes referred to as the Prince of Bangladeshi Music. His notable songs include the title "আবার এলো যে সন্ধ্যা (The Evening is Here Again)", "কে বাঁশি বাজায় রে? (Who's Playing the Flute?)" and more. He died on 28 December 1987, at the age of 27 years.

Source: Wikipedia — https://en.wikipedia.org/wiki/Happy_Akhand$b$, 'en', NULL, $b$Singer$b$, $b$Dhaka$b$, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Husna Banu Khanam$b$, DATE '1922-02-18', DATE '2006-05-30', $b$Husna Banu Khanam (Bengali: হুসনা বানু খানম, Bengali pronunciation: [ɦusna banu kʰanom]; 18 February 1922 – 30 May 2006) was a Bangladeshi educationist, writer and Nazrul singer. She was a pioneer of Bengali Muslim women journalism. In 1999, she received the Ekushey Padak Award for her contribution in music, and in 2004, she received the Begum Rokeya Medal for her contribution to the socio-economic development of women by the Government of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Husna_Banu_Khanam$b$, 'en', NULL, $b$Singer, Musician$b$, NULL, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Hasina Mumtaz$b$, DATE '1945-03-10', DATE '2024-02-18', $b$Hasina Hossain Mumtaz (10 March 1945 – 18 February 2024) was a Bangladeshi singer. She received Shilpakala Padak awarded by Bangladesh Shilpakala Academy in 2019 for her contribution to vocal music.

Source: Wikipedia — https://en.wikipedia.org/wiki/Hasina_Mumtaz$b$, 'en', NULL, $b$Singer$b$, NULL, $b$Dhaka$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Ila Majumder$b$, NULL, DATE '2011-05-03', $b$Ila Majumder (9 September 1941 — 3 May 2011) was a Bangladeshi classical vocalist. Bangladesh Shilpakala Academy awarded her for the special contribution in the field of culture. She was the spouse of the classical musician of Barin Mazumder.

Source: Wikipedia — https://en.wikipedia.org/wiki/Ila_Majumder$b$, 'en', NULL, $b$Singer, Musician$b$, $b$Pabna District$b$, $b$Dhaka$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Indra Mohan Rajbongshi$b$, DATE '1946-01-26', DATE '2021-04-07', $b$Indra Mohan Rajbongshi (26 January 1946 – 7 April 2021) was a Bangladeshi folk singer. He was the recipient of 2018 Ekushey Padak by the Government of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Indra_Mohan_Rajbongshi$b$, 'en', NULL, $b$Singer$b$, NULL, $b$Bangladesh Medical University$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Julhas Uddin Ahmed$b$, DATE '1933-11-10', DATE '2021-09-24', $b$Ustad Julhas Uddin Ahmed (10 November 1933 – 24 September 2021) was a Bangladeshi Nazrul Geeti singer and teacher. He was awarded Ekushey Padak for his special contribution in Nazrul Geeti by the government of Bangladesh in 2017.

Source: Wikipedia — https://en.wikipedia.org/wiki/Julhas_Uddin_Ahmed$b$, 'en', NULL, $b$Singer$b$, $b$Munshiganj District$b$, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Jalal Uddin Khan$b$, NULL, DATE '1972-07-31', $b$Jalal Uddin Khan (Bengali: জালাল উদ্দিন খাঁ; 25 April 1894 — 31 July 1972) was a Bangladeshi composer of Baul Song from Kendua Upazila, Netrakona. His father's name was Shadaruddin Khan. Influenced by the songs of Baul Rashid Uddin, he started composing folk and Sufi music in 1922 and composed around 500 songs. In 2005, his songs were published in five volumes as Jalalgeetika Shamagra edited by Jatin Sarker. A two-day Jalal Mela is organized every two years in his native village on the occasion of his birthday to commemorate him. In 2024, a vast program was organized by Kendua Upazilla Authority on this occasion. He was posthumously awarded Ekushey Padak in 2024 in the musician category.

Source: Wikipedia — https://en.wikipedia.org/wiki/Jalal_Uddin_Khan$b$, 'en', NULL, $b$Singer, Musician$b$, NULL, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Kangal Harinath$b$, DATE '1833-07-20', DATE '1896-04-18', $b$Harinath Majumdar (20 July 1833 – 18 April 1896), better known as Kangal Harinath, was a Bengali journalist, poet, writer, and Baul singer. He is the writer of Bijoy Basanta (1859), which is in the list of the first published Bengali novels.

Source: Wikipedia — https://en.wikipedia.org/wiki/Kangal_Harinath$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Kangal-harinath.jpg?width=640$b$, $b$Singer, Poet$b$, NULL, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Kasim Uddin$b$, NULL, DATE '1992-08-22', $b$Kasim Uddin (Bengali: কছিম উদ্দিন; died 22 August 1992)  was a veteran folk singer of Bangladesh of Bhawaiya genre. He is reckoned as the greatest Bhawaiya singer after Abbasuddin Ahmed. He is also addressed "The Prince of Bhawaiya". He is considered a cultural icon in Kurigram, where every year on his birth anniversary, 'Kasin Uddin Festival' of folk songs is organised.

Source: Wikipedia — https://en.wikipedia.org/wiki/Kasim_Uddin$b$, 'en', NULL, $b$Singer$b$, NULL, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Khandaker Nurul Alam$b$, NULL, DATE '2016-01-22', $b$Khandaker Nurul Alam (1937 – 22 January 2016) was a Bangladeshi music composer and singer. He won Bangladesh National Film Award for Best Music Director for the films Chandranath (1984), Shuvoda (1986), and Padma Meghna Jamuna (1991). He was awarded Ekushey Padak in 2008 by the Government of Bangladesh for his contribution to Bangladeshi music.

Source: Wikipedia — https://en.wikipedia.org/wiki/Khandaker_Nurul_Alam$b$, 'en', NULL, $b$Singer$b$, $b$Goalpara$b$, $b$Dhaka$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Khalid Hassan Milu$b$, NULL, DATE '2005-03-29', $b$Khalid Hassan Milu (6 April 1960 – 29 March 2005) was a Bangladeshi singer. He received the Bangladesh National Film Award for Best Male Playback Singer for his performance in the film Hridoy Theke Hridoy (1994). He rendered 5,000 songs and performed playback in about 250 films.

Source: Wikipedia — https://en.wikipedia.org/wiki/Khalid_Hassan_Milu$b$, 'en', NULL, $b$Singer$b$, $b$Barishal$b$, $b$Dhaka$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Khoda Box$b$, NULL, DATE '1990-01-15', $b$Khoda Box (1928 – January 15, 1990) was a Bangladeshi Baul singer and composer. He was awarded Ekushey Padak by the Government of Bangladesh in 1990 for his contribution to Baul music.

Source: Wikipedia — https://en.wikipedia.org/wiki/Khoda_Box$b$, 'en', NULL, $b$Singer$b$, NULL, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Khalid Hossain$b$, DATE '1935-12-04', DATE '2019-05-22', $b$Khalid Hossain (4 December 1935 – 22 May 2019) was a Bangladeshi Nazrul Geeti singer. In recognition of his contribution in music, the government of Bangladesh awarded him the country's second highest civilian award Ekushey Padak in 2000.

Source: Wikipedia — https://en.wikipedia.org/wiki/Khalid_Hossain$b$, 'en', NULL, $b$Singer$b$, $b$Krishnanagar$b$, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Khalid$b$, NULL, DATE '2024-03-18', $b$Khalid (1963/1964 – 18 March 2024), born Khalid Anwar Saifullah, was a Bangladeshi singer and one of the pioneers of Bangladeshi pop music in the 1980s and 1990s. Hailing from Gopalganj, he began his musical career in 1981, inspired by legendary singer Bhupen Hazarika’s songs "Ganga Amar Ma" and "Padma Amar Ma".

Source: Wikipedia — https://en.wikipedia.org/wiki/Khalid_(Bangladeshi_singer)$b$, 'en', NULL, $b$Singer$b$, NULL, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Khondokar Faruk Ahmed$b$, NULL, DATE '2001-07-11', $b$Khondokar Faruk Ahmed (1 January 1940 - 11 July 2001) was a prominent Bangladeshi singer. He was a pioneer of modern Bangla songs.

Source: Wikipedia — https://en.wikipedia.org/wiki/Khondokar_Faruk_Ahmed$b$, 'en', NULL, $b$Singer$b$, NULL, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Lucky Akhand$b$, DATE '1956-06-18', DATE '2017-04-21', $b$Lucky Akhand (18 June 1956 – 21 April 2017) was a Bangladeshi singer-composer. He was associated with the musical band Happy Touch. He composed and gave voice to songs including Ei Neel Monihar, Aamay Deko Na, Agey Jodi Janitam, Riti Niti Janina, Polatok Am, Abar Elo Jey Shondhya Porichoy Kobe hobe, Aj achhi kal nei, Hotath kore Bangladesh, Tumi Daklei kachhe astam, Bolechhile kal tumi asbe, Tumi ke bolona, Amake tumi valo besona, Mamonia, and Shadhinota Tomake Niye. He served as the music director of Bangladeshi national radio network Bangladesh Betar.

Source: Wikipedia — https://en.wikipedia.org/wiki/Lucky_Akhand$b$, 'en', NULL, $b$Singer$b$, $b$Dhaka$b$, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Mahbuba Rahman$b$, DATE '1935-03-03', DATE '2026-03-26', $b$Mahbuba Rahman (née Hasnat; 3 March 1935 – 26 March 2026) was a Bangladeshi singer. She worked in the film industry during 1950s and 1960s. Rahman was the playback singer of Mukh O Mukhosh (1956), the first Bengali language feature film produced in erstwhile East Pakistan (now Bangladesh). She was awarded Ekushey Padak in 1998 by the Government of Bangladesh for her contribution to music.

Source: Wikipedia — https://en.wikipedia.org/wiki/Mahbuba_Rahman$b$, 'en', NULL, $b$Singer$b$, NULL, $b$Dhaka$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Mahmudun Nabi$b$, DATE '1940-12-16', DATE '1990-12-20', $b$Mahmudun Nabi (16 December 1936 – 20 December 1990) was a Bangladeshi playback singer. He was awarded Bangladesh National Film Award for Best Male Playback Singer for his performance in the film The Rain (1976).

Source: Wikipedia — https://en.wikipedia.org/wiki/Mahmudun_Nabi$b$, 'en', NULL, $b$Singer$b$, NULL, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Mihir Kumar Nandi$b$, DATE '1945-12-14', DATE '2017-05-06', $b$Mihir Kumar Nandi (14 December 1945 – 6 May 2017) was a Bangladeshi Rabindra Sangeet singer and classical vocalist. He was a singer at the Swadhin Bangla Betar Kendra during the 1971 Liberation War. In 2015, he was awarded Shilpakala Padak in the vocal music category by the Government of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Mihir_Kumar_Nandi$b$, 'en', NULL, $b$Singer$b$, NULL, $b$Chittagong$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Mohammad Ali Siddiqui$b$, DATE '1944-02-02', DATE '2014-11-04', $b$Mohammad Ali Siddiqui (2 February 1944 – 4 November 2014) was a Bangladeshi playback singer. He was a singer in the 1960s, 1970s and 1980s. He has sung a total of 250 songs in his career spanning over three decades. He was awarded with several prizes including the National Award, Dinesh Padak, Bandhan Lifetime Award and Shilpakala Academy Award.

Source: Wikipedia — https://en.wikipedia.org/wiki/Mohammad_Ali_Siddiqui$b$, 'en', NULL, $b$Singer$b$, $b$Netrokona District$b$, $b$Mirpur Thana$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Mukunda Das$b$, DATE '1878-02-22', DATE '1934-05-18', $b$Mukunda Das (Bengali: মুকুন্দদাস; 22 February 1878 – 18 May 1934) was a Bengali poet, ballad singer, composer and patriot, who contributed to the spread of Swadeshi movement in rural Bengal. He was commonly referred to as "Charankabi" (The Writer of Ballads) during his time. His composed "Zatra" plays like "Matripuja" (Worship of Mothers) gained much popularity among the rural folk especially during the British Raj.

Source: Wikipedia — https://en.wikipedia.org/wiki/Mukunda_Das$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Rebel%20poet%20Mukanda%20Das.jpg?width=640$b$, $b$Singer, Poet, Playwright$b$, NULL, $b$Kolkata$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Mumtaz Ali Khan$b$, DATE '1920-08-01', DATE '1990-08-31', $b$Mumtaz Ali Khan (1 August 1920 – 31 August 1990) was a Bangladeshi singer, lyricist, composer, collector of songs. He was awarded Ekushey Padak in 1981 by the Government of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Mumtaz_Ali_Khan_(musician)$b$, 'en', NULL, $b$Singer$b$, $b$Manikganj District$b$, $b$Dhaka$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Mustafa Zaman Abbasi$b$, DATE '1936-12-08', DATE '2025-05-10', $b$Mustafa Zaman Abbasi (Bengali: মুস্তাফা জামান আব্বাসী; 8 December 1936 – 10 May 2025) was a Bangladeshi musicologist. He was awarded Ekushey Padak in 1995 by the Government of Bangladesh. Abbasi was the youngest son of folk singer-composer Abbas Uddin Ahmed. He was a research scholar at the "Kazi Nazrul Islam and Abbasuddin Research and Study Centre" of Independent University, Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Mustafa_Zaman_Abbasi$b$, 'en', NULL, $b$Singer, Musician$b$, NULL, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Parul Ghosh$b$, NULL, DATE '1977-08-13', $b$Parul Ghosh (née Biswas; 1915–13 August 1977) was an Indian playback singer.

Source: Wikipedia — https://en.wikipedia.org/wiki/Parul_Ghosh$b$, 'en', NULL, $b$Singer$b$, $b$Barishal$b$, $b$Malad$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Pagla Kanai$b$, DATE '1809-03-18', DATE '1889-07-12', $b$Pagla Kanai (8 March 1809 – 12 July 1889) was a Bengali mystic folk singer. His songs were in the genre of Jari, Dhua, Pala Gaan, Kobi Gaan, Murshidi, Marfati and Islamic. He was notable for developing a Jari form, called Dhuajari, in which an incident is narrated in a rhythmic tone. He was contemporary of another folk singer Lalon.

Source: Wikipedia — https://en.wikipedia.org/wiki/Pagla_Kanai$b$, 'en', NULL, $b$Singer, Musician, Poet$b$, NULL, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Radharaman Dutta$b$, DATE '1833-05-25', DATE '1915-11-10', $b$Radharaman Dutta (Bengali: রাধারমণ দত্ত; Unknown – 1915), also spelt as Radha Raman Dutta, was an influential Bengali musician and poet. A prominent member of the Bauls, Dutta's body of work has led him to be considered as the "Father of Dhamail songs". His songs are widely covered by contemporary Bengali musicians and lyricist.

Source: Wikipedia — https://en.wikipedia.org/wiki/Radharaman_Dutta$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Radharaman.jpeg?width=640$b$, $b$Singer, Poet$b$, $b$Jagannathpur Upazila$b$, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Pratul Mukhopadhyay$b$, DATE '1942-06-25', DATE '2025-02-15', $b$Pratul Mukhopadhyay (25 June 1942 – 15 February 2025) was an Indian Bengali-language singer, creative artist, activist, and songwriter. He is the writer and the singer of the famous Bengali song Ami Banglay Gan Gai and Dinga Bhashao Sagore. He was a playback singer in the Bengali film Gosaibaganer Bhoot. Mukhopadhyay died at the SSKM Hospital, Kolkata, West Bengal, on 15 February 2025, at the age of 82.

Source: Wikipedia — https://en.wikipedia.org/wiki/Pratul_Mukhopadhyay$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Pratul%20Mukhopadhyay%20at%20the%20Mrinal%20Sen%20Muktamanch%20of%20the%2046th%20International%20Kolkata%20Book%20Fair%20at%20Central%20Park%2C%20Salt%20Lake%20-%202023-02-05%20%282%29%20%28cropped%29.jpg?width=640$b$, $b$Singer, Composer, Lyricist, Singer-songwriter, Recording artist$b$, $b$Barishal$b$, $b$Kolkata$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Probal Chowdhury$b$, NULL, DATE '2009-10-17', $b$Probal Chowdhury (1947 – 17 October 2009) was a Bangladeshi freedom fighter, playback singer and composer. He rendered several songs from Swadhin Bangla Betar Kendra during the Bangladesh Liberation War. After the war, he pursued his solo career in playback.

Source: Wikipedia — https://en.wikipedia.org/wiki/Probal_Chowdhury$b$, 'en', NULL, $b$Singer$b$, $b$Chattogram District$b$, $b$Chittagong$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Ramkanai Das$b$, NULL, DATE '2014-09-05', $b$Ramkanai Das (Bengali: রামকানাই দাস; 1935 – 5 September 2014) was a Bangladeshi folk and classical musician. He was awarded Ekushey Padak by the government of Bangladesh in 2014.

Source: Wikipedia — https://en.wikipedia.org/wiki/Ramkanai_Das$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Pandit%20Ramkanai%20Das%20and%20Subarna%20Das.jpg?width=640$b$, $b$Singer$b$, $b$Sunamganj District$b$, $b$Dhaka$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Ramesh Shil$b$, NULL, DATE '1967-04-06', $b$Ramesh Shil (1877 – April 6, 1967) was a Bengali bard. He belonged to the class of bards, called Kabiyals, who improvised songs in poetic contests evolved in Calcutta and its outskirts in the 18th and the 19th centuries, and also became known for his composition of songs in the Maizbhandari, a musical tradition based in Chittagong. He was awarded Ekushey Padak in 2002 by the Government of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Ramesh_Shil$b$, 'en', NULL, $b$Singer, Poet$b$, NULL, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Sahana Devi$b$, DATE '1897-05-17', DATE '1990-04-06', $b$Sahana Devi (Bengali: সাহানা দেবী) (1897–1990) was an Indian singer, she was a widely listened to singer of Rabindra Sangeet. She was the niece of Deshbandhu Chittaranjan Das.

Source: Wikipedia — https://en.wikipedia.org/wiki/Sahana_Devi$b$, 'en', NULL, $b$Singer, Writer$b$, $b$Faridpur$b$, $b$Pondicherry$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Sagar Sen$b$, DATE '1932-05-15', DATE '1983-01-04', $b$Sagar Sen (15 May 1932 – 4 January 1983) was a Bengali singer. Though primarily known as a Rabindrasangeet artist, he recorded numerous Bengali modern songs.

Source: Wikipedia — https://en.wikipedia.org/wiki/Sagar_Sen$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Sagar%20Sen%20%2815.05.1932%20-%2004.01.1983%29.jpg?width=640$b$, $b$Singer, Composer$b$, $b$Faridpur District$b$, $b$Kolkata$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$S. D. Burman$b$, DATE '1906-10-01', DATE '1975-10-31', $b$Sachin Dev Burman (1 October 1906 – 31 October 1975) was an Indian music director and singer. He was a member of the Tripura royal family. He started his career with Bengali films in 1937. He later began composing for Hindi movies and became one of the most successful and influential Indian film music composers. Burman composed the soundtracks for over 100 movies, including Bengali films and Hindi.

Apart from being a versatile composer, he also sang songs in folk style of East Bengal and light semi-classical. His son, R. D. Burman, was also a celebrated music composer for Bollywood films.

Burman's compositions were sung by the leading singers of the era, including Kishore Kumar, Lata Mangeshkar, Mohammed Rafi, Geeta Dutt, Manna Dey, Hemant Kumar, Asha Bhosle, Shamshad Begum, Mukesh and Talat Mahmood. As a playback singer, Burman sang 14 Hindi and 13 Bengali film songs.

Source: Wikipedia — https://en.wikipedia.org/wiki/S._D._Burman$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Sachin%20Dev%20Burman%202007%20stamp%20of%20India.jpg?width=640$b$, $b$Composer, Singer, Music director, Film score composer, Writer$b$, $b$Cumilla$b$, $b$Mumbai$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Sadi Mohammad$b$, DATE '1957-10-04', DATE '2024-03-13', $b$Sadi Mohammad (4 October 1955 – 13 March 2024) was a Bangladeshi Rabindra Sangeet singer and composer. He served as the director of the cultural organization, Rabi Raag.

Source: Wikipedia — https://en.wikipedia.org/wiki/Sadi_Mohammad$b$, 'en', NULL, $b$Singer, Composer, Writer$b$, NULL, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Sabah Tani$b$, NULL, DATE '2018-02-19', $b$Sabah Tani (died 19 February 2018) was a Bangladeshi singer from the 1980s and 1990s. Her notable songs include "Kichhukhon", "Bhalobasa Bahurupi" and "Kono Baishakhi Raate Jodi".

Source: Wikipedia — https://en.wikipedia.org/wiki/Sabah_Tani$b$, 'en', NULL, $b$Singer$b$, NULL, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Sanjit Acharya$b$, NULL, DATE '2024-12-09', $b$Sanjit Acharya (1953 – 9 December 2024) was a Bangladeshi singer, composer, playwright and lyricist from Chattogram. He is best known for his song O Re Sampanwala, which was used in his play Sampanwala.

Source: Wikipedia — https://en.wikipedia.org/wiki/Sanjit_Acharya$b$, 'en', NULL, $b$Singer$b$, NULL, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Shefali Ghosh$b$, DATE '1941-01-11', DATE '2006-12-31', $b$Shefali Ghosh (c. 1941 – December 31, 2006) was a Bangladeshi music artist. She sang Chittagong's regional songs. She was awarded Ekushey Padak by the Government of Bangladesh in 2008.

Source: Wikipedia — https://en.wikipedia.org/wiki/Shefali_Ghosh$b$, 'en', NULL, $b$Singer, Musician, Writer$b$, NULL, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Shammi Akhtar$b$, DATE '1955-09-22', DATE '2018-01-16', $b$Shammi Akhter (born Shamima Akhtar; 16 February 1957 – 16 January 2018) was a Bangladeshi playback singer. She was awarded the Bangladesh National Film Award for Best Female Playback Singer for the film Bhalobaslei Ghor Bandha Jay Na (2010).

Source: Wikipedia — https://en.wikipedia.org/wiki/Shammi_Akhtar$b$, 'en', NULL, $b$Singer$b$, $b$Jashore$b$, $b$Dhaka$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Sheikh Luthfur Rahman$b$, NULL, DATE '1994-11-30', $b$Sheikh Luthfur Rahman (born 1920) was a Bangladeshi composer and singer. He received the Ekushey Padak from the Government of Bangladesh in 1979. He was notable for the composition of the songs "Orey Bhai, Bangladesher Bangali Ar Nai", “Shunen Hujur Bagher Jaat Eyi Bangalira”, “Manbona Bondhon Manbona” and others.

Source: Wikipedia — https://en.wikipedia.org/wiki/Sheikh_Luthfur_Rahman$b$, 'en', NULL, $b$Singer, Composer$b$, NULL, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Shantanu Biswas$b$, DATE '1954-10-25', DATE '2019-07-12', $b$Shantanu Biswas (25 October 1954 – 12 July 2019) was a Bangladeshi dramatist, playwright, stage director, singer-songwriter and composer. He has written and directed several full-length plays between 1975 and 2019, where he performed as an actor in more than sixteen plays. His major successes include Informer (1982), and Julius Caesar er Shesh Shaat Din (The Last Seven Days of Julius Caesar) (1987).

Born in Chittagong (now Chattogram), Biswas spent his whole life in the port city, where he struggled to establish himself as a dramatist and musician. He has released five solo and two mixed albums. He made his debut album Chirkut in 2009. His last solo Sritir Shohore was released posthumously in 2019 by G-Series. His music as blended with modern poetry, and lyrics with diverse tunes covering different genres of world music.

Source: Wikipedia — https://en.wikipedia.org/wiki/Shantanu_Biswas$b$, 'en', NULL, $b$Singer-songwriter, Composer, Writer, Actor, Playwright$b$, $b$Chittagong$b$, $b$Dhaka$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Sohrab Hossain$b$, DATE '1922-04-09', DATE '2012-12-27', $b$Sohrab Hossain (9 April 1922 – 27 December 2012) was a Bangladeshi singer and an exponent of Nazrul Sangeet. From his childhood, he was interested in music and started learning music. He met singer Abbas Uddin in a function in Ranaghat. Then he went to Kolkata. In Kolkata with the help of Abbas Uddin he started working on a music album but could not finish it.

After the partition of India, he came back to Dhaka where he got a Government job. With the musical troupe of Abbas Uddin he performed all over Bangladesh. He worked as a playback singer in several movies. He was also a teacher of few musical institutions.

Hossain received the Independence Day Award in 1980.

Source: Wikipedia — https://en.wikipedia.org/wiki/Sohrab_Hossain$b$, 'en', NULL, $b$Singer$b$, $b$Nadia district$b$, $b$Dhaka$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Shyam Sundar Baishnab$b$, NULL, DATE '2000-12-04', $b$Shyam Sundar Baishnab (died 4 December 2000) was a Bangladeshi folk singer. He was awarded Ekushey Padak in 2008 by the Government of Bangladesh for his contribution to music.

Source: Wikipedia — https://en.wikipedia.org/wiki/Shyam_Sundar_Baishnab$b$, 'en', NULL, $b$Singer$b$, NULL, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Shujeo Shyam$b$, DATE '1946-03-14', DATE '2024-10-18', $b$Shujeo Shyam (14 March 1946 – 18 October 2024) was a Bangladeshi singer, composer, and music director. He won Bangladesh National Film Award for Best Music Director four times for the films Hason Raja (2002), Joyjatra (2004), Obujh Bou (2010) and Joiboti Konyar Mon (2021). He was awarded Ekushey Padak in 2018 by the Government of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Shujeo_Shyam$b$, 'en', NULL, $b$Singer, Composer$b$, $b$Sylhet District$b$, $b$Bangladesh Medical University$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Suman Kalyanpur$b$, DATE '1937-01-28', DATE '2026-05-31', $b$Suman Kalyanpur (born as Suman Hemmady; 28 January 1937 – 31 May 2026) was an Indian playback singer. Known for her three-decade career in Hindi cinema, she was awarded the Padma Bhushan by the Government of India.

Kalyanpur's career started in 1954 and she went onto become a popular singer in the 1960s and 1970s. She also recorded songs for film in several languages besides Hindi, including Bengali, Marathi, Assamese, Gujarati, Kannada, Angika, Bhojpuri, Rajasthani, Odia and Punjabi.  Her voice has often been mistaken to be that of Lata Mangeshkar due to their similar tone and texture.

Source: Wikipedia — https://en.wikipedia.org/wiki/Suman_Kalyanpur$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Suman%20Kalyanpur%20in%202023.jpg?width=640$b$, $b$Actor, Singer, Composer$b$, $b$Dhaka$b$, $b$Mumbai$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Sudhin Das$b$, DATE '1930-04-30', DATE '2017-06-27', $b$Sudhin Das (pronounced [ʃudʱn daʃ]; 30 April 1930 – 27 June 2017) was a Bangladeshi Nazrul Sangeet musician. He was awarded Ekushey Padak by the Government of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Sudhin_Das$b$, 'en', NULL, $b$Singer$b$, $b$Cumilla$b$, $b$Dhaka$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Zahidur Rahim$b$, NULL, DATE '1978-06-18', $b$Zahidur Rahim (c. 1935 – 18 June 1978) was a Bangladeshi Rabindra Sangeet exponent. He was awarded Ekushey Padak in 2000 by the Government of Bangladesh.

Source: Wikipedia — https://en.wikipedia.org/wiki/Zahidur_Rahim$b$, 'en', NULL, $b$Singer, Musician$b$, $b$Bogura$b$, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Jane Alom$b$, NULL, DATE '2021-03-02', $b$জানে আলম (? – ২ মার্চ ২০২১) বাংলাদেশের একজন স্বনামধন্য কণ্ঠশিল্পী, সুরকার, গীতিকার ও প্রযোজক ছিলেন। বাংলা পপ সঙ্গীতের স্রষ্টা ও প্রচারক হিসেবে যে পাঁচজন শিল্পীকে মনে করা হয় উনি তাদের একজন।

Source: Wikipedia — https://bn.wikipedia.org/wiki/%E0%A6%9C%E0%A6%BE%E0%A6%A8%E0%A7%87_%E0%A6%86%E0%A6%B2%E0%A6%AE$b$, 'bn', NULL, $b$Singer, Composer, Lyricist, Dj producer$b$, $b$Manikganj$b$, $b$Bangladesh Medical University$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Aparesh Lahiri$b$, DATE '1924-08-08', DATE '1998-05-28', $b$অপরেশ লাহিড়ী ( ৮ আগস্ট ১৯২৪ - ২৮ মে ১৯৯৮) একজন বাঙালি সুরকার, গায়ক এবং সঙ্গীত পরিচালক।

অপরেশ লাহিড়ী'র সঙ্গীত জীবনের শুরু হয় আকাশবাণীতে। নানা রকমের গানের সাথে ধ্রুপদী সঙ্গীতেও তিনি দক্ষ ছিলেন। প্রায় ১০০টির মতো চলচ্চিত্রে তিনি সুর দিয়েছেন।

১৯৭২ খ্রিস্টাব্দে তিনি মুম্বাই চলে যান। অপরেশ লাহিড়ীর স্ত্রী বাঁশরী লাহিড়ী একজন গায়িকা ছিলেন। মুম্বাই হিন্দি চলচ্চিত্র জগতের বিখ্যাত সুরকার ও গায়ক বাপ্পী লাহিড়ী তাদের পুত্র।

Source: Wikipedia — https://bn.wikipedia.org/wiki/%E0%A6%85%E0%A6%AA%E0%A6%B0%E0%A7%87%E0%A6%B6_%E0%A6%B2%E0%A6%BE%E0%A6%B9%E0%A6%BF%E0%A6%A1%E0%A6%BC%E0%A7%80$b$, 'bn', NULL, $b$Singer$b$, $b$Rangpur District$b$, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Bimalakanta Roychaudhuri$b$, DATE '1909-12-26', DATE '1980-07-05', $b$বিমলাকান্ত রায়চৌধুরী (২৬ ডিসেম্বর ১৯০৯ - ৫ জুলাই, ১৯৮০) ছিলেন একজন বিশিষ্ট ভারতীয় বাঙালি সঙ্গীত,  সেতার ও সুরবাহার বাদ্যশিল্পী। তার রচিত ভারতীয় সঙ্গীতকোষ গ্রন্থটি সঙ্গীত নাটক অকাদেমি থেকে পুরস্কৃত হয়।

Source: Wikipedia — https://bn.wikipedia.org/wiki/%E0%A6%AC%E0%A6%BF%E0%A6%AE%E0%A6%B2%E0%A6%BE%E0%A6%95%E0%A6%BE%E0%A6%A8%E0%A7%8D%E0%A6%A4_%E0%A6%B0%E0%A6%BE%E0%A6%AF%E0%A6%BC%E0%A6%9A%E0%A7%8C%E0%A6%A7%E0%A7%81%E0%A6%B0%E0%A7%80$b$, 'bn', NULL, $b$Soloist, Singer$b$, $b$Rangpur$b$, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Swapan Gupta$b$, NULL, DATE '2021-10-11', $b$স্বপন গুপ্ত  (১৯৪৬ - ১১ অক্টোবর ২০২১) ছিলেন একজন বিশিষ্ট রবীন্দ্র সংগীত শিল্পী। ২০১৫ খ্রিস্টাব্দে পশ্চিমবঙ্গ সরকার তাকে "সঙ্গীত মহাসম্মান" প্রদান করে।

Source: Wikipedia — https://bn.wikipedia.org/wiki/%E0%A6%B8%E0%A7%8D%E0%A6%AC%E0%A6%AA%E0%A6%A8_%E0%A6%97%E0%A7%81%E0%A6%AA%E0%A7%8D%E0%A6%A4$b$, 'bn', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Swapan%20Gupta.jpg?width=640$b$, $b$Singer$b$, $b$Barisal Division$b$, $b$Kolkata$b$);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Sunil Karmakar$b$, DATE '1959-01-15', DATE '2026-02-06', $b$বাউল শিল্পী সুনীল কর্মকার (১৫ জানুয়ারি ১৯৫৯ – ৬ ফেব্রুয়ারি ২০২৬) ছিলেন বাংলাদেশের একজন নামকরা লোক সংগীতের শিল্পী। দৃষ্টহীন এই শিল্পীর লোক সঙ্গীতে অবদানের জন্য ২০২২ সালে বাংলাদেশ শিল্পকলা একাডেমি প্রদত্ত শিল্পকলা পদক লাভ করেন।

Source: Wikipedia — https://bn.wikipedia.org/wiki/%E0%A6%B8%E0%A7%81%E0%A6%A8%E0%A7%80%E0%A6%B2_%E0%A6%95%E0%A6%B0%E0%A7%8D%E0%A6%AE%E0%A6%95%E0%A6%BE%E0%A6%B0$b$, 'bn', NULL, $b$Singer$b$, $b$Netrokona District$b$, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Abhirup Guhathakurta$b$, NULL, DATE '2025-08-31', $b$অভিরূপ গুহঠাকুরতা ছিলেন একজন বিশিষ্ট রবীন্দ্রসঙ্গীত শিল্পী। অধুনা বাংলাদেশের বরিশালে তিনি জন্মগ্রহণ করেন। তার কাকা ছিলেন প্রখ্যাত রবীন্দ্রসঙ্গীত শিল্পী, সঙ্গীত শিক্ষক ও কলকাতার রবীন্দ্রসঙ্গীত শিক্ষাপ্রতিষ্ঠান দক্ষিণীর প্রতিষ্ঠাতা, শুভ গুহঠাকুরতা। আরেক বিখ্যাত রবীন্দ্রসঙ্গীত শিল্পী, ঋতু গুহ ছিলেন তার বড়ো বোন।

Source: Wikipedia — https://bn.wikipedia.org/wiki/%E0%A6%85%E0%A6%AD%E0%A6%BF%E0%A6%B0%E0%A7%82%E0%A6%AA_%E0%A6%97%E0%A7%81%E0%A6%B9%E0%A6%A0%E0%A6%BE%E0%A6%95%E0%A7%81%E0%A6%B0%E0%A6%A4%E0%A6%BE$b$, 'bn', NULL, $b$Singer$b$, $b$Barishal$b$, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Siddheswar Mukhopadhyay$b$, NULL, DATE '1999-07-08', $b$সিদ্ধেশ্বর মুখোপাধ্যায় (১৯১২ – ৮ জুলাই ১৯৯৯) ছিলেন বিশ শতকের বাংলার বিশিষ্ট সংগীতশিল্পী। তিনি বিখ্যাত সঙ্গীতশিল্পী মানবেন্দ্র মুখোপাধ্যায়ের পিতৃব্য এবং রত্নেশ্বর মুখোপাধ্যায় ও সত্যেশ্বর মুখোপাধ্যায়ের অনুজ ছিলেন।

Source: Wikipedia — https://bn.wikipedia.org/wiki/%E0%A6%B8%E0%A6%BF%E0%A6%A6%E0%A7%8D%E0%A6%A7%E0%A7%87%E0%A6%B6%E0%A7%8D%E0%A6%AC%E0%A6%B0_%E0%A6%AE%E0%A7%81%E0%A6%96%E0%A7%8B%E0%A6%AA%E0%A6%BE%E0%A6%A7%E0%A7%8D%E0%A6%AF%E0%A6%BE%E0%A6%AF%E0%A6%BC$b$, 'bn', NULL, $b$Singer, Music teacher$b$, $b$Wazirpur Upazila$b$, NULL);
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place) VALUES (gen_random_uuid(), $b$Girin Chakraborty$b$, DATE '1918-05-05', DATE '1965-12-22', $b$গিরীন চক্রবর্তী (৫ মে ১৯১৮ – ২২ ডিসেম্বর ১৯৬৫) ছিলেন কিংবদন্তি বাঙালি পল্লীগীতি তথা লোকসঙ্গীত ও নজরুলগীতি গায়ক, সুরকার ও সঙ্গীতগবেষক। অজস্র কালজয়ী বাংলাগান বিশেষকরে লোকসঙ্গীতের অমর স্রষ্টা ছিলেন তিনি।

Source: Wikipedia — https://bn.wikipedia.org/wiki/%E0%A6%97%E0%A6%BF%E0%A6%B0%E0%A7%80%E0%A6%A8_%E0%A6%9A%E0%A6%95%E0%A7%8D%E0%A6%B0%E0%A6%AC%E0%A6%B0%E0%A7%8D%E0%A6%A4%E0%A7%80$b$, 'bn', NULL, $b$Singer$b$, $b$Brahmanbaria$b$, $b$Kolkata$b$);
