-- International celebrities: athletes who have passed away.
-- Selection: deceased people with articles in 70+ Wikipedia languages. Data: Wikidata; biographies: English Wikipedia (CC BY-SA 4.0). Photos hotlinked from Wikimedia Commons.

INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Alfredo Di Stéfano$b$, DATE '1926-07-04', DATE '2014-07-07', $b$Alfredo Stéfano Di Stéfano Laulhé (4 July 1926 – 7 July 2014) was an Argentine and Spanish professional footballer and manager who played as a forward. Nicknamed "Saeta Rubia" ("The Blond Arrow"), he played in all five of Madrid's European Cup victories during the 1950s and 1960s. He played international football for Argentina and Colombia before becoming a naturalised citizen of Spain and playing for its national team. He is widely regarded as one of the greatest footballers of all time and the greatest Real Madrid player ever. He is currently the only player to win the Super Ballon d'Or.

Di Stéfano began his club career at age 17 with Argentina's River Plate in 1943. Due to a footballers' strike in Argentina in 1949, he transferred to Millonarios of Bogotá in the Colombian league until 1953, when he left for Real Madrid. He scored a total of 216 league goals for Real Madrid, a club record at the time. In 1964, Di Stefano signed with Espanyol and played for them for the remainder of his career until retiring at the age of 40 in 1966.

At the international level, Di Stéfano helped Argentina win the Copa América in 1947. However, although having played for three different national teams, he never played a single match at the FIFA World Cup during his career. His 49 goals in the European Cup was the highest of any player at the time. He was awarded the Ballon d'Or in 1957 and 1959. He is currently the seventh highest scorer in the history of Spain's top division, and places fourth on Real Madrid's highest league goalscorer of all time. He is Madrid's joint leading goalscorer in the history of El Clásico, alongside Cristiano Ronaldo.

In November 2003, to celebrate UEFA's Jubilee, Di Stéfano was selected as the Golden Player of Spain by the Royal Spanish Football Federation as their most outstanding player of the past 50 years. He was voted fourth, behind Pelé, Diego Maradona, and Johan Cruyff, in a vote organized by France Football magazine which consulted their former Ballon d'Or winners to elect the Football Player of the Century. In 1989, Di Stefano was awarded the Super Ballon d'Or, given to the best player of the previous three decades, and is currently the award's only ever reciepient. He was also named at 4th in the list of "Greatest male players of the century" by the IFFHS. In 2004, he was named by Pelé in the FIFA 100 list of the world's greatest living players. In 2008 Di Stéfano was honoured by both UEFA and Real Madrid with a special Presidents' award issued by FIFA at a ceremony in Madrid, where a statue was also unveiled.

Awards: Ballon d'Or, Pichichi Trophy, Knight Grand Cross of the Order of Sports Merit, Gold Medal of the Royal Order of Sports Merit, Illustrious Citizen of Buenos Aires, UEFA President's Award

Source: Wikipedia — https://en.wikipedia.org/wiki/Alfredo_Di_St%C3%A9fano$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Di%20stefano%20argentina%20%28cropped%29.jpg?width=640$b$, $b$Association football player, Association football coach$b$, $b$Buenos Aires$b$, $b$Madrid$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Ayrton Senna$b$, DATE '1960-03-21', DATE '1994-05-01', $b$Ayrton Senna da Silva (Brazilian Portuguese: [aˈiʁtõ ˈsẽnɐ dɐ ˈsiwvɐ] ; 21 March 1960 – 1 May 1994) was a Brazilian racing driver and philanthropist who competed in Formula One from 1984 to 1994. Senna won three Formula One World Drivers' Championship titles with McLaren, and—at the time of his death—held the record for most pole positions (65), among others; he won 41 Grands Prix across 11 seasons.

Born and raised in São Paulo, Senna began competitive kart racing aged 13; his first go-kart was built by his father using a lawnmower engine. After twice finishing runner-up at the Karting World Championship, Senna progressed to Formula Ford in 1981, dominating the British and European championships in his debut seasons. He then won the 1983 British Formula Three Championship amidst a close title battle with Martin Brundle, further winning the Macau Grand Prix that year. Senna signed for Toleman in 1984, making his Formula One debut at the Brazilian Grand Prix. After scoring several podium finishes in his rookie season, Senna moved to Lotus in 1985 to replace Nigel Mansell, taking his maiden pole position and victory at the rain-affected Portuguese Grand Prix, a feat he repeated in Belgium. He remained at Lotus for his 1986 and 1987 campaigns, scoring multiple wins in each and finishing third in the latter World Drivers' Championship.

Senna signed for McLaren in 1988 to partner Alain Prost; together, they won 15 of 16 Grands Prix held that season—driving the Honda-powered MP4/4—with Senna taking his maiden championship by three points after winning a then-record eight Grands Prix. Their fierce rivalry culminated in title-deciding collisions at Suzuka in 1989 and 1990, despite Prost's move to Ferrari in the latter, with Prost winning the former title and Senna taking the following. Senna took seven victories, including his home Grand Prix in Brazil, as he secured his third title in 1991. The dominant Williams–Renault combination prevailed throughout his remaining two seasons at McLaren, with Senna achieving several race wins in each, including his record-breaking sixth Monaco Grand Prix victory in 1993 on his way to again finishing runner-up to Prost in the championship. Senna negotiated a move to Williams for his 1994 campaign, replacing the retired Prost to partner Damon Hill.

During the 1994 San Marino Grand Prix at Imola, Senna was killed in a crash whilst leading the race, driving the Williams FW16. His state funeral was attended by about 3 million people.

Following subsequent safety reforms, he was the last fatality in the Formula One World Championship until Jules Bianchi in 2014. Senna achieved 41 wins, 65 pole positions, 19 fastest laps and 80 podiums in Formula One; he remains a legendary figure within motorsport for his raw speed and uncompromising driving style, as well as his philanthropy, and is frequently cited as a national hero of Brazil. He was also widely acclaimed for his wet-weather performances, such as at the 1984 Monaco, 1985 Portuguese and 1993 European Grands Prix. Senna was inducted into the International Motorsports Hall of Fame in 2000 and into the Automotive Hall of Fame in 2025.

Awards: Formula One World Champion, L'Équipe Champion of Champions, Livro dos Heróis e Heroínas da Pátria
Education: Colégio São Luís

Source: Wikipedia — https://en.wikipedia.org/wiki/Ayrton_Senna$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Ayrton%20Senna%209%20-%20Cropped.jpg?width=640$b$, $b$Formula One driver, Racing automobile driver, Businessperson, Philanthropist$b$, $b$maternity hospital of São Paulo$b$, $b$Ospedale Maggiore di Bologna$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Babe Ruth$b$, DATE '1895-02-06', DATE '1948-08-16', $b$George Herman "Babe" Ruth (February 6, 1895 – August 16, 1948) was an American professional baseball player whose career in Major League Baseball (MLB) spanned 22 seasons, from 1914 through 1935. Nicknamed "the Bambino" and "the Sultan of Swat", he began his MLB career as a star left-handed pitcher for the Boston Red Sox, but achieved his greatest fame as a slugging outfielder for the New York Yankees. Ruth is regarded as one of the greatest sports heroes in American culture and is considered by many to be the greatest baseball player of all time. In 1936, Ruth was elected to the Baseball Hall of Fame as one of its "first five" members.

Born in Baltimore, Ruth was sent to St. Mary's Industrial School for Boys at age seven. In 1914, Ruth was signed to play Minor League baseball for the Baltimore Orioles but was soon sold to the Red Sox. By 1916, he had built a reputation as an outstanding pitcher who sometimes hit long home runs, a feat unusual for any player in the dead-ball era. Although Ruth twice won 23 games in a season as a pitcher and was a member of three World Series championship teams with the Red Sox, he wanted to play every day and was allowed to convert to an outfielder. With regular playing time, he broke the MLB single-season home run record in 1919 with 29.

After that season, Red Sox owner Harry Frazee sold Ruth to the Yankees amid controversy. The trade fueled Boston's subsequent 86-year championship drought and popularized the "Curse of the Bambino" superstition. In his 15 years with the Yankees, Ruth helped the team win seven American League (AL) pennants and four World Series championships. His big swing led to escalating home run totals that not only drew fans to the ballpark and boosted the sport's popularity but also helped usher in baseball's live-ball era, which evolved from a low-scoring game of strategy to a sport where the home run was a major factor. As part of the Yankees' vaunted "Murderers' Row" lineup of 1927, Ruth hit 60 home runs, which extended his own MLB single-season record by a single home run. Ruth's last season with the Yankees was 1934, and he retired after a short stint with the Boston Braves the following year. In his career, he led the AL in home runs 12 times.

During Ruth's career, he was the target of intense press and public attention for his baseball exploits and off-field penchants for drinking and womanizing. After his retirement as a player, he was denied the opportunity to manage a major league club, most likely because of poor behavior during parts of his playing career. In his final years, Ruth made many public appearances, especially in support of American efforts in World War II. In 1946, he became ill with nasopharyngeal cancer and died from the disease two years later. Ruth remains a major figure in American culture.

Awards: Major League Baseball Most Valuable Player Award, Major League Baseball All-Star, Boston Red Sox Hall of Fame, Major League Baseball All-Time Team, Major League Baseball All-Century Team, Presidential Medal of Freedom

Source: Wikipedia — https://en.wikipedia.org/wiki/Babe_Ruth$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Babe%20Ruth%2C%201933.jpg?width=640$b$, $b$Baseball player$b$, $b$Baltimore$b$, $b$Memorial Sloan Kettering Cancer Center$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Boris Spassky$b$, DATE '1937-01-30', DATE '2025-02-27', $b$Boris Vasilyevich Spassky (Russian: Борис Васильевич Спасский; January 30, 1937 – February 27, 2025) was a Soviet and Russian chess grandmaster who was the tenth World Chess Champion, holding the title from 1969 to 1972. Spassky played three world championship matches: he lost to Tigran Petrosian in 1966; defeated Petrosian in 1969 to become world champion; then lost to Bobby Fischer in a famous match in 1972.

Spassky won the Soviet Chess Championship twice outright (1961, 1973), and twice lost in playoffs (1956, 1963), after tying for first place during the event proper. He was a World Chess Championship candidate on seven occasions (1956, 1965, 1968, 1974, 1977, 1980, 1985). In addition to his Candidates wins in 1965 and 1968, Spassky reached the semi-final stage in 1974 and the final stage in 1977.

Spassky immigrated to France in 1976 and became a French citizen in 1978. He continued to compete in tournaments, but was no longer a major contender for the world title. Spassky lost an unofficial rematch against Fischer in 1992. In 2012, he left France and returned to Russia.

Awards: Chess Oscar, world chess champion, Order of the Badge of Honour, Medal "For Labour Valour", Honoured Master of Sports of the USSR, Russian Federation Presidential Certificate of Honour, Honorary Railwayman

Source: Wikipedia — https://en.wikipedia.org/wiki/Boris_Spassky$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Dhr.%20Boris%20Spassky%2C%20Bestanddeelnr%20932-7320.jpg?width=640$b$, $b$Chess player$b$, $b$Saint Petersburg$b$, $b$Moscow$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Diogo Jota$b$, DATE '1996-12-04', DATE '2025-07-03', $b$Diogo José Teixeira da Silva (4 December 1996 – 3 July 2025), commonly known as Diogo Jota, was a Portuguese professional footballer who played as a forward and winger. He was known for his finishing, pace, dribbling ability, and work rate.

Jota started his career with Paços de Ferreira, before signing for La Liga club Atlético Madrid in 2016. After two seasons in the Primeira Liga, he was consecutively loaned to Primeira Liga club Porto in 2016 and EFL Championship club Wolverhampton Wanderers in 2017. Having helped them gain promotion to the Premier League, he joined the club in 2018 for a reported €14 million and made 131 appearances for them, scoring 44 goals. In 2020, he signed for Liverpool for a fee reported to be £41 million. He played 182 games and scored 65 goals over five seasons for Liverpool, winning the Premier League in 2025, as well as one FA Cup and two EFL Cup titles.

As a Portugal youth international, Jota represented his country at under-19, under-21, and under-23 levels. He made his senior international debut in November 2019 and was chosen in the squads for two UEFA European Championships (2020 and 2024), but missed the 2022 FIFA World Cup due to injury. He also won the UEFA Nations League in 2019 and 2025.

On 3 July 2025, Jota and his brother André Silva died in a car accident in Cernadilla, Spain. The death was followed by Liverpool retiring his number 20.

Source: Wikipedia — https://en.wikipedia.org/wiki/Diogo_Jota$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Diogo%20Jota%202025%20Cropped.jpg?width=640$b$, $b$Association football player$b$, $b$Porto$b$, $b$Zamora Province$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Enzo Ferrari$b$, DATE '1898-02-18', DATE '1988-08-14', $b$Enzo Anselmo Giuseppe Maria Ferrari (; Italian: [ˈɛntso anˈsɛlmo ferˈraːri]; 18 February 1898 – 14 August 1988) was an Italian racing driver and entrepreneur, the founder of Scuderia Ferrari in Grand Prix motor racing, and subsequently of the Ferrari automobile marque. Under his leadership in Formula One, Ferrari won nine World Drivers' Championships and eight World Constructors' Championships during his lifetime.

He was widely known as il Commendatore or il Drake, a nickname given by British opponents in reference to the English privateer Francis Drake, due to Ferrari's demonstrated ability and determination in achieving significant sports results with his small company. In his final years, he was often referred to as l'Ingegnere ("the Engineer"), il Grande Vecchio ("the Grand Old Man"), il Cavaliere ("the Knight"), il Mago ("the Wizard"), and il Patriarca ("the Patriarch").

Awards: Order of Merit for Labour, Knight Grand Cross of the Order of Merit of the Italian Republic

Source: Wikipedia — https://en.wikipedia.org/wiki/Enzo_Ferrari$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Enzo%20Ferrari%20-%20Wheel%20of%20a%20racing%20car.jpg?width=640$b$, $b$Entrepreneur, Racing automobile driver, Industrialist$b$, $b$Modena$b$, $b$Modena$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Eusébio$b$, DATE '1942-01-25', DATE '2014-01-05', $b$Eusébio da Silva Ferreira (European Portuguese: [ewˈzɛβju ðɐ ˈsilvɐ fɨˈʁɐjɾɐ]; 25 January 1942 – 5 January 2014), nicknamed the "Black Panther", the "Black Pearl" or "o Rei" ("the King"), was a Portuguese footballer who played as a striker. He is considered one of the greatest players of all time as well as Benfica's best player ever. He was known for his speed, technique, athleticism and right-footed shot, making him a prolific goalscorer, accumulating 733 goals in 745 matches. Eusébio was the first ever player to win European Golden Boot, World Cup Golden Boot and UCL Golden Boot. In the UEFA Champions League, he ranks second for the all-time Portuguese top goalscorers, scoring 47 goals.

Eusébio helped Portugal reach third place at the 1966 FIFA World Cup, being the top goalscorer of the tournament with nine goals. He won the Ballon d'Or in 1965 and was runner-up in 1962 and 1966. He is Benfica's all-time top scorer with 473 goals in 440 competitive matches. There, his honours include eleven Primeira Liga titles and a European Cup, also being integral in reaching additional European Cup finals in 1963, 1965 and 1968. He is the second-highest goalscorer, behind Alfredo Di Stéfano, in the pre-Champions League era of the European Cup with 47 goals. He was the European Cup top scorer in 1964–65, 1965–66 and 1967–68. He also won the Bola de Prata for the Primeira Liga top scorer a record seven times. He was the first ever player to win the European Golden Boot, in 1968, a feat he replicated in 1973.

From his retirement until his death, Eusébio was an ambassador of football and was one of the most recognizable faces of his generation. His name often appears in best player of all time lists and polls by football critics and fans. He was elected the ninth-best footballer of the 20th century in a poll by the IFFHS and the tenth-best footballer of the 20th century in a poll by the World Soccer magazine. Pelé named Eusébio as one of the 125 best living footballers in his 2004 FIFA 100 list. He was seventh in the online poll for UEFA Golden Jubilee Poll. In November 2003, to celebrate UEFA's Jubilee, he was selected as the Golden Player of Portugal by the Portuguese Football Federation as their most outstanding player of the past 50 years. Shortly after Eusébio's death, Di Stéfano stated: "For me Eusébio will always be the best player of all time".

Awards: Ballon d'Or, Grand Cross of the Order of Merit of Portugal, Grand Cross of the Order of Prince Henry, UEFA President's Award

Source: Wikipedia — https://en.wikipedia.org/wiki/Eus%C3%A9bio$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Eusebio%20en%201973.jpg?width=640$b$, $b$Association football player, Athlete$b$, $b$Maputo$b$, $b$Lisbon$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Ferenc Puskás$b$, DATE '1927-04-01', DATE '2006-11-17', $b$Ferenc Puskás (né Purczeld; 1 April 1927 – 17 November 2006) was a Hungarian professional footballer and manager. Nicknamed the "Galloping Major", Puskás is widely regarded as one of the greatest players of all time, the greatest Hungarian footballer of all time, and the sport's first international superstar. A forward and an attacking midfielder, he scored 84 goals in 85 international matches for Hungary and later played four international matches for Spain as well. He is the European all-time top assist provider in international football (53). He became an Olympic champion in 1952 and led his nation to the final of the 1954 World Cup. He won three European Cups (1959, 1960, 1966), ten national championships (five Hungarian and five Spanish Primera División) and eight top individual scoring honors. In 1995, he was recognized as the greatest top division scorer of the 20th century by the IFFHS. Scoring 802 goals in 792 official games during his career, he is the seventh top goal scorer of all time by the RSSSF.

The son of former footballer Ferenc Puskás Sr., Puskás started his career in Hungary playing for Kispest and Budapest Honvéd. He was the top scorer in the Hungarian League on four occasions, and in 1948, he was the top goal scorer in Europe. During the 1950s, he was both a prominent member and captain of the Hungary national team, known as the Mighty Magyars. After the Hungarian Revolution, Puskás served a two year ban from UEFA. Despite failing to sign for Ethnikos Piraeus in 1957 under pressure from rival clubs, in 1958, he emigrated to Spain where he successfully signed for Real Madrid at the age of 31. While playing with the club, Puskás won four  Pichichi Trophies, which is awarded to the top goalscorer of La Liga each season, and scored seven goals in two European Cup finals, winning the competition three times with the club and claiming five consecutive La Liga titles. He scored 619 goals in 618 matches in the Hungarian and Spanish leagues and National Cups.

After retiring as a player, he became a coach. The highlight of his coaching career came in 1971 when he guided Panathinaikos to the European Cup final, where they lost 2–0 to Ajax. He also led the club to the championship in 1972, becoming an icon in the country. Afterward he'd have spells at various countries and clubs, including Spain, Paraguay and the Saudi Arabia national team, with varying success. He returned again to Greece to manage an exceptionally strong AEK Athens team for the 1978–79 season. In 1993, he returned to Hungary and took temporary charge of the Hungary national team. In 1998, he became one of the first ever FIFA/SOS Charity ambassadors. In 2002, the Népstadion in Budapest was renamed the Puskás Ferenc Stadion in his honor. He was also declared the best Hungarian player of the last 50 years by the Hungarian Football Federation in the UEFA Jubilee Awards in November 2003. In October 2009, FIFA announced the introduction of the FIFA Puskás Award, awarded to the player who has scored the "most beautiful goal" over the past calendar year. In 2004, he was listed by Pelé in the FIFA 100, which featured his choices for the 100 best living footballers at the time of its release.

Awards: honorary citizen of Budapest, Silver Olympic Order

Source: Wikipedia — https://en.wikipedia.org/wiki/Ferenc_Pusk%C3%A1s$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Puskas%20%281971%29.tif?width=640$b$, $b$Association football player, Association football coach$b$, $b$Budapest$b$, $b$Budapest$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Garrincha$b$, DATE '1933-10-28', DATE '1983-01-20', $b$Manuel Francisco dos Santos (28 October 1933 – 20 January 1983), nicknamed Mané Garrincha, best known as simply Garrincha (Portuguese pronunciation: [ɡaˈʁĩʃɐ], "wren"), was a Brazilian professional footballer who played as a right winger. He is widely regarded as one of the greatest players of all time, and by many, one of the greatest dribblers ever.

Garrincha played a vital role in Brazil's 1958 and 1962 World Cup victories. In 1962, when Pelé was injured, Garrincha led Brazil to a World Cup victory with a dominating performance throughout the tournament. He also became the first player to win the Golden Ball (Player of the tournament), Golden Boot (Leading Goalscorer) and the World Cup in the same tournament. He was also named in the World Cup All-Star Teams of both 1958 World Cup and 1962 World Cup. In 1994, he was named in the FIFA World Cup All-Time Team. Brazil never lost a match while fielding both Garrincha and Pelé. In 1999, he came seventh in the FIFA Player of the Century grand jury vote. He is a member of the World Team of the 20th Century, and was inducted into the Brazilian Football Hall of Fame. Due to his immense popularity in Brazil, he was also called Alegria do Povo (People's Joy) and Anjo de Pernas Tortas (Bent-Legged Angel).

At club level, Garrincha played the majority of his professional career for the Brazilian team Botafogo. In the Maracanã Stadium, the home team room is known as "Garrincha". In the capital Brasília, the Estádio Nacional Mané Garrincha is named after him. He is credited for inspiring the first bullfighting chants of olé to be used at football grounds.

Source: Wikipedia — https://en.wikipedia.org/wiki/Garrincha$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Manoel%20Francisco%20dos%20Santos-Garrincha.jpg?width=640$b$, $b$Association football player$b$, $b$Magé$b$, $b$Rio de Janeiro$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$George Best$b$, DATE '1946-05-22', DATE '2005-11-25', $b$George Best (22 May 1946 – 25 November 2005) was a Northern Irish professional footballer who played as a right winger, spending most of his club career at Manchester United. A skillful dribbler, he is considered one of the greatest players of all time, along with being considered one of the most talented to play. He was named European Footballer of the Year in 1968 and came fifth in the FIFA Player of the Century vote. Best received plaudits for his playing style, which combined pace, skill, balance, feints, the ability to get past defenders and goalscoring. In 1999 he was on the six-man shortlist for the BBC's Sports Personality of the Century. He was an inaugural inductee into the English Football Hall of Fame in 2002.

Born in Belfast, Best began his club career in England with Manchester United, with the scout who had spotted his talent at the age of 15 sending a telegram to manager Matt Busby which read: "I think I've found you a genius". After making his debut at age 17, he scored 179 goals in 470 appearances over 11 years and was the club's top goalscorer in the league for five consecutive seasons. He won two League titles, two Charity Shields and the European Cup with the club.

In international football, Best was capped 37 times for Northern Ireland between 1964 and 1977. A combination of the team's performance and his lack of fitness in 1982 meant that he never played in the finals of a major tournament. He considered his international career as being "recreational football", with the expectations placed on a smaller nation in Northern Ireland being much less than with his club. He is regarded as one of the greatest players never to have played at a World Cup. The Irish Football Association described him as the "greatest player to ever pull on the green shirt of Northern Ireland".

With his good looks, dark Beatle mop-top hair and playboy lifestyle, Best became one of the first media celebrity footballers, earning the nickname "o Quinto Beatle" by Portuguese press reporters after a stand-out performance for Manchester United in Lisbon in March 1966. However, his extravagant lifestyle led to various personal problems, most notably alcoholism, from which he suffered for the rest of his life. These issues affected him on and off the field, often causing controversy. Although conscious of his problems, he made light of them and was known for his intelligence and wit on the subject during periods of sobriety: "I spent a lot of money on booze, girls and fast cars – the rest I just squandered". After football, he spent some time as a football analyst, but his financial and health problems continued into his retirement. He died in 2005, aged 59, from complications from the immunosuppressive drugs he needed to take after a liver transplant in 2002.

Awards: Ballon d'Or, English Football Hall of Fame
Education: Grosvenor Grammar School

Source: Wikipedia — https://en.wikipedia.org/wiki/George_Best$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/George%20Best%20%281976%29.jpg?width=640$b$, $b$Association football player, Sports commentator, Athlete$b$, $b$Belfast$b$, $b$London$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Gerd Müller$b$, DATE '1945-11-03', DATE '2021-08-15', $b$Gerhard "Gerd" Müller (German: [ɡɛʁt ˈmʏlɐ]; 3 November 1945 – 15 August 2021) was a German professional footballer. A prolific striker, especially in and around the six-yard box, he is widely regarded as one of the greatest goalscorers and players in the history of the sport. With success at both the club level and the international level, he is one of eleven players to have won the FIFA World Cup, the UEFA Champions League and the Ballon d'Or.

At international level with West Germany, he scored 68 goals in 62 appearances, and at club level, in 15 years with Bayern Munich, in which he scored 365 goals in 427 Bundesliga matches, he became—and still is—record holder of that league. In 74 European club games he scored 65 goals. Averaging over a goal a game with West Germany, Müller is currently joint-29th on the list of all time international goalscorers, despite having played fewer matches than every other player in the top 37. Among the top scorers, he has the third-highest goal-to-game ratio. He also had the highest ratio of 0.97 goals per game in the European Cup, scoring 34 goals in 35 matches.

Nicknamed "Bomber der Nation" ("the nation's Bomber") or simply "Der Bomber", Müller was named European Footballer of the Year in 1970. After a successful season at Bayern Munich, he scored ten goals at the 1970 FIFA World Cup for West Germany where he received the Golden Boot as top goalscorer, before winning the 1970 Ballon d'Or. In 1972, he won the UEFA European Championship and was the top goalscorer, scoring two goals in the final. Two years later, he scored 4 goals in the 1974 FIFA World Cup, including the winning goal in the final.

Müller held the all-time goal-scoring record in the World Cup with 14 goals for 32 years. In 1999, Müller was ranked ninth in the European Player of the Century election held by the International Federation of Football History & Statistics (IFFHS), and he was voted 13th in the IFFHS' World Player of the Century election. In 2004, Pelé named Müller in the FIFA 100 list of the world's greatest living players.

Awards: German Footballer of the Year, Silbernes Lorbeerblatt, Cross of the Order of Merit of the Federal Republic of Germany, Ballon d'Or, Germany's Sports Hall of Fame, German Football Hall of Fame

Source: Wikipedia — https://en.wikipedia.org/wiki/Gerd_M%C3%BCller$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Gerd%20M%C3%BCller%20c1973%20%28cropped%29.jpg?width=640$b$, $b$Association football player, Association football coach$b$, $b$Nördlingen$b$, $b$Wolfratshausen$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Jesse Owens$b$, DATE '1913-09-12', DATE '1980-03-31', $b$James Cleveland "Jesse" Owens (September 12, 1913 – March 31, 1980) was an American track and field athlete. He made history at the 1936 Olympic Games by winning four gold medals, setting individual Olympic records in each event, plus another as a member of the 400-meter relay. He is widely regarded as one of the greatest athletes in track and field history.

Owens excelled in short sprints and the long jump and was lauded in his lifetime as "perhaps the greatest and most famous athlete in track and field history". Earlier he won four events, set five world records, and tied another—all in less than an hour, at the 1935 Big Ten Championships in Ann Arbor, Michigan, a feat that has never been equaled and was called "the greatest 45 minutes ever in sport". He won four NCAA titles in both 1935 and 1936, bringing his total to eight—an unparalleled achievement still unmatched.

He achieved international fame at the 1936 Summer Olympics in Berlin, Germany, by winning four gold medals: 100 meters, long jump, 200 meters, and 4 × 100-meter relay. He was the most successful athlete at the Games and, as a black American man, was credited by ESPN with "single-handedly crushing Hitler's myth of Aryan supremacy".

The Jesse Owens Award is USA Track & Field's accolade for the year's best track and field athlete. In a 1950 Associated Press poll, Owens was voted the greatest track and field athlete for the first half of the century. In 1999, he made the six-man short-list for the BBC's Sports Personality of the Century. That same year, ESPN ranked him sixth-greatest North American athlete of the twentieth century and the highest-ranked in his sport.

Awards: Presidential Medal of Freedom, Congressional Gold Medal, Theodore Roosevelt Award, Officer's Cross of the Order of Merit of the Federal Republic of Germany, Associated Press Athlete of the Year, IAAF Hall of Fame, Silver Olympic Order
Education: Ohio State University, East Technical High School, North Platte High School

Source: Wikipedia — https://en.wikipedia.org/wiki/Jesse_Owens$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Jesse%20Owens%201936.jpg?width=640$b$, $b$Sprinter, Athletics competitor, Long jumper, Entrepreneur, Athlete, Olympic champion$b$, $b$Oakville$b$, $b$Tucson$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Johan Cruyff$b$, DATE '1947-04-25', DATE '2016-03-24', $b$Hendrik Johannes Cruijff (25 April 1947 – 24 March 2016), internationally known as Johan Cruyff was a Dutch professional football player and manager. Regarded as one of the greatest players in history and as the greatest Dutch footballer ever, he won the Ballon d'Or three times, in 1971, 1973, and 1974. Cruyff was a proponent of the football philosophy known as Total Football, developed by Rinus Michels, both as a player and a manager. Because of the far-reaching impact of his playing style and his coaching ideas, he is widely regarded as one of the most influential figures in modern football, and he is also regarded as one of the greatest managers of all time.

In the late 1960s and early 1970s, Dutch football rose from a semi-professional and obscure level to become a powerhouse in the sport. The Netherlands qualified for the 1974 FIFA World Cup, their first appearance in the competition in 36 years. With three goals and three assists, Cruyff led the Netherlands to the final, where they lost to West Germany; nonetheless, he received the Golden Ball as player of the tournament. After finishing third in UEFA Euro 1976, Cruyff refused to play in the 1978 FIFA World Cup after a kidnapping attempt targeting him and his family in their Barcelona home led to his retirement from international football.

At club level, Cruyff started his career at Ajax in 1964, where he won six Eredivisie titles, three European Cups, and one Intercontinental Cup. He moved to FC Barcelona in 1973, winning the La Liga title in 1973–74, the club's first in 14 years, and the Copa del Rey once. After stints at the Los Angeles Aztecs and the Washington Diplomats in the United States and at Levante in Spain, Cruyff returned to Ajax in 1981, winning two further Eredivisie titles. As the club refused to extend his contract, Cruyff moved to main rivals Feyenoord in 1983, where he won the double (Eredivisie and KNVB Cup) in his first and only season at the club. After retiring from playing in 1984, Cruyff became a highly successful manager of Ajax and Barcelona, winning the 1987 European Cup Winners' Cup at Ajax, and four La Liga titles and one European Cup at Barcelona. After his dismissal in 1996, he remained an advisor to both Ajax and Barcelona. His son Jordi also played football professionally for Barcelona.

Cruyff founded the Johan Cruyff Foundation in 1997, which is intended to help disadvantaged children and those with special educational needs. In addition, he is the originator of several catchphrases and aphorisms, known as Cruijffiaans, that have entered everyday language, especially in the Netherlands and to some extent in Spain. In 1999, Cruyff was voted European Player of the Century in an election held by the International Federation of Football History & Statistics, and came second behind Pelé in their World Player of the Century poll.

Awards: Saint George's Cross, Ballon d'Or, Gold Medal of the City of Barcelona for Cultural, Scientific, Civic or Sports Merit, Dutch Footballer of the Year, Dutch Sportsman of the year, Don Balón Award, Knight of the Order of Orange-Nassau, UEFA President's Award
Education: Sunday school

Source: Wikipedia — https://en.wikipedia.org/wiki/Johan_Cruyff$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Johan%20Cruijff%20%281974%29.jpg?width=640$b$, $b$Association football player, Association football coach, Coach$b$, $b$Betondorp$b$, $b$Barcelona$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Juan Manuel Fangio$b$, DATE '1911-06-24', DATE '1995-07-17', $b$Juan Manuel Fangio (Spanish: [ˈxwan maˈnwel ˈfaŋxjo], Italian: [ˈfandʒo]; 24 June 1911 – 17 July 1995) was an Argentine racing driver, who competed in Formula One from 1950 to 1958. Nicknamed "el Chueco" and "el Maestro", Fangio won five Formula One World Drivers' Championship titles and—at the time of his retirement—held the record for most wins (24), pole positions (29), fastest laps (23), and podium finishes (35), among others.

From childhood, Fangio abandoned his studies to pursue auto mechanics. In 1938, he debuted in the newly-formed Argentine stock car racing series Turismo Carretera, competing in a Ford V8. In 1940, he competed with Chevrolet, winning the Grand Prix International Championship and devoted his time to the Turismo Carretera becoming its champion, a title he successfully defended a year later. Fangio then competed in Europe between 1947 and 1949, where he achieved further success.

One of the most successful drivers in Formula One history, Fangio made his debut in the inaugural Formula One season in 1950 to dominate the first decade of the championship. He went on to win the World Drivers' Championship five times—a record that stood for 46 years—and became the only driver in F1 history to win titles with four different teams: Alfa Romeo (1951), Maserati (1954 and 1957), Mercedes-Benz (1954 and 1955), and Ferrari (1956). He holds the highest winning percentage in Formula One at 46.15%, winning 24 of 52 Formula One races he entered. Additionally, Fangio also holds the record for the highest pole percentage at 55.77%, achieving 29 pole positions from 52 entries. Fangio is the only Argentine driver to have won either the World Drivers' Championship or the Argentine Grand Prix.

Among his greatest F1 wins is the 1955 Argentine Grand Prix, contested in very hot weather for three hours. While the few other finishing cars were driven by two or three younger drivers who took turns, the 44 year old drove the whole race on his own, and set fastest lap doing so. His last GP win was for Maserati at the 1957 German Grand Prix where he faced better Ferrari cars, and opted to make a pit stop for fuel and tyres. After this stop was delayed by mistakes, and his lead was lost, he patiently drove with new tyres and half full tank, then went all-out and caught up to the leaders by taking unprecedented risks and beating the lap record several times.

Fangio also competed in endurance sports car racing, winning the 1953 Carrera Panamericana and the 12 Hours of Sebring in 1956 with Ferrari and in 1957 with Maserati. He finished second in the 1955 Targa Florio, and twice in the Mille Miglia.

After retirement, Fangio presided as the honorary president of Mercedes-Benz Argentina from 1987, a year after the inauguration of his museum, until his death in 1995. In 2011, on the centenary of his birth, Fangio was remembered around the world and various activities were held in his honor.

Awards: diamond Konex award

Source: Wikipedia — https://en.wikipedia.org/wiki/Juan_Manuel_Fangio$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Juan%20Manuel%20Fangio%20%28circa%201952%29.jpg?width=640$b$, $b$Entrepreneur, Formula One driver, Racing automobile driver$b$, $b$Balcarce$b$, $b$Buenos Aires$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Kevin Keegan$b$, DATE '1951-02-14', DATE '2026-07-20', $b$Joseph Kevin Keegan (14 February 1951 – 20 July 2026) was an English football player and manager who played as an attacking midfielder or forward. Nicknamed "King Kev" or "Mighty Mouse", Keegan was recognised for his dribbling ability, finishing and presence in the air, as much as he was for his distinctive appearance and charismatic personality. He is regarded as one of the greatest players of all time and was a widely recognised figure of English football during the 1970s, winning consecutive Ballon d'Ors in 1978 and 1979.

Keegan began his playing career at Scunthorpe United in 1968, before Bill Shankly signed him for Liverpool. There, he won three First Division titles, the UEFA Cup twice, the FA Cup and, in his final season, the European Cup. During this period, he was a regular member of the England national team, and captained the team on 31 occasions, including at UEFA Euro 1980. He moved to Hamburger SV in the summer of 1977 and was named European Footballer of the Year in both 1978 and 1979. Hamburg won the Bundesliga title in the 1978–79 season and reached the 1980 European Cup final. Keegan left Hamburg and played at Southampton for two seasons, before transferring to Newcastle United in the Second Division in 1982. He helped Newcastle secure promotion in his second season, and retired from playing in 1984. He scored 204 goals in 592 appearances in his club career, adding 21 goals in 63 caps for England.

He moved into management at Newcastle in 1992, and the team won promotion to the Premier League as First Division champions in his first full season. Newcastle finished second in the Premier League in the 1995–96 season, despite leading the way for most of the campaign. After managing Fulham for two seasons, he took charge of the England national team in February 1999, but resigned in October 2000 following a 1–0 loss against Germany in qualification for the 2002 FIFA World Cup. In 2001, he became manager of Manchester City for four years, until he resigned in 2005. Keegan had been out of football for almost three years when he returned to Newcastle for a second spell as manager in January 2008, but this lasted only eight months, as he resigned in September following speculation about a dispute with the club's directors. The three clubs he managed were promoted as champions in his first full season in charge of them.

Awards: Officer of the Order of the British Empire, Ballon d'Or

Source: Wikipedia — https://en.wikipedia.org/wiki/Kevin_Keegan$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Kevin%20keegan%20panini%20card%20%28cropped%29.jpg?width=640$b$, $b$Association football player, Association football coach, Autobiographer$b$, $b$Armthorpe$b$, NULL, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Lev Yashin$b$, DATE '1929-10-21', DATE '1990-03-20', $b$Lev Ivanovich Yashin (Russian: Лев Иванович Яшин; 22 October 1929 – 20 March 1990) was a Soviet professional footballer who played as a goalkeeper. Widely regarded as one of the greatest goalkeepers in the history of the sport, he is the only player in his position to win the Ballon d'Or. He was known for his athleticism, positioning, imposing presence in goal, and acrobatic reflex saves. He also served as deputy chairman of the Football Federation of the Soviet Union.

Yashin earned status for revolutionising the goalkeeping position by imposing his authority on the entire defence. A vocal presence in goal, he shouted orders at his defenders, came off his line to intercept crosses and also ran out to meet onrushing attackers, done at a time when goalkeepers spent the entire 90 minutes standing in the goal waiting to be called into action. His performances made an indelible impression on a global audience at the 1958 World Cup, the first to be broadcast internationally. He dressed head to toe in apparent black (in truth very dark blue), thus earning his nicknames "the Black Spider" or "the Black Panther", which enhanced his popularity.

Yashin appeared in three World Cups from 1958 to 1966 and was an unused squad member in 1970. In 2002, he was chosen to the FIFA World Cup Dream Team. In 1994, he was chosen for the FIFA World Cup All-Time Team, and in 1998 was chosen as a member of the World Team of the 20th Century. According to FIFA, Yashin saved over 150 penalty kicks in professional football — more than any other goalkeeper. He also kept over 270 clean sheets in his career, winning a gold medal at the 1956 Olympic football tournament, and the 1960 European Championships.

In 1963, Yashin received the Ballon d'Or, awarded to the European player of the year, the only goalkeeper ever to receive the award. He was additionally named posthumously to the Ballon d'Or Dream Team in 2020, a greatest all-time XI, and was voted the best goalkeeper of the 20th century by the IFFHS. He was also named to the IFFHS All-time Men's Dream Team in 2021. He was named by France Football as the greatest goalkeeper of all time in 2020. In 2025, IFFHS crowned him as the greatest goalkeeper in football history. In November 2003, to celebrate UEFA's Jubilee, he was selected as the Golden Player of Russia by the Russian Football Union as their most outstanding player of the past 50 years. In 2019, France Football established the Yashin Trophy for the best performing goalkeeper in the previous season, and is awarded alongside the Ballon D'Or.

Awards: Hero of Socialist Labour, Master of Sport of the USSR, International Class, Medal "For Valiant Labour in the Great Patriotic War 1941–1945", Ballon d'Or, Medal "Veteran of the Armed Forces of the USSR", Ballon d'Or 1963, Honoured Master of Sports of the USSR, Medal "For Impeccable Service", 3rd class, Medal "For Impeccable Service", 2nd class, Silver Olympic Order
Education: Russian State University of Physical Education, Sport, Youth and Tourism

Source: Wikipedia — https://en.wikipedia.org/wiki/Lev_Yashin$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Lev%20Yashin%201966.jpg?width=640$b$, $b$Association football player, Ice hockey player, Goalkeeper, Athlete$b$, $b$Moscow$b$, $b$Moscow$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Muhammad Ali$b$, DATE '1942-01-17', DATE '2016-06-03', $b$Muhammad Ali ( ah-LEE; born Cassius Marcellus Clay Jr.; January 17, 1942 – June 3, 2016) was an American professional boxer and activist. A global cultural icon, widely known by the nickname "the Greatest", he is often regarded as the greatest heavyweight boxer of all time. He held the Ring magazine heavyweight title from 1964 to 1970, was the undisputed champion from 1974 to 1978, and was the WBA and Ring heavyweight champion from 1978 to 1979. In 1999, he was named Sportsman of the Century by Sports Illustrated and the Sports Personality of the Century by the BBC.

Born in Louisville, Kentucky, he began training as an amateur boxer at age 12. At 18, he won a gold medal in the light heavyweight division at the 1960 Summer Olympics and turned professional later that year. He joined the Nation of Islam in the early 1960s, but later transitioned to Sunni Islam in the mid-1970s after the death of its longtime leader, Elijah Muhammad. He won the world heavyweight championship, defeating Sonny Liston in a major upset on February 25, 1964, at age 22. During that year, he denounced his birth name as a "slave name" and formally changed his name to Muhammad Ali. In 1967, Ali refused to be drafted into the military, owing to his religious beliefs and ethical opposition to the Vietnam War, and was found guilty of draft evasion and stripped of his boxing titles. He stayed out of prison while appealing the decision to the Supreme Court, where his conviction was overturned in 1971. He did not fight for nearly four years and lost a period of peak performance as an athlete. Ali's actions as a conscientious objector to the Vietnam War made him an icon for the larger counterculture of the 1960s generation, and he became a prominent, high-profile figure of racial pride for African Americans during the civil rights movement and throughout his career.

Ali fought in several highly publicized boxing matches, including fights with Liston, Joe Frazier (including the Fight of the Century, which at the time was the biggest boxing event, and the Thrilla in Manila), and George Foreman in The Rumble in the Jungle. At a time when many boxers let their managers do the talking, Ali became renowned for his provocative and outlandish persona. He was famous for trash talking, often free-styled with rhyme schemes and spoken word poetry, and is identified as a pioneer in hip-hop. He often predicted in which round he would knock out his opponent. As a boxer, Ali was known for his unorthodox movement, footwork, head movement, and rope-a-dope technique, among others.

Outside boxing, Ali performed as a spoken word artist, releasing two studio albums: I Am the Greatest! (1963) and The Adventures of Ali and His Gang vs. Mr. Tooth Decay (1976). Both albums received Grammy Award nominations. He also featured as an actor and writer, releasing two autobiographies. Ali retired from boxing in 1981 and focused on religion, philanthropy, and activism. In 1984, he made public his diagnosis of Parkinson's syndrome, which some reports attributed to boxing-related injuries, though he and his specialist physicians disputed this. He remained an active public figure, but in his later years made fewer public appearances as his condition worsened, and was cared for by his family until his death in 2016.

Awards: Presidential Citizens Medal, Presidential Medal of Freedom, Philadelphia Liberty Medal, Arthur Ashe Courage Award, Otto Hahn Peace Medal, Library of Congress Living Legend, Associated Press Athlete of the Year, star on Hollywood Walk of Fame, International Boxing Hall of Fame, WBC World Heavyweight Champion
Education: Santa Monica College, Central High School

Source: Wikipedia — https://en.wikipedia.org/wiki/Muhammad_Ali$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Muhammad%20Ali%20NYWTS.jpg?width=640$b$, $b$Boxer, Autobiographer, Activist, Author, Athlete$b$, $b$Louisville$b$, $b$Scottsdale$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Niki Lauda$b$, DATE '1949-02-22', DATE '2019-05-20', $b$Andreas Nikolaus "Niki" Lauda (22 February 1949 – 20 May 2019) was an Austrian racing driver, motorsport executive, and aviation entrepreneur, who competed in Formula One from 1971 to 1979 and from 1982 to 1985. Lauda won three Formula One World Drivers' Championship titles and—at the time of his retirement—held the record for most podium finishes (54); he won 25 Grands Prix across 13 seasons, and remains the only driver to have won a World Drivers' Championship with both Ferrari and McLaren.

Born and raised in Vienna, Lauda was the grandson of local industrialist Hans Lauda. Starting his career in karting, he progressed to Formula Vee and privateer racing in the late 1960s. After his career stalled, Lauda took out a £30,000 bank loan and secured a place in European Formula Two with March Engineering in 1971, making his Formula One debut with the team at the Austrian Grand Prix. He was promoted to a full-time seat in 1972, ending the season with a non-classified championship finish, while winning the British Formula Two Championship. Lauda moved to BRM for the 1973 season, scoring his maiden points finish in Belgium and earning a seat with Ferrari the following year alongside Clay Regazzoni. Lauda took his maiden podium in his debut for Ferrari, and his maiden victory three races later at the Spanish Grand Prix. After winning five Grands Prix in his 1975 campaign, Lauda won his first title, becoming the first Ferrari-powered World Drivers' Champion in 11 years.

While leading the 1976 championship—amid a fierce title battle with James Hunt—Lauda was seriously injured during the German Grand Prix at the Nürburgring, suffering severe burns and other life-changing injuries when his Ferrari 312T2 caught fire during a crash. He returned to racing six weeks later at the Italian Grand Prix, eventually losing the title to Hunt by one point. Lauda remained at Ferrari in 1977, winning several races on the way to his second championship and clinching the title at the United States Grand Prix. He eventually left Ferrari, where he was replaced by Gilles Villeneuve, and signed with Brabham in 1978, achieving podiums in every race he finished that season, with victories in Sweden and Italy. Amid a winless 1979 season for Brabham, which had moved to Ford Cosworth V8 engines, Lauda left the team after the Italian Grand Prix, and took a two-year hiatus from racing. He returned with McLaren in 1982, winning multiple races. After a winless 1983 campaign, Lauda was partnered by Alain Prost the following season, where he beat Prost to his third title by a record half-point. With seven years between his second and third championships, Lauda holds the record for the longest period in the history of the sport between World Championship victories, breaking Jack Brabham's record of six. Lauda retired after the 1985 season—taking his final victory at the Dutch Grand Prix—having achieved 25 race wins, 24 pole positions, 24 fastest laps, and 54 podiums in Formula One.

Outside of Formula One, Lauda won the Nürburgring 24 Hours in 1973 with Alpina, and the inaugural BMW M1 Procar Championship in 1979 with Project Four. In aviation, Lauda founded and managed three airlines: Lauda Air from 1985 to 1999, Niki from 2003 to 2011, and Lauda from 2016 onwards. He returned to Formula One in an advisory role at Ferrari in 1993, and was the team principal of Jaguar from 2001 to 2002. From 2012 until his death, Lauda was the non-executive chairman and co-owner of Mercedes, winning six consecutive World Constructors' Championships with the team from 2014 to 2019. Lauda was inducted into the International Motorsports Hall of Fame in 1993.

Awards: Grand Gold Decoration of Styria, BBC World Sport Star of the Year

Source: Wikipedia — https://en.wikipedia.org/wiki/Niki_Lauda$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Lauda%20at%201982%20Dutch%20Grand%20Prix.jpg?width=640$b$, $b$Formula One driver, Aircraft pilot, Entrepreneur, Sporting director$b$, $b$Vienna$b$, $b$Zurich$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Paavo Nurmi$b$, DATE '1897-06-13', DATE '1973-10-02', $b$Paavo Johannes Nurmi (Finnish pronunciation: [ˈpɑːʋo ˈnurmi] ; 13 June 1897 – 2 October 1973) was a Finnish middle-distance and long-distance runner. He was called the "Flying Finn" because he dominated distance running in the 1920s. Nurmi set 22 official world records at distances between 1,500 metres and 20 kilometres, and won nine gold and three silver medals in his 12 events in the Summer Olympic Games. At his peak, Nurmi was undefeated for 121 races at distances from 800 m upwards. Throughout his 14-year career, he remained unbeaten in cross country events and the 10,000 metres.

Born into a working-class family, Nurmi left school at the age of 12 to provide for his family. In 1912, he was inspired by the Olympic feats of Hannes Kolehmainen and began developing a strict training program. Nurmi started to flourish during his military service, setting Finnish records in athletics en route to his international debut at the 1920 Summer Olympics. After winning a silver medal in the 5,000 m, he won gold in the 10,000 m and the cross country events. In 1923, Nurmi became the first runner to hold simultaneous world records in the mile, the 5,000 m and the 10,000 m races, a feat which has never been repeated. He set new world records for the 1,500 m and the 5,000 m with just an hour between the races, and took gold medals in both distances in less than two hours at the 1924 Summer Olympics. Seemingly unaffected by the Paris heat wave, Nurmi won all his races and returned home with five gold medals, although he was frustrated that Finnish officials had refused to enter him for the 10,000 m.

Struggling with injuries and motivation issues after his exhaustive U.S. tour in 1925, Nurmi found his long-time rivals compatriot Ville Ritola and Sweden's Edvin Wide ever more serious challengers. At the 1928 Summer Olympics, Nurmi recaptured the 10,000 m title but was beaten for the gold in the 5,000 m and the 3,000 m steeplechase. He then turned his attention to longer distances, breaking the world records for events such as the one hour run and the 25-mile marathon. Nurmi intended to end his career with a marathon gold medal, as his idol Kolehmainen had done. In a controversial case that strained Finland–Sweden relations and sparked an inter-IAAF battle, Nurmi was suspended before the 1932 Games by an IAAF council that questioned his amateur status; two days before the opening ceremonies, the council rejected his entries. Although he was never declared a professional, Nurmi's suspension became definite in 1934 and he retired from running.

Nurmi later coached Finnish runners, raised funds for Finland during the Winter War, and worked as a haberdasher, building contractor and in the financial sector, becoming one of the richest people in Finland. In 1952, he was the lighter of the Olympic Flame at the Summer Olympics in Helsinki. Nurmi's running speed and elusive personality spawned nicknames such as the "Phantom Finn", while his achievements, training methods and running style influenced future generations of middle- and long-distance runners. Nurmi, who rarely ran without a stopwatch in his hand, has been credited with introducing the "even pace" strategy and analytic approach to running, and for making running a major international sport.

Awards: Knight First Class of the Order of the White Rose of Finland, The Great Cross of Merit of Finnish Sports and Culture of Physical Exercise, Knight First Class of the Order of the Lion of Finland, Finnish Olympic Cross of Merit, First Class, First Class Medal of the Order of the White Rose of Finland, IAAF Hall of Fame

Source: Wikipedia — https://en.wikipedia.org/wiki/Paavo_Nurmi$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Paavo%20Nurmi%20%28Antwerp%201920%29.jpg?width=640$b$, $b$Long-distance runner, Marathon runner, Athletics competitor, Athlete$b$, $b$Turku$b$, $b$Helsinki$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Ted Turner$b$, DATE '1938-11-19', DATE '2026-05-06', $b$Robert Edward Turner III (November 19, 1938 – May 6, 2026) was an American businessman, television producer, media proprietor, and philanthropist. He founded CNN, the first 24-hour cable news channel, and WTBS, which pioneered the superstation concept in cable television. Turner also founded the television networks TNT, TBS, The Cartoon Network, Inc., and Turner Classic Movies, and acquired professional wrestling company Jim Crockett Promotions, which became the basis of the promotion World Championship Wrestling (WCW).

Turner began his media empire in March 1963 when he took over his father's billboard business—Turner Outdoor Advertising, then worth $1 million—after his father's suicide at the age of 53. His purchase of an Atlanta UHF station in 1970 began the Turner Broadcasting System. In 1980, he founded CNN, one of the most prominent news networks in the world. Turner owned the Atlanta Braves baseball team, which won the 1995 World Series. He turned the team into a nationally popular franchise, and he launched the charitable Goodwill Games. Turner was also a passionate proponent of professional wrestling as a television product, having aired wrestling on TBS dating back to 1971, and credited wrestling with helping TBS gain a national footprint with the coming of cable television. In 1988, Turner purchased Jim Crockett Promotions, which he then rebranded as WCW, a promotion that would supersede the World Wrestling Federation (WWF, now WWE) in popularity during the mid-1990s, an era now called the Monday Night War.

As a philanthropist, he gave $1 billion to create the United Nations Foundation, a public charity to broaden U.S. support for the United Nations; Turner served as co-chairman of its board of directors. In 2001, he co-founded the Nuclear Threat Initiative (NTI) with U.S. senator Sam Nunn (D‑GA), a non-partisan organization dedicated to reducing global reliance on and preventing the proliferation of nuclear, chemical, and biological weapons.

In 2020, Forbes awarded Turner a perfect philanthropy score of 5, the highest possible rating, placing him among an exclusive group of just ten Forbes 400 members, alongside Warren Buffett, George Soros, Eli Broad, and others who have each given away at least 20% of their fortune.

Turner was also known for his controversial statements, which earned him the nicknames "The Mouth of the South" and "Captain Outrageous". He was the largest private landowner in the United States until John C. Malone surpassed him in 2011. He used much of his land for ranches to re-popularize bison meat for his Ted's Montana Grill chain, having amassed the largest privately owned bison herd in the world. Turner devoted much of his assets to environmental causes and also created the environmental-themed animated series Captain Planet and the Planeteers.

Awards: Peabody Awards, Humanist of the Year, International Emmy Directorate Award, Delta Prize for Global Understanding, Audubon Medal, honorary doctorate of Haifa University, Emperor Has No Clothes Award, Edward R. Murrow Lifetime Achievement Award, Bower Award and Prize for Achievement in Science, star on Hollywood Walk of Fame
Education: Brown University, The McCallie School

Source: Wikipedia — https://en.wikipedia.org/wiki/Ted_Turner$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Ted%20Turner%20at%20the%20LBJ%20Foundation.jpg?width=640$b$, $b$Media proprietor, Philanthropist, Environmentalist, Sailor, Sports executive, Baseball manager$b$, $b$Cincinnati$b$, $b$Lamont$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Tenzing Norgay$b$, DATE '1914-05-29', DATE '1986-05-09', $b$Tenzing Norgay (; Sherpa: བསྟན་འཛིན་ནོར་རྒྱས tendzin norgyé; May 1914 – 9 May 1986), born Namgyal Wangdi, and also referred to as Sherpa Tenzing, was a Nepalese-Indian Sherpa mountaineer. On 29 May 1953, he and Edmund Hillary were the first people confirmed to have reached the summit of Mount Everest, as part of the 1953 British Mount Everest expedition. Time named Norgay one of the 100 most influential people of the 20th century.

Awards: George Medal, Padma Bhushan, Order of the Star of Nepal, Grande Médaille d'Or des Explorations

Source: Wikipedia — https://en.wikipedia.org/wiki/Tenzing_Norgay$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Tenzing%20Norgay%20%28cropped%29.jpg?width=640$b$, $b$Explorer, Mountain guide, Autobiographer, Mountaineer$b$, $b$Tengboche$b$, $b$Darjeeling$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Wilhelm Steinitz$b$, DATE '1836-05-17', DATE '1900-08-12', $b$William Steinitz (born Wilhelm Steinitz; May 14, 1836 – August 12, 1900) was a Bohemian-Austrian, and later American, chess player. From 1886 to 1894, he was the first World Chess Champion. He was also a highly influential writer and chess theoretician.

When discussing chess history from the 1850s onwards, commentators have debated whether Steinitz could be effectively considered the champion from an earlier time, perhaps as early as 1866. Steinitz lost his title to Emanuel Lasker in 1894, and lost a rematch in 1896–97.

Statistical rating systems give Steinitz a rather low ranking among world champions, mainly because he took several long breaks from competitive play. However, an analysis based on one of these rating systems shows that he was one of the most dominant players in the history of the game. Steinitz was unbeaten in match play for 32 years, from 1862 to 1894.

Although Steinitz became "world number one" by winning in the all-out attacking style that was common in the 1860s, he unveiled in 1873 a new positional style of play, and demonstrated that it was superior to the previous style. His new style was controversial and some even branded it as "cowardly", but many of Steinitz's games showed that it could also set up attacks as ferocious as those of the old school.

Steinitz was also a prolific writer on chess, and defended his new ideas vigorously. The debate was so bitter and sometimes abusive that it became known as the "Ink War". By the early 1890s, Steinitz's approach was widely accepted, and the next generation of top players acknowledged their debt to him, most notably his successor as world champion, Emanuel Lasker.

Traditional accounts of Steinitz's character depict him as ill-tempered and aggressive, but more recent research shows that he had long and friendly relationships with some players and chess organizations. Most notably from 1888 to 1889 he co-operated with the American Chess Congress in a project to define rules governing the conduct of future world championships. Steinitz was unskilled at managing money and lived in poverty all his life.

Awards: world chess champion
Education: TU Wien

Source: Wikipedia — https://en.wikipedia.org/wiki/Wilhelm_Steinitz$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Steinitz%2C%20William-4%20-%20DPLA%20-%209eeab9ac335135c24b69ab7e36fc5354%20%28cropped%29.jpg?width=640$b$, $b$Chess player, Chess composer, Chess theoretician$b$, $b$Prague$b$, $b$New York City$b$, 'day', 'day');
