-- International celebrities: other notable people who have passed away.
-- Selection: deceased people with articles in 70+ Wikipedia languages. Data: Wikidata; biographies: English Wikipedia (CC BY-SA 4.0). Photos hotlinked from Wikimedia Commons.

INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Al Capone$b$, DATE '1899-01-17', DATE '1947-01-25', $b$Alphonse Gabriel Capone (, kə-POHN; Italian: [kaˈpoːne]; January 17, 1899 – January 25, 1947), sometimes known by the nickname "Scarface", was an American gangster and businessman who attained notoriety during the Prohibition era as the co-founder and boss of the Chicago Outfit from 1925 to 1931. His seven-year reign as a crime boss ended when he was imprisoned at the age of 33.

Capone was born in New York City in 1899 to Italian immigrants. He joined the Five Points Gang as a teenager and became a bouncer in organized crime premises such as brothels. In his early twenties, Capone moved to Chicago and became a bodyguard of Johnny Torrio, head of a criminal syndicate that illegally supplied alcohol—the forerunner of the Outfit—and was politically protected through the Unione Siciliana.

A conflict with the North Side Gang was instrumental in Capone's rise and fall. Torrio went into retirement after North Side gunmen almost killed him, handing control to Capone. Although Capone expanded the bootlegging business through increasingly violent means, his mutually profitable relationships with Mayor William Hale Thompson and the Chicago Police Department meant he seemed safe from law enforcement.

Capone apparently reveled in attention, such as the cheers from spectators when he appeared at baseball games. He made donations to various charities and was viewed by many as a "modern-day Robin Hood". The Saint Valentine's Day Massacre, in which seven people from rival gangs were murdered in broad daylight, damaged the public image of Chicago and Capone, leading influential citizens to demand government action and newspapers to dub Capone "Public Enemy No. 1".

Federal authorities became intent on jailing Capone and charged him with twenty-two counts of tax evasion. He was convicted of five counts in 1931. During a highly publicized case, the judge admitted as evidence Capone's admissions of his income and unpaid taxes, made during prior and ultimately abortive negotiations to pay the government taxes he owed. He was convicted and sentenced to eleven years in federal prison. After conviction, he replaced his defense team with experts in tax law, and his grounds for appeal were strengthened by a U.S. Supreme Court ruling, although his appeal ultimately failed. Capone showed signs of neurosyphilis early in his sentence and became increasingly debilitated before being released after almost eight years of incarceration. In 1947, he died of cardiac arrest after a stroke.

Source: Wikipedia — https://en.wikipedia.org/wiki/Al_Capone$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Al%20Capone%20in%201930.jpg?width=640$b$, $b$Gangster$b$, $b$Brooklyn$b$, $b$Palm Island$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Albert Speer$b$, DATE '1905-03-19', DATE '1981-09-01', $b$Berthold Konrad Hermann Albert Speer (; German: [ˈʃpeːɐ̯] ; 19 March 1905 – 1 September 1981) was a German architect who served as Minister of Armaments and War Production in Nazi Germany during most of World War II. A close friend and ally of Adolf Hitler, he was convicted at the Nuremberg trials and served 20 years in prison.

An architect by training, Speer joined the Nazi Party in 1931. His architectural skills made him increasingly prominent within the Party, and he became a member of Hitler's inner circle. Hitler commissioned him to design and construct structures, including the Reich Chancellery and the Nazi Party rally grounds in Nuremberg. In 1937, Hitler appointed Speer as General Building Inspector for Berlin. In this capacity he was responsible for the Central Department for Resettlement that evicted Jewish tenants from their homes in Berlin. In February 1942, Speer was appointed as Reich Minister of Armaments and War Production. Using misleading statistics, he promoted himself as having performed an armaments miracle that was widely credited with keeping Germany in the war. In 1944, Speer established a task force to increase production of fighter aircraft. It became instrumental in exploiting slave labor for the benefit of the German war effort.

After the war, Speer was among the 24 major war criminal defendants charged by the International Military Tribunal for Nazi atrocities. He was found guilty of war crimes and crimes against humanity, principally for the use of slave labor, narrowly avoiding a death sentence. Having served his full term, Speer was released in 1966. He used his writings from the time of imprisonment as the basis for two autobiographical books, Inside the Third Reich and Spandau: The Secret Diaries. Speer's books were a success; the public was fascinated by the inside view of the Third Reich he provided. He died of a stroke in 1981.

Through his autobiographies and interviews, Speer carefully constructed an image of himself as a man who deeply regretted having failed to discover the crimes of the Third Reich. He continued to deny explicit knowledge of, and responsibility for, the Holocaust. This image dominated his historiography in the decades following the war, giving rise to the "Speer myth": the perception of him as an apolitical technocrat responsible for revolutionizing the German war machine. The myth began to fall apart in the 1980s, when the armaments miracle was attributed to Nazi propaganda. Twenty-five years after Speer's death, Adam Tooze wrote in The Wages of Destruction that the idea that Speer was an apolitical technocrat was "absurd". Martin Kitchen, writing in Speer: Hitler's Architect, stated that much of the increase in Germany's arms production was actually due to systems instituted by Speer's predecessor (Fritz Todt) and that Speer was intimately aware of and involved in the Final Solution, evidence of which has been conclusively shown in the decades following the Nuremberg trials.

Notable works: Deutsches Stadion, Nazi party rally grounds, Volkshalle, New Chancellery
Education: Technische Universität Berlin

Source: Wikipedia — https://en.wikipedia.org/wiki/Albert_Speer$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Bundesarchiv%20Bild%20146II-277%2C%20Albert%20Speer.jpg?width=640$b$, $b$Politician, Architect, Holocaust perpetrator$b$, $b$Mannheim$b$, $b$London$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Aristotle Onassis$b$, DATE '1906-01-15', DATE '1975-03-15', $b$Aristotle Socrates Onassis (, US also ; Greek: Αριστοτέλης Ωνάσης, romanized: Aristotélis Onásis, pronounced [aristoˈtelis oˈnasis]; 20 January 1906 – 15 March 1975) was a Greek and Argentine business magnate and shipping tycoon. He amassed the world's largest privately-owned shipping fleet and was one of the world's richest and most famous men. He was married to Athina Mary Livanos, had a long-standing affair with opera singer Maria Callas, and in his final years was married to American former First Lady Jacqueline Kennedy.

Onassis was born in Smyrna in the Ottoman Empire to Greek parents and fled the city with his family to Greece in 1922 in the wake of the burning of Smyrna. He moved to Argentina in 1923 and established himself as a tobacco trader and later a shipping owner during the Second World War. Moving to Monaco, Onassis fought Prince Rainier III for economic control of the country through his ownership of SBM and its Monte Carlo Casino. In the mid-1950s, he sought to secure an oil shipping arrangement with Saudi Arabia and engaged in whaling expeditions. In the 1960s, Onassis attempted to establish a large investment contract—Project Omega—with the Greek military junta and sold Olympic Airways, which he had founded in 1957. He was greatly affected by the death of his son, Alexander, in 1973 and died two years later.

Education: Evangelical School of Smyrna

Source: Wikipedia — https://en.wikipedia.org/wiki/Aristotle_Onassis$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Aristotle%20Onassis%201967cr.jpg?width=640$b$, $b$Ship-owner, Businessperson, Entrepreneur$b$, $b$İzmir$b$, $b$Neuilly-sur-Seine$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Barbara McClintock$b$, DATE '1902-06-16', DATE '1992-09-02', $b$Barbara McClintock (June 16, 1902 – September 2, 1992) was an American cytogeneticist who was awarded the 1983 Nobel Prize in Physiology or Medicine. McClintock received her PhD in botany from Cornell University in 1927. There, she started her career as the leader of the development of maize cytogenetics, the focus of her research for the rest of her life. From the late 1920s, McClintock studied chromosomes and how they change during reproduction in maize. She developed the technique for visualizing maize chromosomes and used microscopic analysis to demonstrate many fundamental genetic ideas. One of those ideas was the notion of genetic recombination by crossing-over during meiosis—a mechanism by which chromosomes exchange information. She demonstrated the role of the telomere and centromere, regions of the chromosome that are important in the conservation of genetic information. She was recognized as among the best in the field, awarded prestigious fellowships, and elected a member of the National Academy of Sciences in 1944.

During the 1940s and 1950s, McClintock discovered transposons and used it to demonstrate that genes are responsible for turning physical characteristics on and off. She developed theories to explain the suppression and expression of genetic information from one generation of maize plants to the next. Due to skepticism of her research and its implications, she stopped publishing her data in 1953.

Later, she made an extensive study of the cytogenetics and ethnobotany of maize races from South America. McClintock's research became well understood in the 1960s and 1970s, as other scientists confirmed the mechanisms of genetic change and protein expression that she had demonstrated in her maize research in the 1940s and 1950s. Awards and recognition for her contributions to the field followed, including the Nobel Prize in Physiology or Medicine, awarded to her in 1983 for the discovery of genetic transposition; as of 2025, she remains the only woman who has received an unshared Nobel Prize in that category.

Awards: Guggenheim Fellowship, MacArthur Fellows Program, Albert Lasker Award for Basic Medical Research, Nobel Prize in Physiology or Medicine, Wolf Prize in Medicine, National Women's Hall of Fame, National Medal of Science, Thomas Hunt Morgan Medal, Louisa Gross Horwitz Prize, Connecticut Women's Hall of Fame
Education: Cornell University, Erasmus Hall High School, Cornell University College of Agriculture and Life Sciences, University of Missouri

Source: Wikipedia — https://en.wikipedia.org/wiki/Barbara_McClintock$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Barbara%20McClintock%20%281902-1992%29%20shown%20in%20her%20laboratory%20in%201947.jpg?width=640$b$, $b$Botanist, Olarte, Chemist, University teacher, Geneticist, Cell biologist$b$, $b$Hartford$b$, $b$Huntington$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Bartolomeu Dias$b$, DATE '1450-01-01', DATE '1500-05-29', $b$Bartolomeu Dias (d. 29 May 1500) was a Portuguese mariner and explorer. In February 1488, he became the first European navigator to round the southern tip of Africa and to demonstrate that the most effective southward route for ships is to go diagonally southwest in the open ocean, well to the west of the African coast. His discoveries were later used by Vasco da Gama to establish a sea route between Europe and Asia.

Source: Wikipedia — https://en.wikipedia.org/wiki/Bartolomeu_Dias$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Bartolomeu%20Dias%2C%20South%20Africa%20House%20%28cut%29.JPG?width=640$b$, $b$Explorer$b$, $b$Algarve$b$, $b$Cape of Good Hope$b$, 'year', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Felix Dzerzhinsky$b$, DATE '1877-08-30', DATE '1926-07-20', $b$Felix Edmundovich Dzerzhinsky (11 September [O.S. 30 August] 1877 – 20 July 1926), nicknamed Iron Felix (Russian: Железный Феликс), was a Bolshevik revolutionary and politician of Polish origin. From 1917 until his death in 1926, he led the first three Soviet secret police organizations—the Cheka, the GPU and the OGPU—establishing state security organs for the new Soviet government.

Born to a Polish family of noble descent in Ozhyemblovo estate (now Dzerzhinovo), in Russian Poland, Dzerzhinsky embraced revolutionary politics from a young age, and was active in the Social Democracy of the Kingdom of Poland and Lithuania party. Active in Kaunas and Warsaw, he was frequently arrested and underwent several exiles to Siberia, from which he escaped every time. He evaded the tsarist secret police, the Okhrana, whose work he took interest in. Dzerzhinsky participated in the failed 1905 Revolution, and pursued further revolutionary activities in Germany and Poland. After a final arrest in 1912, was imprisoned until the February Revolution of 1917. He then joined Vladimir Lenin's Bolshevik party, and played an active role in the October Revolution which brought them to power.

In December 1917, Lenin named Dzerzhinsky head of the newly established the All-Russian Extraordinary Commission (Cheka), tasking him with the suppression of counter-revolutionary activities in Soviet Russia. The Russian Civil War saw a vast expansion of the Cheka's authority, inaugurating a campaign of mass arrests, detentions and executions in what became known as the Red Terror. The agency was reorganized as the State Political Directorate (GPU) in 1922, and then as the Joint State Political Directorate (OGPU) a year later, with Dzerzhinsky remaining as head of the powerful organization. He served as director of the Supreme Soviet of the National Economy (VSNKh) from 1924.

Dzerzhinsky died of a heart attack in 1926, and was buried in the Kremlin Wall Necropolis. He was remembered by secret police agents (known as "Chekists" throughout the Soviet era) as a hero of the revolution. A large statue of him stood in front of the security service headquarters at Moscow's Lubyanka Building until 1991. He also became a prominent symbol of repression and brutality to critics of the Soviet government.

Awards: Order of the Red Banner, Honorary Worker of the VChK–GPU (V)
Education: Saint Petersburg State University, 1st Vilna Men's Gymnasium

Source: Wikipedia — https://en.wikipedia.org/wiki/Felix_Dzerzhinsky$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Feliks%20Dzier%C5%BCy%C5%84ski.jpg?width=640$b$, $b$Politician, Revolutionary, Communist$b$, $b$Dzerzhinovo$b$, $b$Moscow$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Ferdinand II, Holy Roman Emperor$b$, DATE '1578-07-09', DATE '1637-02-15', $b$Ferdinand II (9 July 1578 – 15 February 1637) was Holy Roman Emperor, King of Bohemia, Hungary, and Croatia from 1619 until his death in 1637. He was the son of Archduke Charles II of Inner Austria and Maria of Bavaria, who were devout Catholics. In 1590, when Ferdinand was 11 years old, they sent him to study at the Jesuits' college in Ingolstadt because they wanted to isolate him from the Lutheran nobles. A few months later, his father died, and he inherited Inner Austria–Styria, Carinthia, Carniola and smaller provinces. His cousin, Rudolf II, Holy Roman Emperor, who was the head of the Habsburg family, appointed regents to administer these lands.

Ferdinand was installed as the actual ruler of the Inner Austrian provinces in 1596 and 1597. Rudolf II also charged him with the command of the defense of Croatia, Slavonia, and southeastern Hungary against the Ottoman Empire. Ferdinand regarded the regulation of religious issues as a royal prerogative and introduced strict Counter-Reformation measures from 1598. First, he ordered the expulsion of all Protestant pastors and teachers; next, he established special commissions to restore the Catholic parishes. The Ottomans captured Nagykanizsa in Hungary in 1600, which enabled them to invade Styria. A year later, Ferdinand tried to recapture the fortress, but the action ended in November 1601 with a defeat, due to the unprofessional command of his troops. During the first stage of the family feud known as the Brothers' Quarrel, Ferdinand initially supported Rudolph II's brother, Matthias, who wanted to convince the melancholic emperor to abdicate, but Matthias' concessions to the Protestants in Hungary, Austria, and Bohemia outraged Ferdinand. He planned an alliance to strengthen the position of the Catholic Church in the Holy Roman Empire, but the Catholic princes established the Catholic League without his participation in 1610.

Philip III of Spain, who was the childless Matthias' nephew, acknowledged Ferdinand's right to succeed Matthias in Bohemia and Hungary in exchange for territorial concessions in 1617. Spain also supported Ferdinand against the Republic of Venice during the Uskok War in 1617–1618. The Diets of Bohemia and Hungary confirmed Ferdinand's position as Matthias' successor only after he had promised to respect the Estates' privileges in both realms. The different interpretation of the Letter of Majesty, which summarized the Bohemian Protestants' liberties, gave rise to an uprising, known as the Second Defenestration of Prague on 23 May 1618. The Bohemian rebels established a provisional government, invaded Upper Austria, and sought assistance from the Habsburgs' opponents. Matthias II died on 20 March 1619. Ferdinand was elected Holy Roman Emperor on 28 August 1619 (Frankfurt), two days before the Protestant Bohemian Estates deposed Ferdinand (as king of Bohemia). News of his deposition arrived in Frankfurt on the 28th, but Ferdinand did not leave the city until he had been crowned. The rebel Bohemians offered their crown to the Calvinist Frederick V of the Palatinate on 26 August 1619.

Awards: Knight of the Order of the Golden Fleece
Education: University of Ingolstadt

Source: Wikipedia — https://en.wikipedia.org/wiki/Ferdinand_II,_Holy_Roman_Emperor$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Kaiser%20Ferdinand%20II.%201614.jpg?width=640$b$, $b$Aristocrat$b$, $b$Graz$b$, $b$Vienna$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Ferdinand Magellan$b$, DATE '1480-01-01', DATE '1521-04-27', $b$Ferdinand Magellan (c. 1480 – 27 April 1521) was a Portuguese explorer best known for planning and leading the 1519–1522 Spanish expedition to the East Indies. During this expedition, he became the first European to encounter the Strait of Magellan, performed the first European crossing of the Pacific Ocean, and made the first known European contact with the Philippines. Magellan was killed in battle in the Philippines in 1521, but his crew, commanded by Spanish navigator Juan Sebastián Elcano, completed the return trip to Spain in 1522, achieving the first circumnavigation of Earth in history.

Born around 1480 into a family of minor Portuguese nobility, Magellan became a skilled sailor and naval officer in the service of the Portuguese Crown in Asia. However, King Manuel I refused to support Magellan's plan to reach the Moluccas, or Spice Islands, by sailing westwards around the American continent. Magellan then proposed the same plan to King Charles I of Spain, who approved it. In Seville, he married, fathered two children, and organized the expedition. In 1518, for his allegiance to the Hispanic monarchy, Magellan was appointed an admiral of the Spanish fleet and given command of the expedition—the five-ship "Armada of Molucca". He also was made a Commander of the Order of Santiago, one of the highest military ranks of the Spanish Empire.

Granted special powers and privileges by the king, he led the Armada from Sanlúcar de Barrameda southwest across the Atlantic Ocean, to the eastern coast of South America, and south to Patagonia. Despite a series of storms and mutinies, the expedition successfully passed through the Strait of Magellan into the Mar del Sur, which Magellan renamed the Mar Pacifico, or Pacific Ocean. The expedition landed at Guam after an arduous crossing of the Pacific, then reached the Philippines. There, on 27 April 1521, Magellan died in the Battle of Mactan after being shot in the neck with a poison arrow. Under the command of Captain Juan Sebastián Elcano, the expedition finally reached the Spice Islands. The fleet's two remaining ships then parted ways, one attempting, unsuccessfully, to reach New Spain by sailing east across the Pacific. The other ship, commanded by Elcano, sailed west across the Indian Ocean and north along the Atlantic coast of Africa, finally returning to Spain in September 1522.

While in the Kingdom of Portugal's service, Magellan had already reached the Malay Archipelago in Southeast Asia on previous voyages traveling east (from 1505 to 1511–1512). By visiting this area again but now traveling west, Magellan achieved a nearly complete personal circumnavigation of the globe for the first time in history.

Awards: Master of the Order of Santiago, Military Order of Saint James of the Sword, Order of Christ

Source: Wikipedia — https://en.wikipedia.org/wiki/Ferdinand_Magellan$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Retrato%20de%20Hernando%20de%20Magallanes.jpg?width=640$b$, $b$Explorer, Sailor, Seafarer$b$, $b$Ponte da Barca$b$, $b$Mactan$b$, 'year', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Gavrilo Princip$b$, DATE '1894-07-25', DATE '1918-04-28', $b$Gavrilo Princip (Serbian Cyrillic: Гаврило Принцип, pronounced [ɡǎʋrilo prǐnt͡sip]; 25 July 1894 – 28 April 1918) was a Bosnian Serb student who assassinated Archduke Franz Ferdinand, heir presumptive to the throne of Austria-Hungary, and his wife Sophie, Duchess of Hohenberg, in Sarajevo on 28 June 1914. The assassination set off the July Crisis, a series of events that within one month led to the outbreak of World War I.

Princip was born in western Bosnia to a poor Serb family. Aged 13, he was sent to Sarajevo, the capital of Austrian-occupied Bosnia, to study at the Merchants' School. He later transferred to the gymnasium, where he became politically aware. In 1911, he joined Young Bosnia, a secret local society aiming to free Bosnia from Austrian rule and achieve the unification of the South Slavs. After attending anti-Austrian demonstrations in Sarajevo, he was expelled from school and walked to Belgrade, Serbia, to continue his education. During the First Balkan War, Princip traveled to Southern Serbia to volunteer with the Serbian army's irregular forces fighting against the Ottoman Empire but was rejected for being too small and weak.

In 1913, following the unexpected success of the Serbians in the war against the Ottomans, the Austrian military governor of Bosnia, Oskar Potiorek, declared a state of emergency, dissolved the parliament, imposed martial rule, and banned Serbian public, cultural, and educational societies. Inspired by assassination attempts against Imperial officials by Slavic nationalists and anarchists, Princip persuaded two other young Bosnians to join a plot to assassinate the heir to the Habsburg Empire during his announced visit to Sarajevo. The Black Hand, a Serbian secret society with ties to Serbian military intelligence, provided the conspirators with weapons and training before facilitating their re-entry into Bosnia.

On Sunday 28 June 1914, during the royal couple's visit to Sarajevo, the then-teenager Princip mortally wounded Franz Ferdinand and Sophie by firing a pistol into their convertible car. Princip was arrested immediately by Austro-Hungarian authorities and tried alongside 24 others, all Bosnians and thus Austro-Hungarian subjects. At his trial, Princip stated: "I am a Yugoslav nationalist, aiming for the unification of all Yugoslavs, and I do not care what form of state, but it must be free from Austria." Princip was spared the death penalty because of his age (19) and sentenced to twenty years in prison. He was imprisoned at the Terezín Fortress. The Serbian government itself did not inspire the assassination but the Austrian Foreign Office and Army used the murders as a reason for a preventive war which led directly to World War I.

Princip died on 28 April 1918 of tuberculosis, worsened by harsh prison conditions, that had already led to the amputation of his right arm. His legacy is viewed as controversial; many Serbs regard him as a hero who stood against colonial oppression and slavery, while Bosniaks and Croats frequently view him as a terrorist.

Education: First Belgrade Gymnasium

Source: Wikipedia — https://en.wikipedia.org/wiki/Gavrilo_Princip$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Gavrilo%20Princip%2C%20cell%2C%20headshot%2C%20bw%20%28cropped%29.jpg?width=640$b$, $b$Revolutionary$b$, $b$Obljaj$b$, $b$Theresienstadt Small Fortress$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Heinrich Himmler$b$, DATE '1900-10-07', DATE '1945-05-23', $b$Heinrich Luitpold Himmler (German: [ˈhaɪnʁɪç ˈluːɪtpɔlt ˈhɪmlɐ] ; 7 October 1900 – 23 May 1945) was a German Nazi politician, police administrator, and military leader. He was the fourth and longest-serving Reichsführer of the Schutzstaffel (Protection Squadron; SS), serving from 1929 to 1945. He was a leading member of the Nazi Party and one of the most powerful figures in Nazi Germany. He was also one of the main architects of the Holocaust, the genocide of European Jews during World War II.

After serving in a reserve battalion during World War I without seeing combat, Himmler went on to join the Nazi Party in 1923. In 1925, he joined the SS, which was initially a small paramilitary arm of the Nazi Party that served as a bodyguard unit for Adolf Hitler. Himmler rose steadily through the SS's ranks to become Reichsführer-SS by 1929. Under Himmler's leadership, the SS grew from a 290-man battalion into one of the most powerful institutions in Nazi Germany. Over the course of his career, Himmler acquired a reputation for good organisational skills and for selecting highly competent subordinates, such as Reinhard Heydrich. From 1943 onwards, he was both Chief of the Kriminalpolizei (Criminal Police) and Minister of the Interior, which gave him oversight of all police and security forces (including the Gestapo). He also controlled the Waffen-SS, a branch of the SS that served in combat alongside the Wehrmacht (Germany's armed forces) in World War II.

As the principal enforcer of the Nazis' racial policies, Himmler was responsible for operating concentration and extermination camps as well as forming the Einsatzgruppen death squads in German-occupied Europe. In this capacity, he played a central role in the genocide of an estimated 5.5–6 million Jews and the deaths of millions of other victims during the Holocaust. A day before the launch of Operation Barbarossa in June 1941, Himmler commissioned the drafting of Generalplan Ost, which was approved by Hitler in May 1942 and implemented by the Nazi regime, resulting in the deaths of approximately 14 million people in Eastern Europe.

In the last years of World War II, Hitler appointed Himmler as Commander of the Replacement Army and General Plenipotentiary for the administration of the Third Reich (Generalbevollmächtigter für die Verwaltung). He was later given command of the Army Group Upper Rhine and the Army Group Vistula. He failed to achieve his assigned objectives, and Hitler replaced him in these posts. Realising the war was lost, Himmler attempted, without Hitler's knowledge, to open peace talks with the western Allies in March 1945. When Hitler learned of this on 28 April, he dismissed Himmler from all his posts and ordered his arrest. Himmler attempted to go into hiding but was captured by British forces. He committed suicide in British custody on 23 May 1945.

Awards: Grand Cross of the Imperial Order of the Red Arrows, Sudetenland Medal, Knight grand cross of the order of the crown of Italy, Order of the Sacred Treasure, 1st Class, Rad kniežaťa Pribinu vojnovej SR 1939-45, Order of the Crown of King Zvonimir, Grand Cross of the Order of the Cross of Liberty, Golden Hitler Youth Badge with Oakleaves, German Legion of Honor, Nuremberg Party Day Badge
Education: Technical University of Munich, Wilhelmsgymnasium, Hans-Carossa-Gymnasium

Source: Wikipedia — https://en.wikipedia.org/wiki/Heinrich_Himmler$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Bundesarchiv%20Bild%20183-S72707%2C%20Heinrich%20Himmler.jpg?width=640$b$, $b$Politician, Farmer, Occultist, Laboratory technician, Gestapo employee, Holocaust perpetrator$b$, $b$Munich$b$, $b$Lüneburg$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Henry Hudson$b$, DATE '1565-01-01', DATE '1611-06-23', $b$Henry Hudson (c. 1565 – disappeared 23 June 1611) was an English sea explorer and navigator during the early 17th century, best known for his explorations of present-day Canada and parts of the Northeastern United States.

In 1607 and 1608, Hudson made two attempts on behalf of English merchants to find a rumoured Northeast Passage to Cathay via a route above the Arctic Circle. In 1609, he landed in North America on behalf of the Dutch East India Company and explored the region around the modern New York metropolitan area. Looking for a Northwest Passage to Asia on his ship Halve Maen ("Half Moon"), he sailed up the Mahicannittuk (Mohican), (a.k.a., Ka'nón:no [Mohawk] and Muhheakantuck [Lenape]), later named the Hudson River, and thereby laid the foundation for Dutch colonization of the region. His contributions to the exploration of the New World were significant and lasting. His voyages helped to establish European contact with the native peoples of North America and contributed to the development of trade and commerce.

On his final expedition, while still searching for the Northwest Passage, Hudson became the first European to see Hudson Strait and the immense Hudson Bay. In 1611, after wintering on the shore of James Bay, Hudson wanted to press on to the west, but most of his crew mutinied. The mutineers cast Hudson, his son, and six others adrift; what then happened to the Hudsons and their companions is unknown.

Awards: Person of National Historic Significance

Source: Wikipedia — https://en.wikipedia.org/wiki/Henry_Hudson$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Henry%2BHudson-posterimage.png?width=640$b$, $b$Explorer, Seafarer$b$, $b$Kingdom of England$b$, $b$James Bay$b$, 'year', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Henry III of France$b$, DATE '1551-09-19', DATE '1589-08-02', $b$Henry III of France (French: Henri III, né Alexandre Édouard; 19 September 1551 – 2 August 1589) was King of France from 1574 until his assassination in 1589 and, as Henry of Valois (Polish: Henryk Walezy; Lithuanian: Henrikas Valua), King of Poland and Grand Duke of Lithuania from 1573 to 1575. Before he came to these thrones, he was known as the Duke of Angoulême and Duke of Orléans from 1560, then as Duke of Anjou from 1566.

As the fourth son of King Henry II of France and Queen Catherine de' Medici, he was not expected to inherit the French throne and thus was a good candidate for the vacant throne of the Polish–Lithuanian Commonwealth, where he was elected monarch in 1573. During his brief rule, he refused to sign the Henrician Articles into law, which would recognise the szlachta's right to freely elect their monarch. The Henrician Articles became, nonetheless, deeply rooted in Poland's politics as all his successors accepted them. Aged 22, Henry abandoned Poland–Lithuania upon inheriting the French throne when his brother, Charles IX of France, died without issue.

France was at the time plagued by the Wars of Religion, and Henry's authority was undermined by violent political factions funded by foreign powers: the Catholic League (supported by Spain and the Pope), the Protestant Huguenots (supported by England and the Dutch) and the Malcontents (led by Henry's own brother Francis, Duke of Anjou and Alençon, a party of Catholic and Protestant aristocrats who jointly opposed the absolutist ambitions of the king). Henry III was himself a politique, arguing that only a strong and centralised yet religiously tolerant monarchy would save France from collapse.

After the death of Henry's younger brother Francis, Duke of Anjou, and when it became apparent that Henry would not father an heir, the Wars of Religion developed into a dynastic war known as the War of the Three Henrys. Under Salic Law, Henry III's heir presumptive was his distant cousin, King Henry III of Navarre, a Protestant. The Catholic League, led by Henry I, Duke of Guise, demanded the exclusion of all Protestant heirs from the line of succession. They instead championed the Catholic Charles, Cardinal of Bourbon, as Henry III's heir presumptive.

Henry had the Duke of Guise murdered in 1588 and was in turn assassinated by Jacques Clément, a Catholic League fanatic, in 1589. He was succeeded by Henry of Navarre.

Awards: Order of the Holy Spirit, Knight of the Garter

Source: Wikipedia — https://en.wikipedia.org/wiki/Henry_III_of_France$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Quesnel%20Henry%20III%20of%20France%20in%20Polish%20hat.jpg?width=640$b$, $b$Aristocrat$b$, $b$Palace of Fontainebleau$b$, $b$Saint-Cloud$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Ingvar Kamprad$b$, DATE '1926-03-30', DATE '2018-01-27', $b$Feodor Ingvar Kamprad (Swedish: [ˈɪ̌ŋːvar ˈkǎmːprad] ; 30 March 1926 – 27 January 2018) was a Swedish billionaire businessman who founded IKEA in 1943 and grew it into a multinational retail company that became the world's largest furniture seller in 2008.

Awards: International Swede of the Year, Global Economy Prize, Knight 1st class of the Order of Vasa, Order of Friendship, honorary doctorate of Lund University

Source: Wikipedia — https://en.wikipedia.org/wiki/Ingvar_Kamprad$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Ingvar%20Kamprad%20%28cropped%29.jpg?width=640$b$, $b$Businessperson, Entrepreneur, Designer$b$, $b$Pjätteryd$b$, $b$Liatorp$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Irena Sendler$b$, DATE '1910-10-20', DATE '2008-05-12', $b$Irena Stanisława Sendler (née Krzyżanowska; 15 February 1910 – 12 May 2008), operating under the nom de guerre Jolanta, was a Polish humanitarian, social worker, and nurse who served in the Polish Underground Resistance during World War II in German-occupied Warsaw. From October 1943 she was head of the children's section of Żegota, the Polish Council to Aid Jews (Polish: Rada Pomocy Żydom).

In the 1930s, Sendler conducted her social work as one of the activists connected to the Free Polish University. From 1935 to October 1943, she worked for the Department of Social Welfare and Public Health of the City of Warsaw. During the war she pursued conspiratorial activities, such as rescuing Jews, primarily as part of the network of workers and volunteers from that department, mostly women. Sendler participated, with dozens of others, in smuggling Jewish children out of the Warsaw Ghetto and then providing them with false identity documents and shelter with willing Polish families or in orphanages and other care facilities, including Catholic nun convents, saving those children from the Holocaust.

The German occupiers suspected Sendler's involvement in the Polish Underground and in October 1943 she was arrested by the Gestapo, but she managed to hide the list of the names and locations of the rescued Jewish children, preventing this information from falling into the hands of the Gestapo. Withstanding torture and imprisonment, Sendler never revealed anything about her work or the location of the saved children. She was sentenced to death but narrowly escaped on the day of her scheduled execution, after Żegota bribed German officials to obtain her release.

In post-war communist Poland, Sendler continued her social activism but also pursued a government career. In 1965, she was recognised by the State of Israel as Righteous Among the Nations. Among the many decorations Sendler received were the Gold Cross of Merit granted to her in 1946 for the saving of Jews and the Order of the White Eagle, Poland's highest honour, awarded late in Sendler's life for her wartime humanitarian efforts.

Awards: Righteous Among the Nations, Order of the White Eagle, Commander with Star of the Order of Polonia Restituta, honorary citizen of Israel, Commander of the Order of Polonia Restituta, Order of the Smile, Jan Karski Courage to Care Award, honorary citizen of Warsaw, honorary citizen of Tarczyn, Cross of Merit (Poland)
Education: University of Warsaw

Source: Wikipedia — https://en.wikipedia.org/wiki/Irena_Sendler$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Irena%20Sendlerowa%201942.jpg?width=640$b$, $b$Social worker, Clinical nurse specialist, Social activist, Resistance fighter, Administrator, Educator$b$, $b$Warsaw$b$, $b$Warsaw$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Iskandar Muda$b$, DATE '1583-01-01', DATE '1636-12-27', $b$Iskandar Muda (1583? – 27 December 1636) was the twelfth Sultan of Aceh, under whom the sultanate achieved its greatest territorial extent, holding sway as the strongest power and wealthiest state in the western Indonesian archipelago and the Strait of Malacca.

"Iskandar Muda" literally means "young Alexander," and his conquests were often compared to those of Alexander the Great. In addition to his notable conquests, during his reign, Aceh became known as an international centre of Islamic learning and trade. He was the last Sultan of Aceh who was a direct lineal male descendant of Ali Mughayat Syah, the founder of the Aceh Sultanate. Iskandar Muda's death meant that the founding dynasty of the Aceh Sultanate, the House of Meukuta Alam died out and was replaced by another dynasty.

Awards: National Hero of Indonesia

Source: Wikipedia — https://en.wikipedia.org/wiki/Iskandar_Muda$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Lukisan%20Iskandar%20muda.jpg?width=640$b$, $b$Public figure$b$, $b$Banda Aceh$b$, NULL, 'year', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$J. P. Morgan$b$, DATE '1837-04-17', DATE '1913-03-31', $b$John Pierpont  Morgan Sr. (April 17, 1837 – March 31, 1913) was an American financier and investment banker who dominated corporate finance on Wall Street throughout the Gilded Age and Progressive Era. As the head of the banking firm that ultimately became known as JPMorgan Chase & Co., he was the driving force behind a wave of industrial consolidations in the United States at the turn of the twentieth century.

Over the course of his career on Wall Street, Morgan spearheaded the formation of several prominent multinational corporations including U.S. Steel, International Harvester, and General Electric. He and his partners also held controlling interests in numerous other American businesses including Aetna, Western Union, the Pullman Car Company, and 21 railroads. His grandfather Joseph Morgan was one of the co-founders of Aetna. Through his holdings, Morgan exercised enormous influence over capital markets in the United States. During the Panic of 1907, he organized a coalition of financiers that saved the American monetary system from collapse.

As the Progressive Era's leading banker, Morgan's dedication to efficiency and modernization helped transform the shape of the American economy. Adrian Wooldridge characterized Morgan as America's "greatest banker". Morgan died in Rome, Italy, in his sleep in 1913 at the age of 75, leaving his fortune and business to his son, J. P. Morgan Jr. Biographer Ron Chernow estimated his fortune at $80 million (equivalent to $1.9 billion in 2024).

Notable works: The Morgan Library & Museum
Education: Cheshire Academy, Boston English High School, University of Göttingen

Source: Wikipedia — https://en.wikipedia.org/wiki/J._P._Morgan$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/J.P.%20Morgan.jpg?width=640$b$, $b$Entrepreneur, Art collector, Banker, Financier, Patron of the arts$b$, $b$Hartford$b$, $b$Rome$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Jeanne Calment$b$, DATE '1875-02-21', DATE '1997-08-04', $b$Jeanne Louise Calment (French: [ʒan lwiz kalmɑ̃] ; 21 February 1875 – 4 August 1997) was a French supercentenarian who is the oldest person in recorded history whose age has been verified, with a documented lifespan of 122 years and 164 days. Her longevity attracted media attention and medical studies of her health and lifestyle. Calment is the only person in history who has been verified to have reached the age of 120 years.

According to census records, Calment outlived both her daughter and her grandson. In January 1988, she was widely reported to be the oldest living person in the world. In 1995, at age 120, she was declared to be the oldest person in history with a verified date of birth.

Source: Wikipedia — https://en.wikipedia.org/wiki/Jeanne_Calment$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Jeanne%20Calment%20age%2020.jpg?width=640$b$, $b$Housewife$b$, $b$Arles$b$, $b$Arles$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$John D. Rockefeller$b$, DATE '1839-07-08', DATE '1937-05-23', $b$John Davison Rockefeller Sr. (July 8, 1839 – May 23, 1937) was an American businessman and philanthropist. He was one of the wealthiest Americans of all time and one of the richest people in history. Rockefeller was born into a large family in Upstate New York who moved several times before eventually settling in Cleveland, Ohio. He became an assistant bookkeeper at age 16 and went into several business partnerships beginning at age 20, concentrating his business on oil refining. Rockefeller founded the Standard Oil Company in 1870. He ran it until 1897 and remained its largest shareholder. In his retirement, he focused his energy and wealth on philanthropy, especially regarding education, medicine, higher education, and modernizing the Southern United States.

Rockefeller's wealth grew substantially as kerosene and gasoline became increasingly important commodities, eventually making him the richest person in the United States. By 1900, Standard Oil controlled about 90% of the nation's oil production. The company lowered production costs and expanded oil distribution through corporate and technological innovations, but it also benefited from a legal environment that enabled consolidation. Critics argue that regulatory capture played a role in facilitating its monopoly power–a view reinforced by Rockefeller's reputed remark, "Competition is a sin."

Rockefeller's company and business practices came under criticism, particularly in the writings of author Ida Tarbell.  The Supreme Court ruled in 1911 that Standard Oil must be dismantled for violation of federal antitrust laws. It was broken up into 34 separate entities, which included companies that became ExxonMobil, Chevron Corporation, and others—some of which remain among the largest companies by revenue worldwide. His personal wealth in 1913 was estimated at $900 million, which was 2.3% of the US gross domestic product (GDP). Rockefeller became the country's first billionaire on 28 September 1916.

Rockefeller spent much of the last 40 years of his life in retirement at Kykuit, his estate in Westchester County, New York, defining the structure of philanthropy, along with other key industrialists such as Andrew Carnegie. His fortune was used chiefly to create the modern systematic approach of targeted philanthropy through the creation of foundations that supported medicine, education, and scientific research. His foundations pioneered developments in medical research and were instrumental in the near-eradication of hookworm in the American South, and yellow fever in the United States. He and Carnegie gave form and impetus through their charities to the work of Abraham Flexner, who in his essay "Medical Education in America" emphatically endowed empiricism as the basis for the US medical system of the 20th century.

Rockefeller was the founder of the University of Chicago and Rockefeller University, and funded the establishment of Central Philippine University in the Philippines. He was a devout mainline Baptist Christian and supported many church-based institutions. He adhered to total abstinence from alcohol and tobacco throughout his life. For advice, he relied closely on his wife, Laura Spelman Rockefeller; they had four daughters and a son together. He was a faithful congregant of the Erie Street Baptist Mission Church, taught Sunday school, and served as a trustee, clerk, and occasional janitor. Religion was a guiding force throughout his life, and he believed it to be the source of his success. Rockefeller was also considered a supporter of capitalism based on a perspective of social Darwinism, and he was quoted often as saying, "The growth of a large business is merely a survival of the fittest."

Notable works: Riverside Church, Kykuit
Awards: Dr. Nathan Davis Award for United States Senators
Education: Chancellor University, Bryant & Stratton College

Source: Wikipedia — https://en.wikipedia.org/wiki/John_D._Rockefeller$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/John-D-Rockefeller-sen.jpg?width=640$b$, $b$Entrepreneur, Accountant, Banker, Philanthropist$b$, $b$Richford$b$, $b$Ormond Beach$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Lee Harvey Oswald$b$, DATE '1939-10-18', DATE '1963-11-24', $b$Lee Harvey Oswald (October 18, 1939 – November 24, 1963) was a U.S. Marine veteran who assassinated John F. Kennedy, the 35th president of the United States, on November 22, 1963.

Oswald was placed in juvenile detention at age twelve for truancy, during which he was assessed by a psychiatrist as "emotionally disturbed" because of the lack of normal family life. He attended twelve schools in his youth, quitting repeatedly, and at age seventeen he joined the Marines, where he was court-martialed twice and jailed. He also became interested in Marxism from a young age. In 1959, he was discharged from active duty into the Marine Corps Reserve, then flew to Europe and defected to the Soviet Union. He lived in Minsk, married a Russian woman named Marina, and had a daughter. In June 1962, he returned to the United States with his wife, and eventually settled in Dallas, Texas, where their second daughter was born. Oswald still continued to express support for the Soviet Union and  Cuban leader Fidel Castro.

Oswald shot and killed Kennedy on November 22, 1963, from a sixth-floor window of the Texas School Book Depository as Kennedy traveled by motorcade through Dealey Plaza in Dallas. About 45 minutes after shooting Kennedy, Oswald murdered a Dallas police officer, J. D. Tippit, on a suburban street. He then slipped into a movie theater, where he was arrested for Tippit's murder. Oswald was charged with the assassination of Kennedy, but he denied responsibility for the killing, claiming that he was a patsy. Two days later, Oswald himself was murdered by a local nightclub owner, Jack Ruby, on live television in the basement of Dallas Police Headquarters.

In September 1964, the Warren Commission concluded that Oswald and Ruby had each acted alone. This conclusion, though controversial, was supported by investigations from the Dallas Police Department, the Federal Bureau of Investigation (FBI), the United States Secret Service, and the House Select Committee on Assassinations (HSCA). Despite forensic, ballistic, and eyewitness accounts supporting the official findings, public-opinion polls have shown that most Americans still do not believe that the official version tells the whole truth of the events, and the assassination has spawned numerous conspiracy theories.

Education: Warren Easton High School, Arlington Heights High School

Source: Wikipedia — https://en.wikipedia.org/wiki/Lee_Harvey_Oswald$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Lee%20Harvey%20Oswald%201963.jpg?width=640$b$, $b$Laborer$b$, $b$New Orleans$b$, $b$Parkland Memorial Hospital$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Marie Antoinette$b$, DATE '1755-11-02', DATE '1793-10-16', $b$Marie Antoinette (Maria Antonia Josepha Johanna; 2 November 1755 – 16 October 1793) was Queen of France as the wife of Louis XVI from 10 May 1774 until the abolition of the French monarchy in 1792 during the French Revolution.

Born in November 1755 at the Hofburg in Vienna, Marie Antoinette was the fifteenth child and youngest daughter of Emperor Francis I and Empress Maria Theresa. By right of her birth, she was an Austrian archduchess of the House of Habsburg-Lorraine. In 1769, Marie Antoinette was betrothed to Louis-Auguste, Dauphin of France, in order to strengthen the Franco–Austrian alliance. The two were married in 1770, thus making Marie Antoinette dauphine of France at the age of fourteen. In 1774, Louis-Auguste inherited the French throne as Louis XVI, becoming king of France, and Marie Antoinette queen consort.

As queen, Marie Antoinette became increasingly a target of criticism by opponents of the domestic and foreign policies of Louis XVI and those opposed to the monarchy in general. The French libelles accused her of being profligate, promiscuous, having illegitimate children, and harboring sympathies for France's perceived enemies, including her native Austria. She was falsely accused of defrauding the Crown's jewelers in the Affair of the Diamond Necklace, but the accusations still damaged her reputation. During the French Revolution, she became known as Madame Déficit because the country's financial crisis was blamed on her lavish spending and her opposition to social and financial reforms proposed by Anne Robert Jacques Turgot and Jacques Necker.

Several events were linked to Marie Antoinette during the Revolution after the government placed the royal family under house arrest in the Tuileries Palace in October 1789. The June 1791 attempted flight to Varennes and her role in the War of the First Coalition were immensely damaging to her image among French citizens. On 10 August 1792, the attack on the Tuileries forced the royal family to take refuge at the Legislative Assembly, and they were imprisoned in the Temple Prison on 13 August 1792. On 21 September 1792, France was declared a republic and the monarchy was abolished. Louis XVI was executed by guillotine on 21 January 1793 and Marie Antoinette moved to the Conciergerie.  Her trial began on 14 October 1793; two days later, she was convicted by the Revolutionary Tribunal of high treason and executed by guillotine on 16 October 1793 at the Place de la Révolution.

Awards: Order of the Starry Cross

Source: Wikipedia — https://en.wikipedia.org/wiki/Marie_Antoinette$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Louise%20Elisabeth%20Vig%C3%A9e-Lebrun%20-%20Marie-Antoinette%20dit%20%C2%AB%20%C3%A0%20la%20Rose%20%C2%BB%20-%20Google%20Art%20Project.jpg?width=640$b$, $b$Aristocrat, Consort$b$, $b$Hofburg Palace$b$, $b$place de la Concorde$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Martin Bormann$b$, DATE '1900-06-17', DATE '1945-05-02', $b$Martin Ludwig Bormann (17 June 1900 – 2 May 1945) was a German Nazi Party official, head of the Nazi Party Chancellery, and private secretary to Adolf Hitler. Bormann gained immense power by using his position as Hitler's private secretary to control the flow of information and access to Hitler. He used his position to create an extensive bureaucracy and involve himself as much as possible in decision-making.

Born in Wegeleben, Bormann joined a paramilitary Freikorps organisation in 1922 while working as manager of a large estate. He served nearly a year in prison as an accomplice to his friend Rudolf Höss (later commandant of Auschwitz concentration camp) in the murder of school teacher Walther Kadow. Bormann joined the Nazi Party in 1927 and the Schutzstaffel (SS) in 1937. He initially worked in the party's insurance service, and transferred in July 1933 to the office of Deputy Führer Rudolf Hess, where he served as chief of staff.

Bormann gained acceptance into Hitler's inner circle and accompanied him everywhere, providing briefings and summaries of events and requests. He was appointed Hitler's personal secretary on 12 April 1943. After Hess's solo flight to Britain on 10 May 1941 to seek peace negotiations with the British government, Bormann assumed Hess's former duties, with the title of Head of the Parteikanzlei (Party Chancellery). He had final approval over civil service appointments, and helped review and approve legislation. He was a leading proponent of reducing the influence of Christian churches and favoured harsh treatment of Jews and Slavs in the areas conquered by Germany during World War II.

Bormann returned with Hitler to the Führerbunker in Berlin on 16 January 1945 as the Red Army approached the city. After Hitler committed suicide, Bormann and others attempted to flee Berlin on 2 May to avoid capture by the Soviets. Bormann likely committed suicide on a bridge near Lehrter station. His body was buried nearby on 8 May 1945, but remained unfound for decades. The missing Bormann was tried in absentia by the International Military Tribunal in the Nuremberg trials of 1945 and 1946, where he was convicted of war crimes and crimes against humanity and sentenced to death by hanging. Bormann's body was found in 1972 and confirmed as his in 1973; the identification was reaffirmed in 1998 by DNA tests.

Awards: Golden Party Badge, Blood Order, Nazi Party Long Service Award, Reichsführer-SS, Honour Chevron for the Old Guard, SS-Ehrenring

Source: Wikipedia — https://en.wikipedia.org/wiki/Martin_Bormann$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Bundesarchiv%20Bild%20183-R14128A%2C%20Martin%20Bormann.jpg?width=640$b$, $b$Politician, Farmer, Nazi, Soldier, Holocaust perpetrator$b$, $b$Halberstadt$b$, $b$Berlin$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Mikhail Kalashnikov$b$, DATE '1919-11-10', DATE '2013-12-23', $b$Mikhail Timofeyevich Kalashnikov (10 November 1919 – 23 December 2013) was a Soviet and Russian lieutenant general, inventor, military engineer, writer, and small arms designer. He is most famous for developing the AK-47 assault rifle and its improvements, the AKM and AK-74, as well as the RPK light machine gun and PK machine gun.

Kalashnikov was, according to himself, a self-taught tinkerer who combined innate mechanical skills with the study of weaponry to design arms that achieved battlefield ubiquity. Even though Kalashnikov felt sorrow at the weapons' uncontrolled distribution, he took pride in his inventions and in their reputation for reliability, emphasizing that his rifle is "a weapon of defense" and "not a weapon for offense".

Notable works: The Gun that Changed the World, The Arms Designer Notes, From A Stranger's Doorstep To The Kremlin Gates, A Biography Of Mikhail Kalashnikov The AK Man, I Walked Along the Same Road as You Did, Fate trajectory, Things that are useful are simple, AK-74, AKM
Awards: State Stalin Prize, 1st degree, Order of Lenin, Order of the Red Star, Order of the Red Banner of Labour, Order of the October Revolution, Order of Friendship of Peoples, Order "For Merit to the Fatherland", 2nd class, Order of St. Andrew the Apostle the First-Called, Order of Honor, Dostyk Order of grade I
Education: Voroniha village secondary school

Source: Wikipedia — https://en.wikipedia.org/wiki/Mikhail_Kalashnikov$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Kalashnikov%20Mikhail%20%281%29.jpg?width=640$b$, $b$Design engineer, Tankman, Inventor, Writer, Military personnel, Politician$b$, $b$Kurya$b$, $b$Izhevsk$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Oskar Schindler$b$, DATE '1908-04-28', DATE '1974-10-09', $b$Oskar Schindler (German: [ˈɔskaʁ ˈʃɪndlɐ] ; 28 April 1908 – 9 October 1974) was a German industrialist and humanitarian who is credited with saving the lives of 1,200 Jews during the Holocaust by employing them in his enamelware and ammunitions factories in German-occupied Poland and the Protectorate of Bohemia and Moravia. He is the subject of the 1982 novel Schindler's Ark and its 1993 film adaptation, Schindler's List.

Schindler grew up in Zwittau, Moravia, and worked in several trades until he joined the Abwehr, the military intelligence service of Nazi Germany, in 1936. Before the beginning of the German occupation of Czechoslovakia in 1938, he collected information on railways and troop movements for the German government. He was arrested for espionage by the Czechoslovak government but was released under the terms of the Munich Agreement that year. He continued to collect information for the Nazis, working in Poland in 1939 before the invasion of Poland at the start of the Second World War. He joined the Nazi Party in 1939. That same year, he acquired an enamelware factory in Kraków, Poland, which employed at its peak in 1944 about 1,750 workers, of whom 1,000 were Jews. His Abwehr connections helped him protect his Jewish workers from deportation and death in the Nazi concentration camps. As time went on, he had to give Nazi officials ever larger bribes and gifts of luxury items obtainable only on the black market to keep his workers safe.

By July 1944, Germany was losing the war; the Schutzstaffel (SS) began closing down the easternmost concentration camps and deporting the remaining prisoners westward. Many were murdered at the Auschwitz concentration camp and the Gross-Rosen concentration camp. Schindler convinced Amon Göth, SS-Hauptsturmführer commandant of the nearby Kraków-Płaszów concentration camp, to allow him to move his factory to Brněnec (German: Brünnlitz, Czech: Brněnec)  in the Protectorate of Bohemia and Moravia, thus sparing his workers from almost certain death in the gas chambers of Auschwitz. Using names provided by a Jewish Ghetto Police officer named Marcel Goldberg, Göth's secretary Mietek Pemper compiled and typed the list of 1,200 Jews who travelled to Brünnlitz in October 1944. Schindler continued to bribe SS officials to prevent his workers' execution until the end of the Second World War in Europe in May 1945, by which time he had spent his entire fortune on bribes and black market purchases of supplies for his workers.

Schindler moved to West Germany after the war, where he was supported financially by Jewish relief organisations. After receiving a partial reimbursement for his wartime expenses, he moved with his wife, Emilie, to Argentina, where they took up farming. When they went bankrupt in 1958, Schindler left his wife and returned to Germany, where he failed at several business ventures and relied on financial support from Schindlerjuden ("Schindler Jews")—the people whose lives he had saved during the war. He died on 9 October 1974 in Hildesheim, Germany, and was buried in Jerusalem on Mount Zion, the only former member of the Nazi Party to be honoured in this way. Oskar and Emilie Schindler were named Righteous Among the Nations by Yad Vashem in 1993.

Awards: Righteous Among the Nations, Order of St. Sylvester, Officer's Cross of the Order of Merit of the Federal Republic of Germany, Jan Karski Courage to Care Award, Order of St. Gregory the Great

Source: Wikipedia — https://en.wikipedia.org/wiki/Oskar_Schindler$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Schindler%2C%20Oskar.jpg?width=640$b$, $b$Entrepreneur, Industrialist, Salesperson, Businessperson, Resistance fighter, Factory owner$b$, $b$Svitavy$b$, $b$Hildesheim$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Pedro Álvares Cabral$b$, DATE '1467-01-01', DATE '1520-01-01', $b$Pedro Álvares Cabral (European Portuguese: [ˈpeðɾu ˈalvɐɾɨʃ kɐˈβɾal], Brazilian Portuguese: [ˈpedɾu ˈawvɐɾɨʃ, ˈawvɐɾɨs kɐˈbɾal]; born Pedro Álvares de Gouveia; c. 1467 or 1468 – c. 1520) was a Portuguese nobleman, colonizer, military commander, navigator and explorer regarded as the European discoverer of Brazil. He was the first human in history to ever be on four continents, uniting all of them in his famous voyage of 1500, where he also conducted the first substantial exploration of the northeast coast of South America and claimed it for Portugal. While details of Cabral's early life remain unclear, it is known that he came from a minor noble family and received a good education. He was appointed to head an expedition to India in 1500, following Vasco da Gama's newly opened route around Africa. The undertaking had the aim of returning with valuable spices and of establishing trade relations in India—bypassing the monopoly on the spice trade then in the hands of Arab, Turkish and Italian merchants. Although the previous expedition of Vasco da Gama to India, on its sea route, had recorded signs of land west of the southern Atlantic Ocean (in 1497), Cabral led the first known expedition to have touched four continents: Europe, Africa, South America, and Asia.

His fleet of 13 ships sailed far into the western Atlantic Ocean, perhaps intentionally, and made landfall (April 1500) on what he initially assumed to be a large island. As the new land was within the Portuguese sphere according to the 1494 Treaty of Tordesillas, Cabral claimed it for the Portuguese Crown. He explored the coast, realizing that the large land mass was probably a continent, and dispatched a ship to notify King Manuel I of the new territory. The continent was South America, and the land he had claimed for Portugal later came to be known as Brazil. The fleet reprovisioned and then turned eastward to resume the journey to India.

A storm in the southern Atlantic caused the loss of several ships, and the six remaining ships eventually rendezvoused in the Mozambique Channel before proceeding to Calicut in India. Cabral was originally successful in negotiating trading rights, but Arab merchants saw Portugal's venture as a threat to their monopoly and stirred up an attack by both Muslims and Hindus on the Portuguese entrepôt. The Portuguese sustained many casualties and their facilities were destroyed. Cabral took vengeance by looting and burning the Arab fleet and then bombarded the city in retaliation for its ruler having failed to explain the unexpected attack. From Calicut the expedition sailed to the Kingdom of Cochin, another Indian city-state, where Cabral befriended its ruler and loaded his ships with coveted spices before returning to Europe. Despite the loss of human lives and ships, Cabral's voyage was deemed a success upon his return to Portugal. The extraordinary profits resulting from the sale of the spices bolstered the Portuguese Crown's finances and helped lay the foundation of a Portuguese Empire that would stretch from the Americas to the Far East.

Awards: Knight of the Military Order of Christ

Source: Wikipedia — https://en.wikipedia.org/wiki/Pedro_%C3%81lvares_Cabral$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Pedro%20%C3%81lvares%20Cabral%20-%20steel%20engraving%20by%20American%20Bank%20Note%20Company.jpg?width=640$b$, $b$Explorer, Seafarer$b$, $b$Belmonte$b$, $b$Santarém$b$, 'year', 'year');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Reinhard Heydrich$b$, DATE '1904-03-07', DATE '1942-06-04', $b$Reinhard Tristan Eugen Heydrich (; German: [ˈʁaɪnhaʁt ˈtʁɪstan ˈʔɔʏɡn̩ ˈhaɪdʁɪç] ; 7 March 1904 – 4 June 1942) was a high-ranking SS and police official in Nazi Germany as well as one of the principal architects of the Holocaust. He held the rank of SS-Obergruppenführer und General der Polizei. Many historians regard Heydrich as one of the most sinister figures within the Nazi regime. Adolf Hitler described him as "the man with the iron heart".

Beginning in September 1939, Heydrich was chief of the Reich Security Main Office (including the Gestapo, Kripo, and SD). He was also Stellvertretender Reichsprotektor (Deputy Reich-Protector) of Bohemia and Moravia. He served as president of the International Criminal Police Commission (ICPC, now known as Interpol) and chaired the January 1942 Wannsee Conference which formalised plans for the "Final Solution to the Jewish question"—the deportation and genocide of all Jews in German-occupied Europe.

Heydrich was the founding head of the Sicherheitsdienst (Security Service, SD), an intelligence organisation charged with seeking out and neutralising resistance to the Nazi Party via arrests, deportations, and murders. He helped organise Kristallnacht, a series of coordinated attacks against Jews throughout Nazi Germany and parts of Austria on 9–10 November 1938. The attacks were carried out by SA stormtroopers and civilians and presaged the Holocaust. Upon his arrival in Prague, Heydrich sought to eliminate opposition to the Nazi occupation by suppressing Czech culture and deporting and executing members of the Czech resistance. He was directly responsible for the Einsatzgruppen, the special task forces that travelled in the wake of the German armies and murdered more than two million people by mass shooting and gassing including 1.3 million Jews.

Heydrich was mortally wounded in Prague on 27 May 1942 as a result of Operation Anthropoid. He was ambushed by a team of Czech and Slovak soldiers who had been sent by the Czechoslovak government-in-exile to kill him; the team was trained by the British Special Operations Executive. Heydrich died from sepsis caused by his injuries on 4 June 1942. Nazi intelligence falsely linked the Czech and Slovak soldiers and resistance partisans to the villages of Lidice and Ležáky. Both villages were razed; the men and boys aged 14 and above were shot and most of the women and children were deported and murdered in Nazi concentration camps.

Awards: German Order, Golden Party Badge, Order of the Rising Sun, 1st class, Blood Order, Wound Badge (1939) in Gold, Iron Cross, Order of the German Eagle, Anschluss Medal, Sudetenland Medal, Memel Medal
Education: Technical University of Munich, Hans-Dietrich-Genscher-Gymnasium

Source: Wikipedia — https://en.wikipedia.org/wiki/Reinhard_Heydrich$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Bundesarchiv%20Bild%20146-1969-054-16%2C%20Reinhard%20Heydrich.jpg?width=640$b$, $b$Politician, Military personnel, Fencer, Aircraft pilot, Soldier, Gestapo employee$b$, $b$Halle (Saale)$b$, $b$Prague$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Ruth Bader Ginsburg$b$, DATE '1933-03-15', DATE '2020-09-18', $b$Joan Ruth Bader Ginsburg ( BAY-dər GHINZ-burg; née Bader; March 15, 1933 – September 18, 2020) was an American lawyer and jurist who served as an associate justice of the Supreme Court of the United States from 1993 until her death in 2020. She was nominated by President Bill Clinton to replace retiring justice Byron White, and at the time was viewed as a moderate consensus-builder. Ginsburg was the first Jewish woman and the second woman to serve on the Court, after Sandra Day O'Connor. During her tenure, Ginsburg authored the majority opinions in cases such as United States v. Virginia (1996), Olmstead v. L.C. (1999), Friends of the Earth, Inc. v. Laidlaw Environmental Services, Inc. (2000), and City of Sherrill v. Oneida Indian Nation of New York (2005). Later in her tenure, Ginsburg received attention for passionate dissents that reflected liberal views of the law.

Ginsburg was born and grew up in Brooklyn, New York. Just over a year later her older sister and only sibling, Marilyn, died of meningitis at the age of six. Her mother died shortly before she graduated from high school. She earned her bachelor's degree at Cornell University and married Martin D. Ginsburg, becoming a mother before starting law school at Harvard, where she was one of the few women in her class. Ginsburg transferred to Columbia Law School, where she graduated joint first in her class. During the early 1960s she worked with the Columbia Law School Project on International Procedure, learned Swedish, and co-authored a book with Swedish jurist Anders Bruzelius; her work in Sweden profoundly influenced her thinking on gender equality. She then became a professor at Rutgers Law School and Columbia Law School, teaching civil procedure as one of the few women in her field and the first female member of the law faculty at Columbia to attain tenure.

Ginsburg spent much of her legal career as an advocate for gender equality and women's rights, winning many arguments before the Supreme Court. She advocated as a volunteer attorney for the American Civil Liberties Union and was a member of its board of directors and one of its general counsel in the 1970s. In 1980, President Jimmy Carter appointed her to the U.S. Court of Appeals for the District of Columbia Circuit, where she served until her appointment to the Supreme Court in 1993. Between O'Connor's retirement in 2006 and the appointment of Sonia Sotomayor in 2009, she was the only female justice on the Supreme Court. During that time, Ginsburg became more forceful with her dissents, such as with Ledbetter v. Goodyear Tire & Rubber Co. (2007).

Despite two bouts with cancer and public pleas from liberal law scholars, she decided not to retire in 2013 or 2014 when President Barack Obama and a Democratic-controlled Senate could appoint and confirm her successor. Ginsburg died at her home in Washington, D.C., on September 18, 2020, at the age of 87, from complications of metastatic pancreatic cancer. The vacancy created by her death was filled 39 days later by Amy Coney Barrett. The result was one of three major rightward shifts in the Court since 1953, following the appointment of Clarence Thomas to replace Thurgood Marshall in 1991 and the appointment of Warren Burger to replace Earl Warren in 1969.

Awards: Brandeis Medal, National Women's Hall of Fame, honorary doctor of the Ohio State University, Fellow of the American Academy of Arts and Sciences, honorary doctor of Harvard University, Forbes list of The World's 100 Most Powerful Women, Time 100, honorary doctorate from Princeton University, Four Freedoms Award – Freedom Medal, Jefferson Awards for Public Service
Education: Cornell University, Harvard Law School, Columbia Law School, James Madison High School

Source: Wikipedia — https://en.wikipedia.org/wiki/Ruth_Bader_Ginsburg$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Ruth%20Bader%20Ginsburg%20official%20SCOTUS%20portrait%20%28cropped%29.jpg?width=640$b$, $b$Judge, Lawyer, Jurist, Member of the Constitutional Court of Austria$b$, $b$Brooklyn$b$, $b$Washington, D.C.$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Sojourner Truth$b$, DATE '1797-01-01', DATE '1883-11-26', $b$Sojourner Truth (; born Isabella Bomefree; c. 1797 – November 26, 1883) was an American abolitionist and activist for African-American civil rights, women's rights, and alcohol temperance. Truth was born into slavery in Swartekill, New York, but escaped with her infant daughter to freedom in 1826. After going to court to recover her son in 1828, she became the first Black woman to win such a case against a white man.

Bomefree gave herself the name Sojourner Truth in 1843 after she became convinced that God had called her to leave the city and go into the countryside "testifying to the hope that was in her." Her best-known speech was delivered extemporaneously, in 1851, at the Ohio Women's Convention in Akron, Ohio. The speech became widely known during the Civil War by the title "Ain't I a Woman?", a variation of the original speech that was published in 1863 as being spoken in a stereotypical Black dialect, then more commonly spoken in the South. Sojourner Truth, however, grew up speaking Dutch as her first language.

During the Civil War, Truth helped recruit Black men into the Union army; after the war, she tried unsuccessfully to secure land grants from the federal government for formerly enslaved people (summarized as the promise of "forty acres and a mule"). She continued to fight on behalf of women and African Americans until her death. As her biographer Nell Irvin Painter wrote, "At a time when most Americans thought of slaves as male and women as white, Truth embodied a fact that still bears repeating: Among the blacks are women; among the women, there are blacks."

A memorial bust of Truth was unveiled in 2009 in Emancipation Hall in the U.S. Capitol Visitor Center. She is the first African American woman to have a statue in the Capitol building. In 2014, Truth was included in Smithsonian magazine's list of the "100 Most Significant Americans of All Time".

Awards: National Women's Hall of Fame, Michigan Women's Hall of Fame

Source: Wikipedia — https://en.wikipedia.org/wiki/Sojourner_Truth$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Sojourner%20Truth%20photograph.jpg?width=640$b$, $b$Writer, Abolitionist, Women's rights activist, Suffragist, Religious leader, Slave$b$, $b$Hurley$b$, $b$Battle Creek$b$, 'year', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Sophie Scholl$b$, DATE '1921-05-09', DATE '1943-02-22', $b$Sophia Magdalena Scholl (9 May 1921 – 22 February 1943) was a German student and anti-Nazi political activist, active in the White Rose non-violent resistance group in Nazi Germany.

Raised in a politically engaged family, Scholl initially joined the Bund Deutscher Mädel, the female branch of the Hitler Youth, but later became critical of the Nazi regime. Influenced by philosophy, theology, and the writings of Theodor Haecker, she became involved in passive resistance efforts alongside her brother, Hans, and fellow students. The White Rose distributed leaflets calling for opposition to the Nazi state, citing ethical and philosophical arguments against its policies. In February 1943, after being caught distributing leaflets at the Ludwig-Maximilians-Universität München, she and her brother Hans were arrested by the Gestapo, interrogated, and convicted of high treason in a show trial presided over by Roland Freisler. They were sentenced to death and executed by guillotine.

After her death, copies of the final White Rose leaflet were air-dropped over Germany by the Allies. In the decades following her death, numerous schools, streets, and memorials have been named in her and her brother's honor for their role in anti-Nazi resistance. Her story has been depicted in several films, books, and other media, including the Oscar nominated film Sophie Scholl – The Final Days.

Education: Ludwig-Maximilians-Universität München

Source: Wikipedia — https://en.wikipedia.org/wiki/Sophie_Scholl$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Gestapo%20photo%20of%20Sophie%20Scholl%20taken%20after%20her%20capture%20on%20February%2018%2C%201943-2.jpg?width=640$b$, $b$University student, Resistance fighter, Student$b$, $b$Forchtenberg$b$, $b$Munich Prison$b$, 'day', 'day');
INSERT INTO people (id, name, birth_date, death_date, bio, lang, photo_url, occupation, birth_place, death_place, birth_precision, death_precision) VALUES (gen_random_uuid(), $b$Ted Bundy$b$, DATE '1946-11-24', DATE '1989-01-24', $b$Theodore Robert Bundy (né Cowell; November 24, 1946 – January 24, 1989), also known by the alias Chris Hagen, was an American serial killer who kidnapped, raped and murdered dozens of young women and girls between 1974 and 1978. His modus operandi typically consisted of convincing his target that he was in need of assistance or duping them into believing he was an authority figure. He would then lure his victim to his vehicle, at which point he would bludgeon them unconscious, then restrain them with handcuffs before driving them to a remote location to be sexually assaulted and killed.

Bundy killed his first definitively-known victim in February 1974 in Washington State, and his later crimes stretched to Oregon, Colorado, Utah, Idaho and Florida. He frequently revisited the bodies of his victims, grooming and performing sex acts on the corpses until decomposition and destruction by wild animals made further interactions impossible. Along with the murders,  Bundy was also a prolific burglar, and on a few occasions he broke into homes at night and bludgeoned, maimed, strangled and sexually assaulted the occupants in their sleep.

In 1975, Bundy was arrested and jailed in Utah for aggravated kidnapping and attempted criminal assault. He then became a suspect in a progressively longer list of unsolved homicides in several states. Facing murder charges in Colorado, Bundy engineered two dramatic escapes and committed further assaults in Florida, including three murders, before being recaptured in 1978. For the Florida homicides, he received three death sentences in two trials. Bundy was executed in the electric chair at Florida State Prison, in Bradford County, on January 24, 1989.

Biographer Ann Rule characterized Bundy as "a sadistic sociopath who took pleasure from another human's pain and the control he had over his victims, to the point of death and even after." He once described himself as "the most cold-hearted son of a bitch you'll ever meet", a statement with which attorney Polly Nelson, a member of his last defense team, agreed. She wrote that "Ted was the very definition of heartless evil."

Education: University of Puget Sound, University of Utah, Temple University, Woodrow Wilson High School

Source: Wikipedia — https://en.wikipedia.org/wiki/Ted_Bundy$b$, 'en', $b$https://commons.wikimedia.org/wiki/Special:FilePath/Ted%20Bundy%20headshot.jpg?width=640$b$, $b$Psychologist, Serial killer$b$, $b$Burlington$b$, $b$Florida State Prison$b$, 'day', 'day');
