-- Notable Indian actors and singers who have passed away.
-- Biographies are concise summaries; source links point to English Wikipedia.
-- Existing name/date pairs are skipped so earlier imports are not duplicated.
INSERT INTO people (
    id, name, birth_date, death_date, bio, lang, photo_url, occupation,
    birth_place, death_place, birth_precision, death_precision
)
SELECT
    gen_random_uuid(), v.name, v.birth_date, v.death_date,
    v.bio || E'\n\nSource: Wikipedia — https://en.wikipedia.org/wiki/' || v.source_slug,
    'en', NULL, v.occupation, v.birth_place, v.death_place, 'day', 'day'
FROM (VALUES
    ('Ashok Kumar', DATE '1911-10-13', DATE '2001-12-10',
        'Indian actor and producer who became one of Hindi cinema''s earliest major stars, with a career spanning more than six decades.',
        'Actor, Producer', 'Bhagalpur, Bihar', 'Mumbai, Maharashtra', 'Ashok_Kumar'),
    ('Raj Kapoor', DATE '1924-12-14', DATE '1988-06-02',
        'Indian actor, film director and producer known for starring in and directing classics including Awaara and Shree 420.',
        'Actor, Director, Producer', 'Peshawar', 'New Delhi', 'Raj_Kapoor'),
    ('Dilip Kumar', DATE '1922-12-11', DATE '2021-07-07',
        'Indian actor celebrated for his performances in Hindi cinema and widely regarded as one of the country''s most influential actors.',
        'Actor', 'Peshawar', 'Mumbai, Maharashtra', 'Dilip_Kumar'),
    ('Dev Anand', DATE '1923-09-26', DATE '2011-12-03',
        'Indian actor, director and producer, remembered as a leading star of Hindi cinema and for films such as Guide and Jewel Thief.',
        'Actor, Director, Producer', 'Shakargarh', 'London', 'Dev_Anand'),
    ('Guru Dutt', DATE '1925-07-09', DATE '1964-10-10',
        'Indian actor and filmmaker whose films Pyaasa and Kaagaz Ke Phool are considered landmarks of Hindi cinema.',
        'Actor, Director, Producer', 'Bangalore, Karnataka', 'Mumbai, Maharashtra', 'Guru_Dutt'),
    ('Madhubala', DATE '1933-02-14', DATE '1969-02-23',
        'Indian actress and one of Hindi cinema''s most celebrated stars, best known internationally for her role in Mughal-e-Azam.',
        'Actor', 'Delhi', 'Mumbai, Maharashtra', 'Madhubala'),
    ('Meena Kumari', DATE '1933-08-01', DATE '1972-03-31',
        'Indian actress and poet acclaimed for her performances in Hindi films including Sahib Bibi Aur Ghulam and Pakeezah.',
        'Actor, Poet', 'Mumbai, Maharashtra', 'Mumbai, Maharashtra', 'Meena_Kumari'),
    ('Nargis', DATE '1929-06-01', DATE '1981-05-03',
        'Indian actress known for films including Mother India; she received the Padma Shri and was nominated to the Rajya Sabha.',
        'Actor, Politician', 'Calcutta, Bengal Presidency', 'Mumbai, Maharashtra', 'Nargis_(actress)'),
    ('Prithviraj Kapoor', DATE '1906-11-03', DATE '1972-05-29',
        'Indian actor and theatre producer who founded the travelling Prithvi Theatre and became a prominent figure in Hindi cinema.',
        'Actor, Theatre artist', 'Samundri', 'Mumbai, Maharashtra', 'Prithviraj_Kapoor'),
    ('Balraj Sahni', DATE '1913-05-01', DATE '1973-04-13',
        'Indian actor and writer, acclaimed for socially engaged performances in films such as Do Bigha Zamin and Garam Hawa.',
        'Actor, Writer', 'Rawalpindi', 'Mumbai, Maharashtra', 'Balraj_Sahni'),
    ('Shammi Kapoor', DATE '1931-10-21', DATE '2011-08-14',
        'Indian actor known for his energetic screen persona and popular Hindi films including Junglee and Kashmir Ki Kali.',
        'Actor', 'Bombay, Bombay Presidency', 'Mumbai, Maharashtra', 'Shammi_Kapoor'),
    ('Sanjeev Kumar', DATE '1938-07-09', DATE '1985-11-06',
        'Indian actor acclaimed for versatile performances in Hindi films, including Koshish, Sholay and Angoor.',
        'Actor', 'Surat, Gujarat', 'Mumbai, Maharashtra', 'Sanjeev_Kumar'),
    ('Amjad Khan', DATE '1940-11-12', DATE '1992-07-27',
        'Indian actor and director widely remembered for playing Gabbar Singh in the Hindi film Sholay.',
        'Actor, Director', 'Hyderabad, Hyderabad State', 'Mumbai, Maharashtra', 'Amjad_Khan_(actor)'),
    ('Vinod Khanna', DATE '1946-10-06', DATE '2017-04-27',
        'Indian actor and politician who starred in Hindi films and later served as a member of parliament and Union minister.',
        'Actor, Politician', 'Peshawar', 'Mumbai, Maharashtra', 'Vinod_Khanna'),
    ('Nutan', DATE '1936-06-04', DATE '1991-02-21',
        'Indian actress noted for acclaimed roles in Hindi films including Seema, Sujata and Bandini.',
        'Actor', 'Bombay, Bombay Presidency', 'Mumbai, Maharashtra', 'Nutan'),
    ('Om Puri', DATE '1950-10-18', DATE '2017-01-06',
        'Indian actor who appeared in Indian and international cinema, with acclaimed performances in Ardh Satya and Aakrosh.',
        'Actor', 'Ambala, Punjab', 'Mumbai, Maharashtra', 'Om_Puri'),
    ('Irrfan Khan', DATE '1967-01-07', DATE '2020-04-29',
        'Indian actor known for acclaimed work in Indian and international films, including The Lunchbox, Piku and Life of Pi.',
        'Actor', 'Tonk, Rajasthan', 'Mumbai, Maharashtra', 'Irrfan_Khan'),
    ('Rishi Kapoor', DATE '1952-09-04', DATE '2020-04-30',
        'Indian actor and film director whose career included Bobby, Amar Akbar Anthony and many later character roles.',
        'Actor, Director', 'Bombay, Bombay State', 'Mumbai, Maharashtra', 'Rishi_Kapoor'),
    ('Sridevi', DATE '1963-08-13', DATE '2018-02-24',
        'Indian actress who starred in Tamil, Telugu, Hindi and other Indian-language films and became one of Indian cinema''s leading stars.',
        'Actor', 'Meenampatti, Tamil Nadu', 'Dubai, United Arab Emirates', 'Sridevi'),
    ('Smita Patil', DATE '1955-10-17', DATE '1986-12-13',
        'Indian actress known for parallel-cinema performances in films including Bhumika, Manthan and Chakra.',
        'Actor', 'Pune, Maharashtra', 'Mumbai, Maharashtra', 'Smita_Patil'),
    ('Uttam Kumar', DATE '1926-09-03', DATE '1980-07-24',
        'Indian actor and producer regarded as one of the most influential stars of Bengali cinema; he also appeared in Hindi films.',
        'Actor, Producer', 'Calcutta, Bengal Presidency', 'Kolkata, West Bengal', 'Uttam_Kumar'),
    ('Sivaji Ganesan', DATE '1928-10-01', DATE '2001-07-21',
        'Indian actor and producer acclaimed for his work in Tamil cinema and honoured with the Dadasaheb Phalke Award.',
        'Actor, Producer', 'Villupuram, Madras Presidency', 'Chennai, Tamil Nadu', 'Sivaji_Ganesan'),
    ('Rajkumar', DATE '1929-04-24', DATE '2006-04-12',
        'Indian actor and playback singer who became one of the defining stars of Kannada-language cinema.',
        'Actor, Singer', 'Gajanur, Madras Presidency', 'Bangalore, Karnataka', 'Rajkumar_(actor)'),
    ('Prem Nazir', DATE '1926-04-07', DATE '1989-01-16',
        'Indian actor who became one of Malayalam cinema''s most prolific leading performers.',
        'Actor', 'Chirayinkeezhu, Travancore', 'Chennai, Tamil Nadu', 'Prem_Nazir'),
    ('Suchitra Sen', DATE '1931-04-06', DATE '2014-01-17',
        'Indian actress celebrated for Bengali cinema and remembered internationally for her leading role in the film Devdas.',
        'Actor', 'Pabna, Bengal Presidency', 'Kolkata, West Bengal', 'Suchitra_Sen'),

    ('K. L. Saigal', DATE '1904-04-11', DATE '1947-01-18',
        'Indian singer and actor whose recordings and film songs helped shape early playback singing in Indian cinema.',
        'Singer, Actor', 'Jammu, Jammu and Kashmir', 'Jalandhar, East Punjab', 'K._L._Saigal'),
    ('Mohammed Rafi', DATE '1924-12-24', DATE '1980-07-31',
        'Indian playback singer who recorded thousands of songs in multiple Indian languages and became a defining voice of Hindi cinema.',
        'Singer', 'Kotla Sultan Singh, Punjab', 'Mumbai, Maharashtra', 'Mohammed_Rafi'),
    ('Kishore Kumar', DATE '1929-08-04', DATE '1987-10-13',
        'Indian playback singer, actor and filmmaker celebrated for his versatile Hindi film songs and distinctive singing style.',
        'Singer, Actor, Filmmaker', 'Khandwa, Central Provinces', 'Mumbai, Maharashtra', 'Kishore_Kumar'),
    ('Lata Mangeshkar', DATE '1929-09-28', DATE '2022-02-06',
        'Indian playback singer whose career spanned decades and whose recordings included songs in numerous Indian languages.',
        'Singer', 'Indore, Indore State', 'Mumbai, Maharashtra', 'Lata_Mangeshkar'),
    ('Mukesh', DATE '1923-07-22', DATE '1976-08-27',
        'Indian playback singer best known for Hindi film songs and as the frequent singing voice for actor Raj Kapoor.',
        'Singer', 'Delhi', 'Detroit, Michigan', 'Mukesh_(singer)'),
    ('Manna Dey', DATE '1919-05-01', DATE '2013-10-24',
        'Indian playback singer who recorded in many Indian languages and was honoured with the Dadasaheb Phalke Award.',
        'Singer', 'Calcutta, Bengal Presidency', 'Bengaluru, Karnataka', 'Manna_Dey'),
    ('Hemant Kumar', DATE '1920-06-16', DATE '1989-09-26',
        'Indian singer and composer prominent in Bengali and Hindi music, known for his baritone voice and film compositions.',
        'Singer, Composer', 'Varanasi, United Provinces', 'Calcutta, West Bengal', 'Hemant_Kumar'),
    ('Geeta Dutt', DATE '1930-11-23', DATE '1972-07-20',
        'Indian playback singer known for Bengali songs and Hindi film recordings, including songs for films directed by Guru Dutt.',
        'Singer', 'Idilpur, Bengal Presidency', 'Bombay, Maharashtra', 'Geeta_Dutt'),
    ('Talat Mahmood', DATE '1924-02-24', DATE '1998-05-09',
        'Indian playback and ghazal singer remembered for his soft singing style and recordings in Hindi and Urdu.',
        'Singer', 'Lucknow, United Provinces', 'Mumbai, Maharashtra', 'Talat_Mahmood'),
    ('Shamshad Begum', DATE '1919-04-14', DATE '2013-04-23',
        'Indian playback singer whose influential recordings featured in Hindi and Punjabi films from the 1930s onward.',
        'Singer', 'Amritsar, Punjab', 'Mumbai, Maharashtra', 'Shamshad_Begum'),
    ('S. P. Balasubrahmanyam', DATE '1946-06-04', DATE '2020-09-25',
        'Indian playback singer, actor and music director who recorded in many Indian languages and received the Padma Shri and Padma Bhushan.',
        'Singer, Actor, Music director', 'Konetammapeta, Madras Presidency', 'Chennai, Tamil Nadu', 'S._P._Balasubrahmanyam'),
    ('Vani Jayaram', DATE '1945-11-30', DATE '2023-02-04',
        'Indian playback singer who recorded in multiple Indian languages and received the Padma Bhushan.',
        'Singer', 'Vellore, Madras Presidency', 'Chennai, Tamil Nadu', 'Vani_Jayaram'),
    ('Bhupen Hazarika', DATE '1926-09-08', DATE '2011-11-05',
        'Indian singer, composer and filmmaker whose songs in Assamese and other languages drew on folk traditions and social themes.',
        'Singer, Composer, Filmmaker', 'Sadiya, Assam', 'Mumbai, Maharashtra', 'Bhupen_Hazarika'),
    ('Jagjit Singh', DATE '1941-02-08', DATE '2011-10-10',
        'Indian ghazal singer and composer who helped bring the genre to a broad modern audience.',
        'Singer, Composer', 'Sri Ganganagar, Rajasthan', 'Mumbai, Maharashtra', 'Jagjit_Singh'),
    ('Bhimsen Joshi', DATE '1922-02-04', DATE '2011-01-24',
        'Indian Hindustani classical vocalist of the Kirana gharana and recipient of the Bharat Ratna.',
        'Singer', 'Ron, Bombay Presidency', 'Pune, Maharashtra', 'Bhimsen_Joshi'),
    ('Kishori Amonkar', DATE '1932-04-10', DATE '2017-04-03',
        'Indian Hindustani classical vocalist known for her khayal performances and interpretation of ragas.',
        'Singer', 'Bombay, Bombay Presidency', 'Mumbai, Maharashtra', 'Kishori_Amonkar'),
    ('Begum Akhtar', DATE '1914-10-07', DATE '1974-10-30',
        'Indian vocalist renowned for her performances of ghazal, thumri and dadra.',
        'Singer', 'Faizabad, United Provinces', 'Ahmedabad, Gujarat', 'Begum_Akhtar'),
    ('Pandit Jasraj', DATE '1930-01-28', DATE '2020-08-17',
        'Indian Hindustani classical vocalist whose career and teaching took Indian classical music to audiences around the world.',
        'Singer', 'Hisar, Punjab', 'New Jersey, United States', 'Jasraj'),
    ('R. D. Burman', DATE '1939-06-27', DATE '1994-01-04',
        'Indian composer and singer who created influential Hindi film music and collaborated with many leading playback singers.',
        'Composer, Singer', 'Calcutta, Bengal Presidency', 'Mumbai, Maharashtra', 'R._D._Burman'),
    ('Bappi Lahiri', DATE '1952-11-27', DATE '2022-02-15',
        'Indian singer and composer known for popular Hindi film music and for introducing disco-influenced sounds to Indian cinema.',
        'Singer, Composer', 'Jalpaiguri, West Bengal', 'Mumbai, Maharashtra', 'Bappi_Lahiri'),
    ('Naushad', DATE '1919-12-25', DATE '2006-05-05',
        'Indian composer known for influential Hindi film scores that incorporated Indian classical music.',
        'Composer', 'Lucknow, United Provinces', 'Mumbai, Maharashtra', 'Naushad'),
    ('M. S. Subbulakshmi', DATE '1916-09-16', DATE '2004-12-11',
        'Indian Carnatic vocalist and the first musician to receive the Bharat Ratna.',
        'Singer', 'Madurai, Madras Presidency', 'Chennai, Tamil Nadu', 'M._S._Subbulakshmi'),
    ('T. M. Soundararajan', DATE '1922-03-24', DATE '2013-05-25',
        'Indian playback singer whose Tamil film songs became closely associated with leading actors of Tamil cinema.',
        'Singer', 'Madurai, Madras Presidency', 'Chennai, Tamil Nadu', 'T._M._Soundararajan'),
    ('Ghantasala', DATE '1922-12-04', DATE '1974-02-11',
        'Indian playback singer and composer celebrated for his work in Telugu cinema and other South Indian film industries.',
        'Singer, Composer', 'Chowtapalli, Madras Presidency', 'Madras, Tamil Nadu', 'Ghantasala_(singer)')
) AS v(name, birth_date, death_date, bio, occupation, birth_place, death_place, source_slug)
WHERE NOT EXISTS (
    SELECT 1
    FROM people p
    WHERE p.name = v.name AND p.death_date = v.death_date
);
