-- More notable Indian actors and singers who have passed away.
-- Biographies are concise summaries; source links point to English Wikipedia.
-- Existing name/date pairs are skipped so earlier imports are not duplicated.
INSERT INTO people (
    id, name, birth_date, death_date, bio, lang, photo_url, occupation,
    birth_place, death_place, birth_precision, death_precision
)
SELECT
    gen_random_uuid(), v.name, v.birth_date, v.death_date,
    v.bio || E'\n\nSource: Wikipedia — https://en.wikipedia.org/wiki/' || v.source_slug,
    'en', NULL, v.occupation, v.birth_place, v.death_place, 'day', 'day'
FROM (VALUES
    ('Rajesh Khanna', DATE '1942-12-29', DATE '2012-07-18',
        'Rajesh Khanna was an Indian actor and film producer who worked primarily in Hindi cinema. He became one of the country''s leading stars in the late 1960s and 1970s, with films including Aradhana, Anand and Amar Prem. He received the Dadasaheb Phalke Award, India''s highest award in cinema.',
        'Actor, Producer', 'Amritsar, Punjab', 'Mumbai, Maharashtra', 'Rajesh_Khanna'),
    ('Shashi Kapoor', DATE '1938-03-18', DATE '2017-12-04',
        'Shashi Kapoor was an Indian actor and film producer who appeared in Hindi and English-language films. A member of the Kapoor family, he starred in films such as Deewar, Kabhi Kabhie and Junoon and also worked extensively in theatre. He received the Dadasaheb Phalke Award.',
        'Actor, Producer', 'Calcutta, Bengal Presidency', 'Mumbai, Maharashtra', 'Shashi_Kapoor'),
    ('Amrish Puri', DATE '1932-06-22', DATE '2005-01-12',
        'Amrish Puri was an Indian actor known for his work in Indian theatre and cinema. He became widely recognised for powerful character and antagonist roles in Hindi films, including Mr. India, Nagina and Dilwale Dulhania Le Jayenge. He also appeared in films made in other Indian languages and in international productions.',
        'Actor', 'Nawanshahr, Punjab', 'Mumbai, Maharashtra', 'Amrish_Puri'),
    ('Kader Khan', DATE '1937-10-22', DATE '2018-12-31',
        'Kader Khan was an Indian actor, screenwriter and dialogue writer who worked primarily in Hindi cinema. He wrote dialogue for hundreds of films and appeared in popular comedies and dramas, including Muqaddar Ka Sikandar, Coolie and Himmatwala. Before his film career, he taught civil engineering in Mumbai.',
        'Actor, Screenwriter, Dialogue writer', 'Kabul, Afghanistan', 'Toronto, Ontario', 'Kader_Khan'),
    ('Dara Singh', DATE '1928-11-19', DATE '2012-07-12',
        'Dara Singh was an Indian wrestler, actor and politician. After becoming a celebrated professional wrestler, he built a long career in Hindi and Punjabi films and was widely recognised for portraying Hanuman in the television series Ramayan. He later served as a member of the Rajya Sabha.',
        'Actor, Wrestler, Politician', 'Dharmuchak, Punjab', 'Mumbai, Maharashtra', 'Dara_Singh'),
    ('A. K. Hangal', DATE '1914-02-01', DATE '2012-08-26',
        'A. K. Hangal was an Indian actor and freedom activist who began his film career later in life. He became known for humane supporting roles in Hindi films, including Sholay, Namak Haraam and Shaukeen. Before acting, he worked as a tailor and took part in India''s independence movement.',
        'Actor, Freedom activist', 'Sialkot, Punjab', 'Mumbai, Maharashtra', 'A._K._Hangal'),
    ('Sushant Singh Rajput', DATE '1986-01-21', DATE '2020-06-14',
        'Sushant Singh Rajput was an Indian actor who worked in Hindi films and television. He first gained a wide audience through the television drama Pavitra Rishta before making his film debut in Kai Po Che!. His film roles included the title character in M. S. Dhoni: The Untold Story and a lead role in Chhichhore.',
        'Actor', 'Patna, Bihar', 'Mumbai, Maharashtra', 'Sushant_Singh_Rajput'),
    ('Nanda', DATE '1939-01-08', DATE '2014-03-25',
        'Nanda was an Indian actress who appeared in Hindi and Marathi films over a career of more than three decades. She began acting as a child and later became a leading performer in films including Chhoti Bahen, Gumnaam and Ittefaq. She received Filmfare Award nominations for her work.',
        'Actor', 'Bombay, Bombay Presidency', 'Mumbai, Maharashtra', 'Nanda_(actress)'),
    ('Parveen Babi', DATE '1954-04-04', DATE '2005-01-20',
        'Parveen Babi was an Indian actress and model who became one of the prominent Hindi film stars of the 1970s and 1980s. Her films included Deewaar, Amar Akbar Anthony and Shaan. She was among the first Indian actors to appear on the cover of Time magazine.',
        'Actor, Model', 'Junagadh, Saurashtra', 'Mumbai, Maharashtra', 'Parveen_Babi'),
    ('Reema Lagoo', DATE '1958-06-21', DATE '2017-05-18',
        'Reema Lagoo was an Indian actress known for performances in Hindi and Marathi films, television and theatre. She became especially familiar to audiences through her roles as a mother in popular Hindi films such as Maine Pyar Kiya, Saajan and Hum Aapke Hain Koun..!.',
        'Actor', 'Bombay, Bombay State', 'Mumbai, Maharashtra', 'Reema_Lagoo'),
    ('Savitri', DATE '1936-12-06', DATE '1981-12-26',
        'Savitri was an Indian actress and filmmaker who worked in Telugu and Tamil cinema, as well as other South Indian film industries. Celebrated for her expressive performances, she starred in landmark films including Devadasu, Mayabazar and Gundamma Katha. She received the Rashtrapati Award for her work in cinema.',
        'Actor, Director, Producer', 'Chirravuru, Madras Presidency', 'Chennai, Tamil Nadu', 'Savitri_(actress)'),
    ('Gemini Ganesan', DATE '1920-11-17', DATE '2005-03-22',
        'Gemini Ganesan was an Indian actor who worked predominantly in Tamil cinema and was popularly known as the Kadhal Mannan, or King of Romance. His screen career included memorable performances in Missiamma, Vanjikottai Valiban and Kalyana Parisu. He received the Padma Shri for his contribution to Indian cinema.',
        'Actor', 'Pudukkottai, Madras Presidency', 'Chennai, Tamil Nadu', 'Gemini_Ganesan'),
    ('N. T. Rama Rao', DATE '1923-05-28', DATE '1996-01-18',
        'N. T. Rama Rao was an Indian actor, filmmaker and politician who became a major star of Telugu cinema. He was especially known for portraying figures from Hindu epics and for producing and directing films. He founded the Telugu Desam Party and served as chief minister of Andhra Pradesh.',
        'Actor, Filmmaker, Politician', 'Nimmakuru, Madras Presidency', 'Hyderabad, Andhra Pradesh', 'N._T._Rama_Rao'),
    ('M. G. Ramachandran', DATE '1917-01-17', DATE '1987-12-24',
        'M. G. Ramachandran was an Indian actor, filmmaker and politician who became one of the leading stars of Tamil cinema. He founded the All India Anna Dravida Munnetra Kazhagam and served as chief minister of Tamil Nadu. He received the Bharat Ratna posthumously.',
        'Actor, Filmmaker, Politician', 'Kandy, British Ceylon', 'Chennai, Tamil Nadu', 'M._G._Ramachandran'),
    ('Akkineni Nageswara Rao', DATE '1924-09-20', DATE '2014-01-22',
        'Akkineni Nageswara Rao was an Indian actor and film producer who worked primarily in Telugu cinema. Over a career spanning more than seven decades, he appeared in films including Devadasu, Mayabazar and Premabhishekam. He was a recipient of the Dadasaheb Phalke Award and the Padma Vibhushan.',
        'Actor, Producer', 'Venkataraghavapuram, Madras Presidency', 'Hyderabad, Telangana', 'Akkineni_Nageswara_Rao'),
    ('Krishna', DATE '1943-05-31', DATE '2022-11-15',
        'Krishna was an Indian actor, director and producer whose work was primarily in Telugu cinema. He appeared in hundreds of films and was known for experimenting with new production techniques and genres in the industry. He received the Padma Bhushan for his contributions to Indian cinema.',
        'Actor, Director, Producer', 'Burripalem, Madras Presidency', 'Hyderabad, Telangana', 'Krishna_(Telugu_actor)'),
    ('Puneeth Rajkumar', DATE '1975-03-17', DATE '2021-10-29',
        'Puneeth Rajkumar was an Indian actor, playback singer and television presenter who worked primarily in Kannada cinema. He began as a child performer and later starred in popular films including Appu, Raajakumara and James. He received the Karnataka State Film Award for Best Child Actor.',
        'Actor, Singer, Television presenter', 'Chennai, Tamil Nadu', 'Bengaluru, Karnataka', 'Puneeth_Rajkumar'),
    ('Vishnuvardhan', DATE '1950-09-18', DATE '2009-12-30',
        'Vishnuvardhan was an Indian actor who worked in Kannada cinema and appeared in films in several other Indian languages. He rose to prominence with the film Naagarahaavu and went on to star in a wide range of acclaimed and popular productions. He was honoured with the Padma Shri.',
        'Actor', 'Mysore, Mysore State', 'Mysore, Karnataka', 'Vishnuvardhan_(actor)'),
    ('Shankar Nag', DATE '1954-11-09', DATE '1990-09-30',
        'Shankar Nag was an Indian actor, screenwriter and director who worked primarily in Kannada cinema. He directed the acclaimed film Ondanondu Kaladalli and created the television series Malgudi Days, adapted from the stories of R. K. Narayan. He was also active in theatre.',
        'Actor, Director, Screenwriter', 'Mallapur, Mysore State', 'Anand, Gujarat', 'Shankar_Nag'),
    ('Manorama', DATE '1937-05-26', DATE '2015-10-10',
        'Manorama was an Indian actress and comedian who worked mainly in Tamil cinema and also performed in theatre and television. Known by the nickname Aachi, she appeared in hundreds of films across a career lasting more than six decades. She received the Padma Shri and the Kalaimamani award.',
        'Actor, Comedian, Singer', 'Mannargudi, Madras Presidency', 'Chennai, Tamil Nadu', 'Manorama_(Tamil_actress)'),
    ('Padmini', DATE '1932-06-12', DATE '2006-09-24',
        'Padmini was an Indian actress and classical dancer who worked in Tamil, Malayalam, Hindi and other Indian-language films. Alongside her sisters Lalitha and Ragini, she was part of the celebrated Travancore Sisters. Her screen career included films such as Thillana Mohanambal and Poovizhi Vasalile.',
        'Actor, Dancer', 'Thiruvananthapuram, Travancore', 'Chennai, Tamil Nadu', 'Padmini_(actress)'),
    ('Soumitra Chatterjee', DATE '1935-01-19', DATE '2020-11-15',
        'Soumitra Chatterjee was an Indian actor, poet and theatre director who worked mainly in Bengali cinema. He became widely known through his collaborations with filmmaker Satyajit Ray, beginning with The World of Apu. His many honours included the Dadasaheb Phalke Award and the Padma Bhushan.',
        'Actor, Poet, Theatre director', 'Krishnanagar, Bengal Presidency', 'Kolkata, West Bengal', 'Soumitra_Chatterjee'),
    ('Chhabi Biswas', DATE '1900-07-12', DATE '1962-06-11',
        'Chhabi Biswas was an Indian actor particularly remembered for his work in Bengali cinema. He frequently portrayed dignified and authoritative characters, including the title role in Satyajit Ray''s Jalsaghar. His career helped shape the character-actor tradition of Bengali film.',
        'Actor', 'Calcutta, Bengal Presidency', 'Kolkata, West Bengal', 'Chhabi_Biswas'),
    ('Rajendra Nath', DATE '1931-06-08', DATE '2008-02-13',
        'Rajendra Nath was an Indian actor and comedian who appeared in Hindi films from the 1950s onward. He became known for comic supporting roles in popular films including Dil Deke Dekho, Jab Pyar Kisise Hota Hai and Phir Wohi Dil Laya Hoon.',
        'Actor, Comedian', 'Peshawar', 'Mumbai, Maharashtra', 'Rajendra_Nath'),
    ('Johnny Walker', DATE '1926-11-11', DATE '2003-07-29',
        'Johnny Walker was an Indian actor and comedian who became one of Hindi cinema''s best-known comic performers. He appeared in many celebrated films, including Pyaasa, C.I.D. and Madhumati, often in roles written around his distinctive comic persona. His screen name was inspired by the whisky brand.',
        'Actor, Comedian', 'Indore, Indore State', 'Mumbai, Maharashtra', 'Johnny_Walker_(actor)'),
    ('Farooq Sheikh', DATE '1948-03-25', DATE '2013-12-28',
        'Farooq Sheikh was an Indian actor, television presenter and social worker associated with Hindi parallel cinema. His performances in films such as Gaman, Umrao Jaan and Chashme Buddoor earned him a reputation for naturalistic acting. He also hosted the television programme Jeena Isi Ka Naam Hai.',
        'Actor, Television presenter', 'Amroli, Bombay State', 'Dubai, United Arab Emirates', 'Farooq_Sheikh'),
    ('Tom Alter', DATE '1950-06-22', DATE '2017-09-29',
        'Tom Alter was an Indian actor of American descent who worked in Hindi films, theatre and television. Fluent in Hindi and Urdu, he performed in a wide range of Indian productions, including the television series Junoon and the film Kranti. He was awarded the Padma Shri for his contribution to the arts.',
        'Actor, Writer', 'Mussoorie, Uttar Pradesh', 'Mumbai, Maharashtra', 'Tom_Alter'),

    ('M. S. Viswanathan', DATE '1928-06-24', DATE '2015-07-14',
        'M. S. Viswanathan was an Indian composer, singer and actor who worked primarily in Tamil cinema. In partnership with T. K. Ramamoorthy, and later independently, he composed music for hundreds of films and helped define popular South Indian film music. He was popularly known as Mellisai Mannar, meaning King of Light Music.',
        'Composer, Singer, Actor', 'Elappully, Madras Presidency', 'Chennai, Tamil Nadu', 'M._S._Viswanathan'),
    ('Madan Mohan', DATE '1924-06-25', DATE '1975-07-14',
        'Madan Mohan was an Indian music director known for his Hindi film compositions and especially for his ghazal-based songs. His work included the soundtracks of Anpadh, Woh Kaun Thi? and Laila Majnu. Several of his compositions became closely associated with the voice of Lata Mangeshkar.',
        'Composer', 'Baghdad, Kingdom of Iraq', 'Mumbai, Maharashtra', 'Madan_Mohan'),
    ('Khayyam', DATE '1927-02-18', DATE '2019-08-19',
        'Khayyam was an Indian music director and composer who created songs for Hindi films over a career spanning several decades. His acclaimed soundtracks included Umrao Jaan and Kabhi Kabhie, for which he received major Indian film awards. He received the Padma Bhushan for his contribution to music.',
        'Composer, Music director', 'Rahoon, Punjab', 'Mumbai, Maharashtra', 'Khayyam'),
    ('C. Ramchandra', DATE '1918-01-12', DATE '1982-01-05',
        'C. Ramchandra was an Indian composer, singer and actor who worked in Hindi and Marathi cinema. He composed popular film songs and sometimes performed under the name Chitalkar. His best-known work includes the music of Anarkali and the patriotic song Aye Mere Watan Ke Logo.',
        'Composer, Singer, Actor', 'Puntamba, Bombay Presidency', 'Mumbai, Maharashtra', 'C._Ramchandra'),
    ('Salil Chowdhury', DATE '1922-11-19', DATE '1995-09-05',
        'Salil Chowdhury was an Indian composer, songwriter, writer and poet whose work crossed Bengali, Hindi and Malayalam cinema. He combined Indian folk and classical traditions with Western orchestration and composed songs and scores for numerous films. He was also active in the Indian People''s Theatre Association.',
        'Composer, Songwriter, Writer', 'Ghazipur, Bengal Presidency', 'Kolkata, West Bengal', 'Salil_Chowdhury'),
    ('Roshan', DATE '1917-07-14', DATE '1967-11-16',
        'Roshan was an Indian composer known for his Hindi film music, including songs rooted in Hindustani classical forms. His film scores included Barsaat Ki Raat, Taj Mahal and Chitralekha. He was the father of filmmaker Rakesh Roshan and music director Rajesh Roshan.',
        'Composer', 'Gujranwala, Punjab', 'Mumbai, Maharashtra', 'Roshan_(music_director)'),
    ('Ravi', DATE '1926-03-03', DATE '2012-03-07',
        'Ravi was an Indian composer and singer who worked in Hindi and Malayalam cinema. He composed music for films including Chaudhvin Ka Chand, Waqt and Nikaah, and also recorded as a playback singer. His Malayalam film work was often credited under the name Bombay Ravi.',
        'Composer, Singer', 'Delhi', 'Mumbai, Maharashtra', 'Ravi_(composer)'),
    ('P. B. Sreenivas', DATE '1930-09-22', DATE '2013-04-14',
        'P. B. Sreenivas was an Indian playback singer who recorded songs in Kannada, Telugu, Tamil, Malayalam and Hindi. His voice became especially associated with leading actors in Kannada cinema, including Dr. Rajkumar. He received the Padma Shri for his contribution to Indian music.',
        'Singer', 'Kakinada, Madras Presidency', 'Chennai, Tamil Nadu', 'P._B._Sreenivas'),
    ('P. Leela', DATE '1934-05-19', DATE '2005-10-31',
        'P. Leela was an Indian playback singer who recorded extensively in Malayalam, Tamil, Telugu and Kannada. Her career included thousands of songs for films and devotional music, and she was honoured with the Kerala State Film Award for her contribution to playback singing.',
        'Singer', 'Nellore, Madras Presidency', 'Chennai, Tamil Nadu', 'P._Leela'),
    ('Jikki', DATE '1935-11-03', DATE '2004-08-16',
        'Jikki was an Indian playback singer whose recordings featured in Tamil, Telugu, Kannada and Malayalam films. She became a popular voice in South Indian cinema from the 1940s onward and recorded songs for many leading composers of the period.',
        'Singer', 'Gajapathinagaram, Madras Presidency', 'Chennai, Tamil Nadu', 'Jikki'),
    ('D. K. Pattammal', DATE '1919-03-19', DATE '2009-07-16',
        'D. K. Pattammal was an Indian Carnatic vocalist who helped bring classical music to concert audiences across India and abroad. She was among the first women to perform complex pallavis on the concert stage and also sang playback for Tamil films. She received the Padma Vibhushan and the Sangeet Natak Akademi Fellowship.',
        'Singer', 'Kancheepuram, Madras Presidency', 'Chennai, Tamil Nadu', 'D._K._Pattammal'),
    ('M. L. Vasanthakumari', DATE '1928-07-03', DATE '1990-10-31',
        'M. L. Vasanthakumari was an Indian Carnatic vocalist and playback singer. A leading performer of her generation, she helped popularise compositions by Purandara Dasa and was a recipient of the Sangeet Natak Akademi Award and the Padma Bhushan.',
        'Singer', 'Madras, Madras Presidency', 'Chennai, Tamil Nadu', 'M._L._Vasanthakumari'),
    ('Gangubai Hangal', DATE '1913-03-05', DATE '2009-07-21',
        'Gangubai Hangal was an Indian Hindustani classical vocalist of the Kirana gharana, known for her deep voice and khayal performances. She performed widely in India and abroad and received the Padma Bhushan, Padma Vibhushan and Sangeet Natak Akademi Fellowship.',
        'Singer', 'Dharwad, Bombay Presidency', 'Hubli, Karnataka', 'Gangubai_Hangal'),
    ('M. Balamuralikrishna', DATE '1930-07-06', DATE '2016-11-22',
        'M. Balamuralikrishna was an Indian Carnatic vocalist, composer and multi-instrumentalist. He performed internationally, composed numerous works and appeared as a playback singer in Indian films. His honours included the Padma Vibhushan and the Sangeet Natak Akademi Award.',
        'Singer, Composer, Musician', 'Sankaraguptam, Madras Presidency', 'Chennai, Tamil Nadu', 'M._Balamuralikrishna'),
    ('Sulochana Chavan', DATE '1933-03-13', DATE '2022-12-10',
        'Sulochana Chavan was an Indian singer particularly known for performing lavani, a musical genre of Maharashtra. She recorded songs for Marathi films and became celebrated for bringing lavani to a broad audience. She received the Padma Shri and the Sangeet Natak Akademi Award.',
        'Singer', 'Mumbai, Bombay Presidency', 'Mumbai, Maharashtra', 'Sulochana_Chavan')
) AS v(name, birth_date, death_date, bio, occupation, birth_place, death_place, source_slug)
WHERE NOT EXISTS (
    SELECT 1
    FROM people p
    WHERE p.name = v.name AND p.death_date = v.death_date
);
