-- Notable Indian politicians and public leaders who have passed away.
-- Biographies are concise summaries; source links point to English Wikipedia.
-- Existing name/date pairs are skipped so earlier imports are not duplicated.
INSERT INTO people (
    id, name, birth_date, death_date, bio, lang, photo_url, occupation,
    birth_place, death_place, birth_precision, death_precision
)
SELECT
    gen_random_uuid(), v.name, v.birth_date, v.death_date,
    v.bio || E'\n\nSource: Wikipedia — https://en.wikipedia.org/wiki/' || v.source_slug,
    'en', NULL, v.occupation, v.birth_place, v.death_place, 'day', 'day'
FROM (VALUES
    ('C. N. Annadurai', DATE '1909-09-15', DATE '1969-02-03',
        'Conjeevaram Natarajan Annadurai was an Indian politician, writer and orator who founded the Dravida Munnetra Kazhagam. He served as chief minister of Madras State from 1967 until his death and was a leading advocate for social reform and greater state autonomy. During his tenure, Madras State was renamed Tamil Nadu.',
        'Politician, Writer', 'Kancheepuram, Madras Presidency', 'Madras, Tamil Nadu', 'C._N._Annadurai'),
    ('E. M. S. Namboodiripad', DATE '1909-06-13', DATE '1998-03-19',
        'Elamkulam Manakkal Sankaran Namboodiripad was an Indian communist politician, writer and social commentator. He led Kerala''s first elected state government in 1957 and later served again as chief minister. He was a leading figure in the Communist movement in India.',
        'Politician, Writer', 'Perintalmanna, Madras Presidency', 'Thiruvananthapuram, Kerala', 'E._M._S._Namboodiripad'),
    ('Jyoti Basu', DATE '1914-07-08', DATE '2010-01-17',
        'Jyoti Basu was an Indian communist politician who served as chief minister of West Bengal from 1977 to 2000, one of the longest tenures for a state chief minister in India. A founding member of the Communist Party of India (Marxist), he was also a prominent participant in parliamentary politics and coalition government.',
        'Politician', 'Calcutta, Bengal Presidency', 'Kolkata, West Bengal', 'Jyoti_Basu'),
    ('Biju Patnaik', DATE '1916-03-05', DATE '1997-04-17',
        'Bijayananda Patnaik, known as Biju Patnaik, was an Indian politician, aviator and freedom activist. He served twice as chief minister of Odisha and founded the Janata Dal in the state. During the Second World War and the independence movement, he undertook notable aviation missions in support of political and humanitarian causes.',
        'Politician, Aviator', 'Cuttack, Bengal Presidency', 'New Delhi', 'Biju_Patnaik'),
    ('J. Jayalalithaa', DATE '1948-02-24', DATE '2016-12-05',
        'Jayaram Jayalalithaa was an Indian politician and former actor who served multiple terms as chief minister of Tamil Nadu. She led the All India Anna Dravida Munnetra Kazhagam and was widely known by the honorific Amma among her supporters. Before entering politics, she was a leading performer in Tamil-language cinema.',
        'Politician, Actor', 'Melukote, Mysore State', 'Chennai, Tamil Nadu', 'Jayalalithaa'),
    ('M. Karunanidhi', DATE '1924-06-03', DATE '2018-08-07',
        'Muthuvel Karunanidhi was an Indian politician, screenwriter and writer who served multiple terms as chief minister of Tamil Nadu. A leader of the Dravida Munnetra Kazhagam for decades, he was influential in Tamil Nadu politics and wrote scripts, plays and essays in Tamil.',
        'Politician, Writer, Screenwriter', 'Thirukkuvalai, Madras Presidency', 'Chennai, Tamil Nadu', 'M._Karunanidhi'),
    ('Bal Thackeray', DATE '1926-01-23', DATE '2012-11-17',
        'Bal Keshav Thackeray was an Indian politician and cartoonist who founded the Shiv Sena political party in Maharashtra. He began his career as a newspaper cartoonist and became a highly influential figure in Mumbai and state politics. He was also known by the honorific Hindu Hriday Samrat among supporters.',
        'Politician, Cartoonist', 'Pune, Bombay Presidency', 'Mumbai, Maharashtra', 'Bal_Thackeray'),
    ('George Fernandes', DATE '1930-06-03', DATE '2019-01-29',
        'George Fernandes was an Indian trade unionist and politician who held several cabinet positions, including minister of defence. He rose to national prominence as a labour leader and parliamentarian and was a leading figure in the opposition during the Emergency. He represented constituencies in both Bihar and Karnataka.',
        'Politician, Trade unionist', 'Mangalore, Mysore State', 'New Delhi', 'George_Fernandes'),
    ('Jayaprakash Narayan', DATE '1902-10-11', DATE '1979-10-08',
        'Jayaprakash Narayan was an Indian independence activist and political leader popularly known as JP. He helped found the Congress Socialist Party and later led a mass movement advocating democratic reform, which became a major challenge to the Emergency government. He received the Bharat Ratna posthumously.',
        'Politician, Independence activist', 'Sitabdiara, Bengal Presidency', 'Patna, Bihar', 'Jayaprakash_Narayan'),
    ('Ram Manohar Lohia', DATE '1910-03-23', DATE '1967-10-12',
        'Ram Manohar Lohia was an Indian socialist politician and independence activist. He helped organise resistance to British rule and later became an influential opposition leader and advocate of social equality, linguistic diversity and decentralised government.',
        'Politician, Independence activist', 'Akbarpur, United Provinces', 'New Delhi', 'Ram_Manohar_Lohia'),
    ('Kanshi Ram', DATE '1934-03-15', DATE '2006-10-09',
        'Kanshi Ram was an Indian politician and social reformer who founded the Bahujan Samaj Party. He organised political movements representing Dalits and other historically marginalised communities and helped build a major political force in Uttar Pradesh. He was known to supporters as Bahujan Nayak.',
        'Politician, Social reformer', 'Khawaspur, Punjab', 'New Delhi', 'Kanshi_Ram'),
    ('Deendayal Upadhyaya', DATE '1916-09-25', DATE '1968-02-11',
        'Deendayal Upadhyaya was an Indian political thinker and organiser who served as president of the Bharatiya Jana Sangh. He developed the political philosophy of Integral Humanism and was active in building the Rashtriya Swayamsevak Sangh and its affiliated organisations.',
        'Politician, Political theorist', 'Dhankya, Jaipur State', 'Mughalsarai, Uttar Pradesh', 'Deendayal_Upadhyaya'),
    ('Gopinath Bordoloi', DATE '1890-06-06', DATE '1950-08-05',
        'Gopinath Bordoloi was an Indian independence activist and the first chief minister of Assam after independence. He worked to preserve Assam''s place within India during the partition period and was a prominent leader of the Indian National Congress in the region. He was posthumously awarded the Bharat Ratna.',
        'Politician, Independence activist', 'Raha, Assam', 'Guwahati, Assam', 'Gopinath_Bordoloi'),
    ('Gopal Krishna Gokhale', DATE '1866-05-09', DATE '1915-02-19',
        'Gopal Krishna Gokhale was an Indian political leader and social reformer who worked for constitutional change and public education under British rule. He founded the Servants of India Society and served in the Imperial Legislative Council. Mahatma Gandhi regarded him as a mentor.',
        'Politician, Social reformer', 'Kotluk, Bombay Presidency', 'Bombay, Bombay Presidency', 'Gopal_Krishna_Gokhale'),
    ('Dadabhai Naoroji', DATE '1825-09-04', DATE '1917-06-30',
        'Dadabhai Naoroji was an Indian political leader, educator and writer known as the Grand Old Man of India. He was a founding member of the Indian National Congress and became the first British Indian member of the United Kingdom Parliament. His economic writing drew attention to the drain of wealth from India under colonial rule.',
        'Politician, Educator, Writer', 'Bombay, Bombay Presidency', 'Bombay, Bombay Presidency', 'Dadabhai_Naoroji'),
    ('Lala Lajpat Rai', DATE '1865-01-28', DATE '1928-11-17',
        'Lala Lajpat Rai was an Indian independence activist, politician and writer known as Punjab Kesari. He was part of the Lal-Bal-Pal nationalist trio and led protests against the Simon Commission. He died after injuries sustained during a police lathi charge at a demonstration in Lahore.',
        'Politician, Independence activist, Writer', 'Dhudike, Punjab', 'Lahore, Punjab', 'Lala_Lajpat_Rai'),
    ('Bal Gangadhar Tilak', DATE '1856-07-23', DATE '1920-08-01',
        'Bal Gangadhar Tilak was an Indian nationalist, teacher and journalist who became a prominent leader in the independence movement. He founded the newspapers Kesari and The Mahratta and helped popularise public Ganesh celebrations. His slogan, “Swaraj is my birthright and I shall have it,” became associated with the struggle for self-rule.',
        'Politician, Journalist, Teacher', 'Chikhali, Bombay Presidency', 'Bombay, Bombay Presidency', 'Bal_Gangadhar_Tilak'),
    ('Bhagat Singh', DATE '1907-09-28', DATE '1931-03-23',
        'Bhagat Singh was an Indian revolutionary and independence activist who opposed British colonial rule. He became a prominent figure in the Hindustan Socialist Republican Association and was involved in acts of political protest in the late 1920s. He was executed by the British government in Lahore at the age of 23.',
        'Revolutionary, Independence activist', 'Banga, Punjab', 'Lahore, Punjab', 'Bhagat_Singh'),
    ('Chandrashekhar Azad', DATE '1906-07-23', DATE '1931-02-27',
        'Chandrashekhar Azad was an Indian revolutionary who fought British rule and helped lead the Hindustan Socialist Republican Association. He took part in the Kakori train action and other revolutionary activities. He died in a gunfight with British police at Alfred Park in Allahabad.',
        'Revolutionary, Independence activist', 'Bhabhra, Central India Agency', 'Allahabad, United Provinces', 'Chandra_Shekhar_Azad'),
    ('Maulana Abul Kalam Azad', DATE '1888-11-11', DATE '1958-02-22',
        'Abul Kalam Azad was an Indian independence activist, scholar and politician. He served as president of the Indian National Congress and became independent India''s first minister of education. He supported a united India and was posthumously awarded the Bharat Ratna.',
        'Politician, Scholar, Independence activist', 'Mecca, Hejaz', 'New Delhi', 'Abul_Kalam_Azad'),
    ('Sarojini Naidu', DATE '1879-02-13', DATE '1949-03-02',
        'Sarojini Naidu was an Indian poet and independence activist who served as the first woman president of the Indian National Congress. After independence, she became governor of the United Provinces, now Uttar Pradesh. Her poetry earned her the title Nightingale of India.',
        'Politician, Poet, Independence activist', 'Hyderabad, Hyderabad State', 'Lucknow, Uttar Pradesh', 'Sarojini_Naidu'),
    ('Vijaya Raje Scindia', DATE '1919-10-12', DATE '2001-01-25',
        'Vijaya Raje Scindia was an Indian politician and a prominent leader of the Bharatiya Jana Sangh and later the Bharatiya Janata Party. Born into the Gwalior royal family, she was elected to Parliament several times and became an influential figure in national and Madhya Pradesh politics.',
        'Politician', 'Sagar, Central Provinces', 'Gwalior, Madhya Pradesh', 'Vijaya_Raje_Scindia'),
    ('Sheila Dikshit', DATE '1938-03-31', DATE '2019-07-20',
        'Sheila Dikshit was an Indian politician who served as chief minister of Delhi for three consecutive terms from 1998 to 2013. She was among India''s longest-serving women chief ministers and later served as governor of Kerala. Her tenure coincided with major changes in Delhi''s transport and urban infrastructure.',
        'Politician', 'Kapurthala, Punjab', 'New Delhi', 'Sheila_Dikshit'),
    ('Sushma Swaraj', DATE '1952-02-14', DATE '2019-08-06',
        'Sushma Swaraj was an Indian lawyer and politician who served as minister of external affairs from 2014 to 2019. She was the first woman to hold that cabinet position and had earlier served as chief minister of Delhi and leader of the opposition in the Lok Sabha.',
        'Politician, Lawyer', 'Ambala Cantonment, Punjab', 'New Delhi', 'Sushma_Swaraj'),
    ('Arun Jaitley', DATE '1952-12-28', DATE '2019-08-24',
        'Arun Jaitley was an Indian lawyer and politician who served as minister of finance and minister of corporate affairs. A senior leader of the Bharatiya Janata Party, he represented the party in Parliament and served as leader of the opposition in the Rajya Sabha. Before entering public office, he practised law at the Supreme Court of India.',
        'Politician, Lawyer', 'New Delhi', 'New Delhi', 'Arun_Jaitley'),
    ('Manohar Parrikar', DATE '1955-12-13', DATE '2019-03-17',
        'Manohar Parrikar was an Indian politician who served multiple terms as chief minister of Goa and later as minister of defence. An engineer by training, he was the first Indian Institute of Technology graduate to become a chief minister of an Indian state. He played a role in several defence policy initiatives.',
        'Politician, Engineer', 'Mapusa, Goa', 'Panaji, Goa', 'Manohar_Parrikar'),
    ('V. P. Singh', DATE '1931-06-25', DATE '2008-11-27',
        'Vishwanath Pratap Singh was an Indian politician who served as prime minister from 1989 to 1990. His government implemented recommendations of the Mandal Commission on reservations for Other Backward Classes in central government employment. He had earlier served as chief minister of Uttar Pradesh and as India''s finance and defence minister.',
        'Politician', 'Allahabad, United Provinces', 'New Delhi', 'V._P._Singh'),
    ('Charan Singh', DATE '1902-12-23', DATE '1987-05-29',
        'Charan Singh was an Indian politician who served as prime minister in 1979 and 1980. He built his political career in Uttar Pradesh and was a leading advocate for farmers and rural interests. Before becoming prime minister, he served as chief minister of Uttar Pradesh and held several national cabinet posts.',
        'Politician', 'Noorpur, United Provinces', 'New Delhi', 'Charan_Singh'),
    ('Morarji Desai', DATE '1896-02-29', DATE '1995-04-10',
        'Morarji Desai was an Indian independence activist and politician who served as prime minister from 1977 to 1979. He was the first prime minister from outside the Indian National Congress and earlier served as chief minister of Bombay State and as deputy prime minister. In 1991 he received the Bharat Ratna.',
        'Politician, Independence activist', 'Bhadeli, Bombay Presidency', 'Mumbai, Maharashtra', 'Morarji_Desai'),
    ('Gulzarilal Nanda', DATE '1898-07-04', DATE '1998-01-15',
        'Gulzarilal Nanda was an Indian economist, politician and independence activist. He served twice as acting prime minister following the deaths of Jawaharlal Nehru and Lal Bahadur Shastri and held several cabinet positions, including minister of labour. He received the Bharat Ratna in 1997.',
        'Politician, Economist', 'Sialkot, Punjab', 'Ahmedabad, Gujarat', 'Gulzarilal_Nanda'),
    ('K. R. Narayanan', DATE '1920-10-27', DATE '2005-11-09',
        'Kocheril Raman Narayanan was an Indian diplomat and politician who served as president of India from 1997 to 2002. He was the first Dalit to hold the office and previously served as vice president and as a diplomat in several countries. Before entering public service, he worked as a journalist and studied at the London School of Economics.',
        'Politician, Diplomat', 'Uzhavoor, Travancore', 'New Delhi', 'K._R._Narayanan'),
    ('Zakir Husain', DATE '1897-02-08', DATE '1969-05-03',
        'Zakir Husain was an Indian educationist and politician who served as president of India from 1967 until his death. He was a co-founder of Jamia Millia Islamia and served as governor of Bihar and vice president of India. He was the first Muslim president of India and received the Bharat Ratna in 1963.',
        'Politician, Educationist', 'Hyderabad, Hyderabad State', 'New Delhi', 'Zakir_Husain'),
    ('Fakhruddin Ali Ahmed', DATE '1905-05-13', DATE '1977-02-11',
        'Fakhruddin Ali Ahmed was an Indian politician who served as president of India from 1974 until his death. A lawyer by training, he was active in the Indian National Congress and held several cabinet posts, including minister of agriculture. He was the second Indian president to die in office.',
        'Politician, Lawyer', 'Delhi, Punjab Province', 'New Delhi', 'Fakhruddin_Ali_Ahmed'),
    ('Shankar Dayal Sharma', DATE '1918-08-19', DATE '1999-12-26',
        'Shankar Dayal Sharma was an Indian lawyer and politician who served as president of India from 1992 to 1997. He previously served as governor of several states, chief minister of Madhya Pradesh and vice president of India. He was also active in the Indian independence movement.',
        'Politician, Lawyer', 'Bhopal, Bhopal State', 'New Delhi', 'Shankar_Dayal_Sharma'),
    ('R. Venkataraman', DATE '1910-12-04', DATE '2009-01-27',
        'Ramaswamy Venkataraman was an Indian lawyer, independence activist and politician who served as president of India from 1987 to 1992. He held several senior cabinet positions, including minister of finance and minister of defence, and earlier served as vice president.',
        'Politician, Lawyer', 'Rajamadam, Madras Presidency', 'New Delhi', 'R._Venkataraman'),
    ('P. V. Narasimha Rao', DATE '1921-06-28', DATE '2004-12-23',
        'Pamulaparthi Venkata Narasimha Rao was an Indian politician who served as prime minister from 1991 to 1996. His government introduced major economic reforms and oversaw a significant shift in India''s economic policy. A scholar and linguist, he also served as chief minister of Andhra Pradesh and held several union cabinet portfolios.',
        'Politician, Writer', 'Laknepalli, Hyderabad State', 'New Delhi', 'P._V._Narasimha_Rao'),
    ('Mulayam Singh Yadav', DATE '1939-11-22', DATE '2022-10-10',
        'Mulayam Singh Yadav was an Indian politician who served three terms as chief minister of Uttar Pradesh and one term as India''s defence minister. He founded the Samajwadi Party and represented Uttar Pradesh in both the state assembly and Parliament over a long political career.',
        'Politician', 'Saifai, United Provinces', 'Gurugram, Haryana', 'Mulayam_Singh_Yadav'),
    ('Devaraj Urs', DATE '1915-08-20', DATE '1982-06-06',
        'Devaraj Urs was an Indian politician who served two terms as chief minister of Karnataka. His government introduced land reforms and measures aimed at improving representation for disadvantaged communities. He was a prominent leader of the Indian National Congress in Karnataka.',
        'Politician', 'Kallahalli, Mysore State', 'Bengaluru, Karnataka', 'D._Devaraj_Urs'),
    ('K. Kamaraj', DATE '1903-07-15', DATE '1975-10-02',
        'Kumaraswami Kamaraj was an Indian independence activist and politician who served as chief minister of Madras State from 1954 to 1963. His government expanded public education and school meal programmes. Later, as president of the Indian National Congress, he helped broker the succession of national leaders after the deaths of Nehru and Shastri.',
        'Politician, Independence activist', 'Virudhunagar, Madras Presidency', 'Madras, Tamil Nadu', 'K._Kamaraj'),
    ('Raja Ram Mohan Roy', DATE '1772-05-22', DATE '1833-09-27',
        'Raja Ram Mohan Roy was an Indian religious and social reformer whose work influenced the Bengal Renaissance. He campaigned against sati, supported modern education and founded the Brahmo Sabha, later known as the Brahmo Samaj. He travelled to Britain as an envoy of the Mughal emperor and died there.',
        'Social reformer, Writer, Political activist', 'Radhanagar, Bengal Presidency', 'Stapleton, Bristol, England', 'Ram_Mohan_Roy'),
    ('Rani Lakshmibai', DATE '1828-11-19', DATE '1858-06-18',
        'Lakshmibai, the Rani of Jhansi, was an Indian queen and one of the leading figures of the Indian Rebellion of 1857. She resisted the East India Company''s annexation of Jhansi and led her forces in battles against British troops. She died during the fighting near Gwalior and became an enduring symbol of resistance.',
        'Ruler, Military leader', 'Varanasi, Benares State', 'Gwalior, Central India Agency', 'Rani_of_Jhansi'),
    ('N. G. Ranga', DATE '1900-11-07', DATE '1995-06-09',
        'Gogineni Ranga was an Indian parliamentarian, freedom fighter and advocate for farmers. He founded the Swatantra Party with C. Rajagopalachari and represented rural interests in Parliament for decades. He received the Padma Vibhushan for his public service.',
        'Politician, Farmer leader', 'Nidubrolu, Madras Presidency', 'Guntur, Andhra Pradesh', 'N._G._Ranga'),
    ('B. P. Mandal', DATE '1918-08-25', DATE '1982-04-13',
        'Bindheshwari Prasad Mandal was an Indian politician who chaired the Second Backward Classes Commission, commonly known as the Mandal Commission. The commission''s report recommended reservations for socially and educationally backward classes in public employment and became a major influence on Indian public policy.',
        'Politician', 'Murho, Bihar and Orissa Province', 'Patna, Bihar', 'B._P._Mandal'),
    ('Madhavrao Scindia', DATE '1945-03-10', DATE '2001-09-30',
        'Madhavrao Scindia was an Indian politician who served as a member of Parliament and held several union cabinet portfolios, including civil aviation and railways. A prominent leader from Madhya Pradesh, he was a member of the Indian National Congress and had earlier represented the Gwalior royal family in public life.',
        'Politician', 'Bombay, Bombay Province', 'Mainpuri, Uttar Pradesh', 'Madhavrao_Scindia'),
    ('Pramod Mahajan', DATE '1949-10-30', DATE '2006-05-03',
        'Pramod Mahajan was an Indian politician and senior leader of the Bharatiya Janata Party. He served as a union minister responsible for telecommunications and parliamentary affairs and was influential in the party''s election campaigns and organisation. He represented Maharashtra in the Rajya Sabha.',
        'Politician', 'Mahbubnagar, Hyderabad State', 'Mumbai, Maharashtra', 'Pramod_Mahajan'),
    ('R. K. Hegde', DATE '1926-08-29', DATE '2004-01-12',
        'Ramakrishna Hegde was an Indian politician who served as chief minister of Karnataka and later as union minister. A founding leader of the Janata Party, he was known for decentralisation measures, including the introduction of local self-government reforms in Karnataka.',
        'Politician', 'Siddapur, Mysore State', 'Bengaluru, Karnataka', 'R._K._Hegde'),
    ('S. R. Bommai', DATE '1924-06-20', DATE '2007-10-10',
        'Somappa Rayappa Bommai was an Indian politician who served as chief minister of Karnataka and was a national leader of the Janata Dal. His dismissal from office led to the landmark Supreme Court judgment in S. R. Bommai v. Union of India, which clarified limits on the use of President''s Rule in the states.',
        'Politician', 'Karajagi, Bombay Presidency', 'Bengaluru, Karnataka', 'S._R._Bommai')
) AS v(name, birth_date, death_date, bio, occupation, birth_place, death_place, source_slug)
WHERE NOT EXISTS (
    SELECT 1
    FROM people p
    WHERE p.name = v.name AND p.death_date = v.death_date
);
