-- Fill missing profile photos for recently imported performers and public figures.
-- Image URLs are Commons-hosted page thumbnails, retrieved through Wikipedia pageimages.
-- Photos without a verified Wikimedia Commons image are left unchanged.
WITH imported_images (name, death_date, photo_url) AS (
  VALUES
    ('Ashok Kumar', DATE '2001-12-10', 'https://upload.wikimedia.org/wikipedia/commons/6/66/Ashok_Kumar_Saab.jpg'),
    ('Raj Kapoor', DATE '1988-06-02', 'https://upload.wikimedia.org/wikipedia/commons/3/3b/Raj_Kapoor_2001_stamp_of_India_%28cropped%29.jpg'),
    ('Dilip Kumar', DATE '2021-07-07', 'https://upload.wikimedia.org/wikipedia/commons/8/8f/Dilip_Kumar_2006.jpg'),
    ('Dev Anand', DATE '2011-12-03', 'https://upload.wikimedia.org/wikipedia/commons/8/8e/Dev_Anand_interacting_with_the_Press_at_the_36th_International_Film_Festival_of_India_%E2%80%93_2005_in_Panaji%2C_Goa_on_November_26%2C_2005.jpg'),
    ('Guru Dutt', DATE '1964-10-10', 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Guru_Dutt_2025_stamp.jpg'),
    ('Madhubala', DATE '1969-02-23', 'https://upload.wikimedia.org/wikipedia/commons/f/f4/Madhubala_on_2008_stamp.jpg'),
    ('Meena Kumari', DATE '1972-03-31', 'https://upload.wikimedia.org/wikipedia/commons/e/ed/Meena_Kumariji.jpg'),
    ('Prithviraj Kapoor', DATE '1972-05-29', 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Prithviraj_Kapoor_in_the_film_Ek_Raat.jpg'),
    ('Shammi Kapoor', DATE '2011-08-14', 'https://upload.wikimedia.org/wikipedia/commons/f/fd/Shammi_Kapoor_in_the_film_Rockstar.jpg'),
    ('Vinod Khanna', DATE '2017-04-27', 'https://upload.wikimedia.org/wikipedia/commons/1/13/VinodKhanna.jpg'),
    ('Nutan', DATE '1991-02-21', 'https://upload.wikimedia.org/wikipedia/commons/f/f0/Nutan.jpg'),
    ('Om Puri', DATE '2017-01-06', 'https://upload.wikimedia.org/wikipedia/commons/e/ee/OmPuriSept10TIFF.jpg'),
    ('Irrfan Khan', DATE '2020-04-29', 'https://upload.wikimedia.org/wikipedia/commons/2/27/Irrfan_Khan_still2.jpg'),
    ('Rishi Kapoor', DATE '2020-04-30', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Rishi_Kapoor_in_2016.jpg'),
    ('Sridevi', DATE '2018-02-24', 'https://upload.wikimedia.org/wikipedia/commons/e/e7/Sridevi.jpg'),
    ('Smita Patil', DATE '1986-12-13', 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Smita_Patil_2013_stamp_of_India_%28cropped%29.jpg'),
    ('Uttam Kumar', DATE '1980-07-24', 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Uttam_Kumar.jpg'),
    ('Sivaji Ganesan', DATE '2001-07-21', 'https://upload.wikimedia.org/wikipedia/commons/e/eb/Sivaji_ganesan_%28cropped%29.jpg'),
    ('Rajkumar', DATE '2006-04-12', 'https://upload.wikimedia.org/wikipedia/commons/3/3f/Rajkumar_2009_stamp_of_India_%28cropped%29.jpg'),
    ('Prem Nazir', DATE '1989-01-16', 'https://upload.wikimedia.org/wikipedia/commons/f/f4/Prem_Nazir_2013_stamp_of_India.jpg'),
    ('K. L. Saigal', DATE '1947-01-18', 'https://upload.wikimedia.org/wikipedia/commons/5/5c/K._L._Saigal.jpg'),
    ('Mohammed Rafi', DATE '1980-07-31', 'https://upload.wikimedia.org/wikipedia/commons/0/05/Mohammed_Rafi_2016_postcard_of_India_crop-flip.jpg'),
    ('Kishore Kumar', DATE '1987-10-13', 'https://upload.wikimedia.org/wikipedia/commons/c/c2/Kishore_Kumar_2016_postcard_of_India_%28cropped%29.jpg'),
    ('Lata Mangeshkar', DATE '2022-02-06', 'https://upload.wikimedia.org/wikipedia/commons/e/e4/Lata_Mangeshkar_-_still_29065_crop.jpg'),
    ('Mukesh', DATE '1976-08-27', 'https://upload.wikimedia.org/wikipedia/commons/3/3b/Mukesh_Indian_Singer.jpg'),
    ('Hemant Kumar', DATE '1989-09-26', 'https://upload.wikimedia.org/wikipedia/commons/f/fd/Hemant_Kumar_2016_stamp_of_India_%28cropped%29.jpg'),
    ('Geeta Dutt', DATE '1972-07-20', 'https://upload.wikimedia.org/wikipedia/commons/b/be/Portrait_of_Indian_playback_singer_Geeta_Dutt.jpg'),
    ('Talat Mahmood', DATE '1998-05-09', 'https://upload.wikimedia.org/wikipedia/commons/6/66/Talat_Mahmood_2016_postcard_of_India_crop.jpg'),
    ('Shamshad Begum', DATE '2013-04-23', 'https://upload.wikimedia.org/wikipedia/commons/5/55/Shamshad_Begum_2016_postcard_of_India_crop.jpg'),
    ('Vani Jayaram', DATE '2023-02-04', 'https://upload.wikimedia.org/wikipedia/commons/2/24/Vani_Jairam_2014_FF_%28cropped%29.jpg'),
    ('Bhimsen Joshi', DATE '2011-01-24', 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Bhimsen_Joshi.jpg'),
    ('R. D. Burman', DATE '1994-01-04', 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Rahul_Dev_Burman.jpg'),
    ('Bappi Lahiri', DATE '2022-02-15', 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Bappi_Lahiri_graces_musical_concert_%E2%80%98Rehmatein-3%E2%80%99.jpg'),
    ('Naushad', DATE '2006-05-05', 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Naushadsaab1.jpg'),
    ('M. S. Subbulakshmi', DATE '2004-12-11', 'https://upload.wikimedia.org/wikipedia/commons/5/5e/M._S._Subbulakshmi_%2803%29.jpg'),
    ('T. M. Soundararajan', DATE '2013-05-25', 'https://upload.wikimedia.org/wikipedia/commons/3/39/TM_Soundararajan_2016_stamp_of_India.jpg'),
    ('Ghantasala', DATE '1974-02-11', 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Ghantasala_Venkateswara_Rao_2003_stamp_of_India.jpg'),
    ('Rajesh Khanna', DATE '2012-07-18', 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Rajesh_Khanna_2013_stamp_of_India_%28cropped%29.jpg'),
    ('Shashi Kapoor', DATE '2017-12-04', 'https://upload.wikimedia.org/wikipedia/commons/7/75/ShashiKapoor.jpg'),
    ('Amrish Puri', DATE '2005-01-12', 'https://upload.wikimedia.org/wikipedia/commons/7/77/Amrish_Puri.jpg'),
    ('Kader Khan', DATE '2018-12-31', 'https://upload.wikimedia.org/wikipedia/commons/3/30/Kader_Khan_Sahab.jpg'),
    ('Dara Singh', DATE '2012-07-12', 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Dara_Singh_1.jpg'),
    ('A. K. Hangal', DATE '2012-08-26', 'https://upload.wikimedia.org/wikipedia/commons/4/46/A_K_Hangal_at_14th_Hira_Manik_Awards.jpg'),
    ('Sushant Singh Rajput', DATE '2020-06-14', 'https://upload.wikimedia.org/wikipedia/commons/9/96/Sushant_Singh_Rajput_snapped_at_the_promotions_of_%27M.S._Dhoni_-_The_Untold_Story%27_%28cropped%29.jpg'),
    ('Nanda', DATE '2014-03-25', 'https://upload.wikimedia.org/wikipedia/commons/5/53/Actress_Nanda_001.jpg'),
    ('Parveen Babi', DATE '2005-01-20', 'https://upload.wikimedia.org/wikipedia/commons/2/25/Parveen_Babi_Signature.png'),
    ('Reema Lagoo', DATE '2017-05-18', 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Reema_Lagoo_%281_May_2011%29.jpg'),
    ('Savitri', DATE '1981-12-26', 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Savitri_2011_stamp_of_India_%28cropped%29.jpg'),
    ('Gemini Ganesan', DATE '2005-03-22', 'https://upload.wikimedia.org/wikipedia/commons/c/c0/Gemini_Ganesan_2006_stamp_of_India_%28cropped%29.jpg'),
    ('N. T. Rama Rao', DATE '1996-01-18', 'https://upload.wikimedia.org/wikipedia/commons/8/8a/N._T._Rama_Rao%2C_1952.jpg'),
    ('M. G. Ramachandran', DATE '1987-12-24', 'https://upload.wikimedia.org/wikipedia/commons/4/44/MGR_portrait%2C_from_2017_Stamp.jpg'),
    ('Akkineni Nageswara Rao', DATE '2014-01-22', 'https://upload.wikimedia.org/wikipedia/commons/3/31/A.Nageswara_Rao.jpg'),
    ('Krishna', DATE '2022-11-15', 'https://upload.wikimedia.org/wikipedia/commons/f/f4/Krishna1964.jpg'),
    ('Puneeth Rajkumar', DATE '2021-10-29', 'https://upload.wikimedia.org/wikipedia/commons/7/7d/Puneeth_Rajkumar_%281%29.jpg'),
    ('Vishnuvardhan', DATE '2009-12-30', 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Vishnuvardhan_1.jpg'),
    ('Farooq Sheikh', DATE '2013-12-28', 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Farooq_Sheikh_at_Mirchi_Music_Awards_2011.jpg'),
    ('Tom Alter', DATE '2017-09-29', 'https://upload.wikimedia.org/wikipedia/commons/9/96/Tom_Alter%2C_2016.jpg'),
    ('Khayyam', DATE '2019-08-19', 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Hakim_Omar_Khayam_-_panoramio.jpg'),
    ('Salil Chowdhury', DATE '1995-09-05', 'https://upload.wikimedia.org/wikipedia/commons/6/6e/SalilChowdhury1002.jpg'),
    ('P. Leela', DATE '2005-10-31', 'https://upload.wikimedia.org/wikipedia/commons/1/11/P_Leela.jpg'),
    ('Jikki', DATE '2004-08-16', 'https://upload.wikimedia.org/wikipedia/commons/e/eb/PGKrishnaveni.jpg'),
    ('M. L. Vasanthakumari', DATE '1990-10-31', 'https://upload.wikimedia.org/wikipedia/commons/2/26/MLVasanthakumari.jpg'),
    ('Gangubai Hangal', DATE '2009-07-21', 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Gangubai_Hangal.jpg'),
    ('Sulochana Chavan', DATE '2022-12-10', 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Sulochana_Chavan.jpg'),
    ('C. N. Annadurai', DATE '1969-02-03', 'https://upload.wikimedia.org/wikipedia/commons/1/1a/CN_Annadurai.jpg'),
    ('E. M. S. Namboodiripad', DATE '1998-03-19', 'https://upload.wikimedia.org/wikipedia/commons/c/c1/EMS_Namboodiripad_2001_stamp_of_India.jpg'),
    ('Biju Patnaik', DATE '1997-04-17', 'https://upload.wikimedia.org/wikipedia/commons/2/20/Biju_Patnaik_2018_stamp_of_India.jpg'),
    ('J. Jayalalithaa', DATE '2016-12-05', 'https://upload.wikimedia.org/wikipedia/commons/3/3a/J_Jayalalithaa.jpg'),
    ('Bal Thackeray', DATE '2012-11-17', 'https://upload.wikimedia.org/wikipedia/commons/a/a5/Bal_Thackeray_%283x4_cropped%29.jpg'),
    ('George Fernandes', DATE '2019-01-29', 'https://upload.wikimedia.org/wikipedia/commons/3/39/George_Fernandes_%28cropped%29.jpg'),
    ('Jayaprakash Narayan', DATE '1979-10-08', 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Jawaharlal_Nehru_with_Jayaprakash_Narayan_Crop.jpg'),
    ('Ram Manohar Lohia', DATE '1967-10-12', 'https://upload.wikimedia.org/wikipedia/commons/5/59/Ram_Manohar_Lohia_1977_stamp_of_India.jpg'),
    ('Kanshi Ram', DATE '2006-10-09', 'https://upload.wikimedia.org/wikipedia/commons/7/7a/Kanshiram.jpg'),
    ('Deendayal Upadhyaya', DATE '1968-02-11', 'https://upload.wikimedia.org/wikipedia/commons/6/60/Deendayal_Upadhyaya_2018_stamp_of_India.jpg'),
    ('Gopinath Bordoloi', DATE '1950-08-05', 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Gopinath_Bordoloi.jpg'),
    ('Gopal Krishna Gokhale', DATE '1915-02-19', 'https://upload.wikimedia.org/wikipedia/commons/a/a5/GKGokhale.jpg'),
    ('Dadabhai Naoroji', DATE '1917-06-30', 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Dadabhai_Naoroji_1889.jpg'),
    ('Bal Gangadhar Tilak', DATE '1920-08-01', 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Bal_Gangadhar_Tilak_%281856-1920%29.webp'),
    ('Bhagat Singh', DATE '1931-03-23', 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Lahore_conspiracy_case_poster_9th_Oct_193o_jindal_sunam_12x9_copy_%28cropped%29.jpg'),
    ('Sheila Dikshit', DATE '2019-07-20', 'https://upload.wikimedia.org/wikipedia/commons/2/2b/The_Chairperson%2C_National_Advisory_Council%2C_Smt._Sonia_Gandhi_and_the_Chief_Minister_of_Delhi%2C_Smt._Sheila_Dikshit_after_casting_their_votes_in_Delhi_Assembly_Election%2C_at_Nirman_Bhavan_polling_booth%2C_in_New_Delhi_%28cropped%29.jpg'),
    ('Sushma Swaraj', DATE '2019-08-06', 'https://upload.wikimedia.org/wikipedia/commons/6/66/Secretary_Tillerson_is_Greeted_by_Indian_Minister_of_External_Affairs_Swaraj_%2824074726498%29_%28cropped%29.jpg'),
    ('V. P. Singh', DATE '2008-11-27', 'https://upload.wikimedia.org/wikipedia/commons/3/3f/Visit_of_Vishwanath_Pratap_Singh%2C_Indian_Minister_for_Trade%2C_to_the_CEC_%28cropped%29.jpg'),
    ('Zakir Husain', DATE '1969-05-03', 'https://upload.wikimedia.org/wikipedia/commons/a/af/President_Zakir_Husain_1998_stamp_of_India_%28cropped%29.jpg'),
    ('Fakhruddin Ali Ahmed', DATE '1977-02-11', 'https://upload.wikimedia.org/wikipedia/commons/3/32/President_Fakhruddin_Ali_Ahmed.jpg'),
    ('Shankar Dayal Sharma', DATE '1999-12-26', 'https://upload.wikimedia.org/wikipedia/commons/0/05/Shri_Shankar_Dayal_Sharma.jpg'),
    ('R. Venkataraman', DATE '2009-01-27', 'https://upload.wikimedia.org/wikipedia/commons/b/b2/Ramaswamy_Venkataraman_%282012_stamp_of_India%29_%28cropped%29.jpg'),
    ('P. V. Narasimha Rao', DATE '2004-12-23', 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Visit_of_Narasimha_Rao%2C_Indian_Minister_for_Foreign_Affairs%2C_to_the_CEC_%28cropped%29.jpg'),
    ('Mulayam Singh Yadav', DATE '2022-10-10', 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Uttar_Pradesh_Chief_Minister_Shri.Mulayam_Singh_Yadav%2C_addressing_at_the_National_Development_Council_52nd_Meeting%2C_at_Vigyan_Bhawan%2C_New_Delhi_on_December_9%2C_2006.jpg'),
    ('K. Kamaraj', DATE '1975-10-02', 'https://upload.wikimedia.org/wikipedia/commons/0/09/Kamarajar.jpg'),
    ('Rani Lakshmibai', DATE '1858-06-18', 'https://upload.wikimedia.org/wikipedia/commons/e/eb/Rani_of_jhansi.jpg'),
    ('N. G. Ranga', DATE '1995-06-09', 'https://upload.wikimedia.org/wikipedia/commons/7/73/NG_Ranga_2001_stamp_of_India.jpg'),
    ('B. P. Mandal', DATE '1982-04-13', 'https://upload.wikimedia.org/wikipedia/commons/d/d2/B.P_Mandal.jpg'),
    ('Madhavrao Scindia', DATE '2001-09-30', 'https://upload.wikimedia.org/wikipedia/commons/8/83/Madhavrao_Scindia_2005_stamp_of_India.jpg'),
    ('Pramod Mahajan', DATE '2006-05-03', 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Pramod_jee.jpg'),
    ('S. R. Bommai', DATE '2007-10-10', 'https://upload.wikimedia.org/wikipedia/commons/8/85/Somappa_Rayappa_Bommai_132.jpg'),
    ('Abdul Matin', DATE '2014-10-08', 'https://upload.wikimedia.org/wikipedia/commons/0/01/AbdulMatin_single.jpg'),
    ('Syed Shamsul Haq', DATE '2016-09-27', 'https://upload.wikimedia.org/wikipedia/commons/f/f4/Syed_Shamsul_Haque.png'),
    ('Mohammad Farhad', DATE '1987-10-09', 'https://upload.wikimedia.org/wikipedia/commons/7/7e/MOHAMMAD_FARHAD_%28cropped%29.webp')
)
UPDATE people AS p
SET photo_url = i.photo_url
FROM imported_images AS i
WHERE p.name = i.name
  AND p.death_date = i.death_date
  AND p.photo_url IS NULL;
