-- A curated addition of notable deceased American and international figures.
-- The list is not exhaustive; existing name/date pairs are skipped.
INSERT INTO people (
    id, name, birth_date, death_date, bio, lang, photo_url, occupation,
    birth_place, death_place, birth_precision, death_precision
)
SELECT
    gen_random_uuid(), v.name, v.birth_date, v.death_date,
    v.bio || E'\n\nSource: Wikipedia - https://en.wikipedia.org/wiki/' || v.source_slug,
    'en', NULL, v.occupation, v.birth_place, v.death_place,
    v.birth_precision, 'day'
FROM (VALUES
    ('Thurgood Marshall', DATE '1908-07-02', DATE '1993-01-24',
        'Thurgood Marshall was an American lawyer and civil rights advocate who successfully argued Brown v. Board of Education before the U.S. Supreme Court. In 1967, he became the first African American justice of the Supreme Court, serving until 1991.',
        'Jurist, Civil rights lawyer', 'Baltimore, Maryland, United States', 'Bethesda, Maryland, United States', 'day', 'Thurgood_Marshall'),
    ('John Lewis', DATE '1940-02-21', DATE '2020-07-17',
        'John Lewis was an American civil rights leader and politician. A leader of the 1960s student movement and chairman of the Student Nonviolent Coordinating Committee, he helped organize the Selma voting-rights marches and served in the U.S. House of Representatives for Georgia from 1987 until his death.',
        'Politician, Civil rights activist', 'Troy, Alabama, United States', 'Atlanta, Georgia, United States', 'day', 'John_Lewis_(civil_rights_leader)'),
    ('Cesar Chavez', DATE '1927-03-31', DATE '1993-04-23',
        'Cesar Chavez was an American labor leader and civil rights activist who co-founded the National Farm Workers Association, later the United Farm Workers. He organized farmworkers through nonviolent campaigns for improved wages and working conditions.',
        'Labor leader, Civil rights activist', 'Yuma, Arizona, United States', 'San Luis, Arizona, United States', 'day', 'C%C3%A9sar_Ch%C3%A1vez'),
    ('Sam Cooke', DATE '1931-01-22', DATE '1964-12-11',
        'Sam Cooke was an American singer, songwriter and entrepreneur whose smooth, influential vocals helped shape soul music. His recordings included You Send Me, A Change Is Gonna Come and Wonderful World.',
        'Singer, Songwriter', 'Clarksdale, Mississippi, United States', 'Los Angeles, California, United States', 'day', 'Sam_Cooke'),
    ('Dorothy Height', DATE '1912-03-24', DATE '2010-04-20',
        'Dorothy Height was an American civil rights and women''s rights activist. As longtime president of the National Council of Negro Women, she worked to expand opportunities for African American women and took part in the leadership of the U.S. civil rights movement.',
        'Civil rights activist', 'Richmond, Virginia, United States', 'Washington, D.C., United States', 'day', 'Dorothy_Height'),
    ('Bayard Rustin', DATE '1912-03-17', DATE '1987-08-24',
        'Bayard Rustin was an American civil rights activist and strategist who advised Martin Luther King Jr. and helped organize the 1963 March on Washington for Jobs and Freedom. He was also a prominent advocate for nonviolent resistance and LGBTQ rights.',
        'Civil rights activist, Organizer', 'West Chester, Pennsylvania, United States', 'New York City, New York, United States', 'day', 'Bayard_Rustin'),
    ('Pauli Murray', DATE '1910-11-20', DATE '1985-07-01',
        'Pauli Murray was an American lawyer, civil rights activist, writer and Episcopal priest. Their legal scholarship on race and sex discrimination influenced later civil rights arguments, and they co-founded the National Organization for Women.',
        'Lawyer, Civil rights activist, Writer', 'Baltimore, Maryland, United States', 'Pittsburgh, Pennsylvania, United States', 'day', 'Pauli_Murray'),
    ('Shirley Chisholm', DATE '1924-11-30', DATE '2005-01-01',
        'Shirley Chisholm was an American politician, educator and author. In 1968, she became the first African American woman elected to the U.S. Congress, and in 1972 she became the first Black candidate to seek a major-party nomination for president.',
        'Politician, Educator, Author', 'Brooklyn, New York, United States', 'Ormond Beach, Florida, United States', 'day', 'Shirley_Chisholm'),
    ('Hank Aaron', DATE '1934-02-05', DATE '2021-01-22',
        'Hank Aaron was an American professional baseball player who spent most of his career with the Milwaukee and Atlanta Braves. He broke Babe Ruth''s career home-run record in 1974 and remained a leading figure in baseball and civil rights.',
        'Baseball player', 'Mobile, Alabama, United States', 'Atlanta, Georgia, United States', 'day', 'Hank_Aaron'),
    ('Fela Kuti', DATE '1938-10-15', DATE '1997-08-02',
        'Fela Kuti was a Nigerian musician, bandleader and political activist who created and popularized Afrobeat, blending West African music with jazz and funk. His songs challenged military rule and social injustice in Nigeria.',
        'Musician, Composer, Political activist', 'Abeokuta, Nigeria', 'Lagos, Nigeria', 'day', 'Fela_Kuti'),
    ('Aung San', DATE '1915-02-13', DATE '1947-07-19',
        'Aung San was a Burmese independence leader and politician who negotiated for Burma''s independence from British rule. He helped establish the framework for a new Burmese state but was assassinated months before independence.',
        'Politician, Independence leader', 'Natmauk, British Burma', 'Rangoon, British Burma', 'day', 'Aung_San'),
    ('Ramon Magsaysay', DATE '1907-08-31', DATE '1957-03-17',
        'Ramon Magsaysay was a Filipino politician who served as the seventh president of the Philippines. Before becoming president, he served as secretary of national defense and became known for his role in suppressing the Hukbalahap insurgency and for rural outreach.',
        'Politician', 'Iba, Zambales, Philippine Islands', 'Mount Manunggal, Cebu, Philippines', 'day', 'Ramon_Magsaysay'),
    ('Osamu Tezuka', DATE '1928-11-03', DATE '1989-02-09',
        'Osamu Tezuka was a Japanese manga artist, animator and physician whose work helped shape modern manga and anime. His creations included Astro Boy, Black Jack and Phoenix, and he was often called the ''God of Manga'' in Japan.',
        'Manga artist, Animator, Physician', 'Toyonaka, Osaka, Japan', 'Tokyo, Japan', 'day', 'Osamu_Tezuka'),
    ('Ryuichi Sakamoto', DATE '1952-01-17', DATE '2023-03-28',
        'Ryuichi Sakamoto was a Japanese composer, musician and actor. A founding member of the electronic music group Yellow Magic Orchestra, he composed concert, electronic and film music, winning an Academy Award for The Last Emperor.',
        'Composer, Musician, Actor', 'Tokyo, Japan', 'Tokyo, Japan', 'day', 'Ryuichi_Sakamoto'),
    ('Oliver Tambo', DATE '1917-10-27', DATE '1993-04-24',
        'Oliver Tambo was a South African anti-apartheid politician and a founding member and long-serving president of the African National Congress. During years in exile, he led international efforts to oppose apartheid and support the liberation movement.',
        'Politician, Anti-apartheid activist', 'Nkantolo, Transvaal, South Africa', 'Johannesburg, South Africa', 'day', 'Oliver_Tambo'),
    ('Ken Saro-Wiwa', DATE '1941-10-10', DATE '1995-11-10',
        'Ken Saro-Wiwa was a Nigerian writer, television producer and environmental activist from the Ogoni people. He led the Movement for the Survival of the Ogoni People, campaigning against environmental damage in the Niger Delta; he was executed by Nigeria''s military government in 1995.',
        'Writer, Environmental activist', 'Bori, Rivers State, Nigeria', 'Port Harcourt, Nigeria', 'day', 'Ken_Saro-Wiwa'),
    ('Toru Takemitsu', DATE '1930-10-08', DATE '1996-02-20',
        'Toru Takemitsu was a Japanese composer who combined elements of Japanese musical tradition with modern classical techniques. His wide-ranging output included orchestral and chamber works, as well as scores for more than 90 films.',
        'Composer', 'Tokyo, Japan', 'Tokyo, Japan', 'day', 'T%C5%8Dru_Takemitsu'),
    ('Issey Miyake', DATE '1938-04-22', DATE '2022-08-05',
        'Issey Miyake was a Japanese fashion designer known for combining technology, experimentation and traditional craft. His work included innovative pleating and the Pleats Please and A-POC clothing lines, and his designs were exhibited internationally.',
        'Fashion designer', 'Hiroshima, Japan', 'Tokyo, Japan', 'day', 'Issey_Miyake'),
    ('Gabriel Garcia Marquez', DATE '1927-03-06', DATE '2014-04-17',
        'Gabriel Garcia Marquez was a Colombian novelist, journalist and screenwriter, widely regarded as one of the leading writers of the 20th century. His works include One Hundred Years of Solitude and Love in the Time of Cholera; he received the 1982 Nobel Prize in Literature.',
        'Writer, Journalist', 'Aracataca, Colombia', 'Mexico City, Mexico', 'day', 'Gabriel_Garc%C3%ADa_M%C3%A1rquez'),
    ('Vaclav Havel', DATE '1936-10-05', DATE '2011-12-18',
        'Vaclav Havel was a Czech writer, dissident and statesman. A leading figure in the Charter 77 human-rights movement, he became the last president of Czechoslovakia and the first president of the Czech Republic after the Velvet Revolution.',
        'Politician, Playwright, Dissident', 'Prague, Czechoslovakia', 'Hradecek, Czech Republic', 'day', 'V%C3%A1clav_Havel'),
    ('Aminu Kano', DATE '1920-01-01', DATE '1983-04-17',
        'Aminu Kano was a Nigerian politician and teacher who advocated for the rights of ordinary people in northern Nigeria. He founded the Northern Elements Progressive Union and was a prominent voice for political participation and social reform after independence.',
        'Politician, Teacher', 'Kano, Northern Nigeria Protectorate', 'Kano, Nigeria', 'year', 'Aminu_Kano'),
    ('Chien-Shiung Wu', DATE '1912-05-31', DATE '1997-02-16',
        'Chien-Shiung Wu was a Chinese-American experimental physicist whose work in nuclear physics included the experiment that demonstrated parity violation in weak interactions. She taught and conducted research at Columbia University and received the inaugural Wolf Prize in Physics.',
        'Physicist', 'Liuhe, Jiangsu, China', 'New York City, New York, United States', 'day', 'Chien-Shiung_Wu'),
    ('Jean-Michel Basquiat', DATE '1960-12-22', DATE '1988-08-12',
        'Jean-Michel Basquiat was an American artist who emerged from New York City''s downtown graffiti and art scenes. His paintings combined text, symbols and social commentary, addressing identity, power and Black history.',
        'Artist', 'Brooklyn, New York, United States', 'New York City, New York, United States', 'day', 'Jean-Michel_Basquiat'),
    ('Ousmane Sembene', DATE '1923-01-01', DATE '2007-06-09',
        'Ousmane Sembene was a Senegalese filmmaker and writer whose novels and films explored colonialism, labor and social change in Africa. Often described as a pioneer of African cinema, he directed films including Black Girl and Xala.',
        'Filmmaker, Writer', 'Ziguinchor, Senegal', 'Dakar, Senegal', 'year', 'Ousmane_Semb%C3%A8ne'),
    ('Jose Saramago', DATE '1922-11-16', DATE '2010-06-18',
        'Jose Saramago was a Portuguese novelist, playwright and journalist. His novels include Blindness and The Gospel According to Jesus Christ; he received the 1998 Nobel Prize in Literature, becoming the first Portuguese-language writer to receive the award.',
        'Writer, Journalist', 'Azinhaga, Portugal', 'Tias, Spain', 'day', 'Jos%C3%A9_Saramago')
) AS v(name, birth_date, death_date, bio, occupation, birth_place, death_place, birth_precision, source_slug)
WHERE NOT EXISTS (
    SELECT 1
    FROM people p
    WHERE p.name = v.name AND p.death_date = v.death_date
);
