# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: memorial.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ememorial.proto\x12\x0bmemorial.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe9\x01\n\x08Memorial\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x15\n\rdate_of_birth\x18\x03 \x01(\t\x12\x15\n\rdate_of_death\x18\x04 \x01(\t\x12\x11\n\tbiography\x18\x05 \x01(\t\x12\x12\n\ncreated_by\x18\x06 \x01(\t\x12\x0e\n\x06status\x18\x07 \x01(\t\x12.\n\ncreated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"E\n\x18GetDailyMemorialsRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x0c\n\x04page\x18\x03 \x01(\x05\"q\n\x19GetDailyMemorialsResponse\x12(\n\tmemorials\x18\x01 \x03(\x0b\x32\x15.memorial.v1.Memorial\x12\r\n\x05total\x18\x02 \x01(\x03\x12\x0c\n\x04page\x18\x03 \x01(\x05\x12\r\n\x05limit\x18\x04 \x01(\x05\"T\n\x15UpdateMemorialRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tbiography\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"A\n\x16UpdateMemorialResponse\x12\'\n\x08memorial\x18\x01 \x01(\x0b\x32\x15.memorial.v1.Memorial2\xd0\x01\n\x0fMemorialService\x12\x62\n\x11GetDailyMemorials\x12%.memorial.v1.GetDailyMemorialsRequest\x1a&.memorial.v1.GetDailyMemorialsResponse\x12Y\n\x0eUpdateMemorial\x12\".memorial.v1.UpdateMemorialRequest\x1a#.memorial.v1.UpdateMemorialResponseBEZCgithub.com/yourusername/mortalbook/memorial-service/gen/memorial/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'memorial_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZCgithub.com/yourusername/mortalbook/memorial-service/gen/memorial/v1'
  _globals['_MEMORIAL']._serialized_start=65
  _globals['_MEMORIAL']._serialized_end=298
  _globals['_GETDAILYMEMORIALSREQUEST']._serialized_start=300
  _globals['_GETDAILYMEMORIALSREQUEST']._serialized_end=369
  _globals['_GETDAILYMEMORIALSRESPONSE']._serialized_start=371
  _globals['_GETDAILYMEMORIALSRESPONSE']._serialized_end=484
  _globals['_UPDATEMEMORIALREQUEST']._serialized_start=486
  _globals['_UPDATEMEMORIALREQUEST']._serialized_end=570
  _globals['_UPDATEMEMORIALRESPONSE']._serialized_start=572
  _globals['_UPDATEMEMORIALRESPONSE']._serialized_end=637
  _globals['_MEMORIALSERVICE']._serialized_start=640
  _globals['_MEMORIALSERVICE']._serialized_end=848
# @@protoc_insertion_point(module_scope)
