# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.proto import memorial_pb2 as memorial__pb2


class MemorialServiceStub(object):
    """─────────────────────────────────────────────────────────────────────────────
    Service
    ─────────────────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDailyMemorials = channel.unary_unary(
                '/memorial.v1.MemorialService/GetDailyMemorials',
                request_serializer=memorial__pb2.GetDailyMemorialsRequest.SerializeToString,
                response_deserializer=memorial__pb2.GetDailyMemorialsResponse.FromString,
                )
        self.UpdateMemorial = channel.unary_unary(
                '/memorial.v1.MemorialService/UpdateMemorial',
                request_serializer=memorial__pb2.UpdateMemorialRequest.SerializeToString,
                response_deserializer=memorial__pb2.UpdateMemorialResponse.FromString,
                )


class MemorialServiceServicer(object):
    """─────────────────────────────────────────────────────────────────────────────
    Service
    ─────────────────────────────────────────────────────────────────────────────

    """

    def GetDailyMemorials(self, request, context):
        """Returns memorials whose death anniversary falls on the given date.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMemorial(self, request, context):
        """Partially updates a memorial and returns the updated entity.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemorialServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDailyMemorials': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDailyMemorials,
                    request_deserializer=memorial__pb2.GetDailyMemorialsRequest.FromString,
                    response_serializer=memorial__pb2.GetDailyMemorialsResponse.SerializeToString,
            ),
            'UpdateMemorial': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMemorial,
                    request_deserializer=memorial__pb2.UpdateMemorialRequest.FromString,
                    response_serializer=memorial__pb2.UpdateMemorialResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memorial.v1.MemorialService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MemorialService(object):
    """─────────────────────────────────────────────────────────────────────────────
    Service
    ─────────────────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def GetDailyMemorials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/memorial.v1.MemorialService/GetDailyMemorials',
            memorial__pb2.GetDailyMemorialsRequest.SerializeToString,
            memorial__pb2.GetDailyMemorialsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateMemorial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/memorial.v1.MemorialService/UpdateMemorial',
            memorial__pb2.UpdateMemorialRequest.SerializeToString,
            memorial__pb2.UpdateMemorialResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
